import type { UiLanguage } from "../services/ui-preferences";

export interface DocumentationFeature { title: string; description: string }
export interface DocumentationTopic {
  id: string;
  eyebrow: string;
  title: string;
  summary: string;
  steps: string[];
  features: DocumentationFeature[];
  keywords: string[];
}

const topic = (value: DocumentationTopic) => value;

const it: DocumentationTopic[] = [
  topic({ id: "start", eyebrow: "PRIMI PASSI", title: "Orientarsi in MLSM Studio", summary: "La Home separa gli strumenti in aree specializzate. Lingua, tema, impostazioni, memoria, supporto e Lonely Bot restano accessibili dalla barra principale.", steps: ["Entra nello Studio e scegli l’area adatta al risultato che vuoi ottenere.", "Importa i file richiesti: l’elaborazione parte solo dopo una tua azione esplicita.", "Controlla anteprima e parametri, quindi esporta il risultato nel formato desiderato."], features: [
    { title: "Progetti", description: "Nuovo, Apri, Salva, Annulla e Ripeti gestiscono il lavoro senza mescolare le sessioni delle diverse aree." },
    { title: "Impostazioni e Restore", description: "Configura provider AI e limiti; Restore verifica Node, npm, Python, FFmpeg, Rubber Band e i runtime isolati." },
    { title: "Memory", description: "Memoria locale consultabile per ritrovare attività e contesto. I dati privati non vengono aggiunti al repository." },
    { title: "Lonely Bot", description: "Assistente contestuale richiamabile dalla barra principale: legge la pagina corrente, consulta la knowledge base e può usare il provider configurato o il modello locale." },
  ], keywords: ["home", "iniziare", "impostazioni", "restore", "memoria", "lonely bot", "tema", "lingua", "progetto"] }),
  topic({ id: "sound", eyebrow: "AUDIO REACTIVE", title: "Sound Animation", summary: "Crea visualizzazioni, storie e tipografia cinetica sincronizzate con audio, ritmo e spettro.", steps: ["Scegli una modalità e importa l’audio.", "Completa l’analisi quando richiesta e configura gli elementi dai pannelli espandibili.", "Genera l’anteprima, controlla il sincronismo ed esporta."], features: [
    { title: "Visualizer", description: "Instrumental Falling, Cover Sphere, Stereo Unfold, Cube Animation, Circular Spectrum Auto Detector e Overlay Spectral trasformano spettro, canali e beat in animazione." },
    { title: "Storie e personaggi", description: "Teddy Walk/Sing e Comments Invasion costruiscono scene guidate dalla traccia e dai contenuti inseriti." },
    { title: "Testo e sottotitoli", description: "Pro Subtitles e Pixels Subtitles importano o generano cue, gestiscono stile per parola e preparano overlay per il montaggio." },
    { title: "Formati e compositing", description: "From 9:16 to 16:9, Cassette Desk e Song Player adattano il contenuto a layout social o player completi." },
  ], keywords: ["spettro", "visualizer", "sottotitoli", "pro subtitles", "cassette", "song player", "teddy", "commenti", "audio reattivo"] }),
  topic({ id: "photo-video", eyebrow: "RESTAURO", title: "Photo & Video Studio", summary: "Ripara, migliora e trasforma immagini o video mantenendo separati backend locali e servizi remoti.", steps: ["Carica una sorgente e scegli elaborazione locale, Gradio/Colab o MLX-DLSS quando compatibile.", "Configura modello, risoluzione e regolazioni; le opzioni lente sono esplicite.", "Avvia, controlla il progresso e scarica il risultato verificato."], features: [
    { title: "Static Watermark Remover", description: "Rimuove un watermark statico con maschera oppure usa un video pulito come riferimento, con scelta FPS, allineamento temporale e possibilità di proseguire in caso di avvisi." },
    { title: "Upscaler", description: "Supporta modelli Real-ESRGAN/RealESRNet, batch foto, confronto, fusione e regolazioni finali. MLX-DLSS è mostrato soltanto su Apple Silicon compatibile e dopo configurazione." },
    { title: "Frame Booster", description: "Interpola i fotogrammi con runtime Python isolato, mostra avvio backend, download modelli, log e avanzamento; il servizio viene chiuso uscendo dall’area." },
  ], keywords: ["upscaler", "dlss", "frame booster", "interpolazione", "watermark", "rimuovi filigrana", "realesrgan", "foto", "video"] }),
  topic({ id: "editor", eyebrow: "MONTAGGIO", title: "Video Editor", summary: "Editor non distruttivo con pool media, timeline multitraccia, compositing, audio mix ed export.", steps: ["Importa video, immagini e audio nel pool media.", "Trascina in timeline, taglia e allinea le clip; aggiungi transizioni, effetti e automazioni.", "Controlla il mix e l’anteprima, poi scegli codec, risoluzione e FPS di export."], features: [
    { title: "Timeline", description: "Tracce multiple, trim, split, snapping, riordino, visibilità e blocco delle clip." },
    { title: "Compositing e colore", description: "Trasformazioni, opacità, modalità di fusione, transizioni e correzione colore lavorano senza alterare i file originali." },
    { title: "Mix audio", description: "Pan, EQ, compressore, fade in/out e linee di inviluppo automatizzano parametri ed effetti nel tempo." },
    { title: "Export", description: "Esporta con impostazioni video/audio e interpolazione opzionale, mostrando stato e diagnostica." },
  ], keywords: ["timeline", "clip", "mix audio", "eq", "compressore", "pan", "fade", "inviluppo", "montaggio", "export"] }),
  topic({ id: "music", eyebrow: "PRODUZIONE AUDIO", title: "Music · AI Quantizer", summary: "Analizza timing e beat map, quantizza, allinea, restaura e masterizza attraverso un flusso guidato.", steps: ["Importa il brano e completa l’analisi forense.", "Esegui o salta esplicitamente Quantizzazione, Allineamento, Restauro e Mastering.", "Confronta la mappatura prima e dopo e scarica gli output quando il pacchetto è pronto."], features: [
    { title: "Quantizzazione", description: "Corregge il timing quando la beat map è valida; se il materiale non è quantizzabile lo segnala senza produrre una versione temporalmente sfalsata." },
    { title: "Allineamento", description: "Applica le opzioni scelte senza ripetere inutilmente la quantizzazione già completata." },
    { title: "Restauro e mastering", description: "Passaggi separati e confermabili, con avvisi professionali per correzioni elevate e nessuna riproduzione automatica al termine." },
    { title: "Mappatura", description: "La vista del timing resta disponibile anche dopo la quantizzazione per confrontare gli interventi." },
  ], keywords: ["quantizer", "quantizzazione", "beat map", "bpm", "alignment", "allineamento", "restauro", "master", "rubber band"] }),
  topic({ id: "lipsync", eyebrow: "POST-PRODUZIONE", title: "MLSM Post Lipsync", summary: "Riallinea il labiale a una nuova voce o al master definitivo usando ancore di parola e una time-map controllabile.", steps: ["Importa il video guida e la voce o il master di riferimento.", "Separa o analizza la voce e verifica le ancore rilevate.", "Correggi la time-map, genera l’anteprima ed esporta il video riallineato."], features: [
    { title: "Analisi vocale", description: "Rileva segmenti e parole utili all’allineamento senza sostituire la verifica visiva." },
    { title: "Time-map", description: "Mappa i tempi sorgente e destinazione, consentendo correzioni prima del rendering." },
    { title: "Export labiale", description: "Ricostruisce il video sincronizzato preservando il formato audio/video previsto dal progetto." },
  ], keywords: ["lipsync", "labiale", "time map", "voce", "sincronizzazione", "ancore"] }),
  topic({ id: "audio", eyebrow: "TRASCRIZIONE E VOCE", title: "Audio", summary: "Trascrive, revisiona, traduce e separa la voce con runtime e modelli configurabili.", steps: ["Importa l’audio e scegli modello locale o provider API configurato.", "Avvia Whisper con precisione compatibile con il dispositivo.", "Revisiona solo se richiesto, poi esporta SRT, VTT, TXT o JSON; usa Demucs per la separazione."], features: [
    { title: "Whisper", description: "Trascrizione con segmenti e timestamp; su Windows seleziona automaticamente una precisione efficiente quando float16/CUDA non sono disponibili." },
    { title: "Revisione LLM", description: "Disattivata di default e avviabile solo con testo di riferimento. Il revisore confronta dati Whisper e testo reale senza inventare parole." },
    { title: "Sottotitoli e traduzione", description: "Esporta formati standard e conserva la struttura temporale durante correzione o traduzione." },
    { title: "Separazione vocale", description: "Demucs isola voce e accompagnamento nel runtime dedicato." },
  ], keywords: ["whisper", "trascrizione", "srt", "vtt", "traduzione", "demucs", "separazione voce", "float16", "cuda"] }),
  topic({ id: "stickman", eyebrow: "ANIMAZIONE", title: "Stickman Animations", summary: "Area dedicata a scene verticali stilizzate, a partire da Bivio, con controlli guidati e anteprima.", steps: ["Scegli la scena e inserisci i contenuti richiesti.", "Configura stile, tempi e formato verticale.", "Controlla l’anteprima ed esporta l’animazione."], features: [{ title: "Bivio", description: "Costruisce una narrazione a scelta con personaggi stickman e composizione 9:16." }, { title: "Raccolta espandibile", description: "L’area è predisposta per aggiungere nuove animazioni mantenendo lo stesso flusso operativo." }], keywords: ["stickman", "bivio", "animazione verticale", "9:16"] }),
  topic({ id: "autopost", eyebrow: "PUBBLICAZIONE", title: "AutoPost", summary: "Importa articoli JSON e li pubblica su uno o più siti WordPress con tassonomie, media, coda e controlli per articolo.", steps: ["Configura i blog e verifica l’endpoint /wp-json/wp/v2/categories.", "Carica il JSON, scegli il blog origine e controlla anteprima, immagine e testo.", "Associa le categorie, elimina o modifica gli articoli, quindi programma o pubblica la coda."], features: [
    { title: "Categorie WordPress", description: "Aggiorna le categorie all’apertura e al cambio blog. Per gli altri blog usa MiniLM locale o LLM, soglia del coseno e selezione First/All." },
    { title: "Anteprima e modifica", description: "Mostra immagine e resa dell’articolo; testo e URL immagine sono modificabili prima del salvataggio." },
    { title: "Coda", description: "Intervallo, articoli per esecuzione, retry e stato rendono visibile cosa verrà pubblicato e quando." },
    { title: "Multi-blog", description: "Ogni articolo viene valutato separatamente; le categorie sopra soglia possono essere assegnate tutte." },
  ], keywords: ["wordpress", "categorie", "json", "pubblicazione", "coda", "coseno", "vector db", "blog", "anteprima articolo"] }),
  topic({ id: "reports", eyebrow: "DATA VISUALIZATION", title: "Reports", summary: "Carica dataset, crea campi calcolati e dashboard, anima serie temporali ed esporta report condivisibili.", steps: ["Crea una dashboard e carica CSV, TXT o Excel; puoi sostituire o accodare file compatibili.", "Aggiungi widget e trascina dimensioni/misure, quindi configura aggregazioni, assi, etichette e stile.", "Salva la dashboard o esporta JSON/HTML; usa la vista sola lettura per la condivisione."], features: [
    { title: "Dataset", description: "Preview, append/replace per file, rimozione dei singoli contributi e riconoscimento dei campi calcolati." },
    { title: "Widget", description: "KPI, linee, aree, barre orizzontali/verticali, dispersione, ciambella, mappe reali, pivot e Replicate XLS." },
    { title: "Campi calcolati", description: "Metalinguaggio con formule di riga e formule aggregate come SUM(a)/SUM(b), guida integrata e assistenza LLM locale o API." },
    { title: "Animazioni", description: "Time Series e Bar Race supportano periodo singolo/cumulativo, raggruppamento temporale, trend, massimo e transizioni progressive." },
    { title: "Replicate XLS", description: "Analizza un template, conserva formattazione, celle vuote e struttura, mappa aree e produce un report che cresce con i dati." },
  ], keywords: ["reports", "dashboard", "excel", "csv", "widget", "grafico", "campo calcolato", "bar race", "time series", "replicate xls", "append"] }),
  topic({ id: "postit", eyebrow: "CONOSCENZA LOCALE", title: "Post-it", summary: "Salva note e link privati, organizza post-it in flussi e ritrova il contenuto tramite ricerca semantica locale.", steps: ["Crea un post-it con titolo, testo e link; la favicon viene recuperata e salvata localmente.", "Collega post-it esistenti in un flusso e descrivi il processo.", "Cerca per significato: i risultati vengono riordinati per similarità del coseno."], features: [
    { title: "Post-it", description: "Titolo, testo, link e favicon; un elemento può essere modificato o eliminato senza pubblicarlo nel repository." },
    { title: "Flussi", description: "Sequenze riutilizzabili di post-it con descrizione, apertura dei singoli link e rimozione di elementi dal flusso." },
    { title: "Ricerca vettoriale", description: "Embedding locali confrontano la richiesta con note e flussi nello stesso spazio vettoriale." },
  ], keywords: ["post-it", "note", "link", "favicon", "flusso", "ricerca semantica", "coseno", "privato"] }),
  topic({ id: "streamer", eyebrow: "ASCOLTO E METERING", title: "Streamer Audio Viewer", summary: "Riproduce una coda di file locali o player ufficiali e visualizza misure stereo professionali in tempo reale.", steps: ["Aggiungi file o una sorgente web e scegli la cattura audio di sistema quando necessaria.", "Gestisci coda, preferiti e avanzamento automatico o manuale.", "Personalizza i widget o entra a schermo intero; il player resta attivo e udibile."], features: [
    { title: "Player e coda", description: "Giradischi, copertina non tagliata, preferiti, eliminazione brani e scelta se passare automaticamente al successivo." },
    { title: "Analisi stereo", description: "Meter, spettro stereo, LUFS, immagine stereo e correlazione di fase usano entrambi i canali anche con audio di sistema da Chrome." },
    { title: "Widget", description: "Riordinabili, eliminabili e recuperabili dal pannello laterale; a schermo intero si adattano al viewport e seguono il tema dell’app." },
  ], keywords: ["streamer", "stereo", "mono", "lufs", "meter", "spettro", "correlazione fase", "audio sistema", "chrome", "coda"] }),
  topic({ id: "documentation", eyebrow: "GUIDA", title: "Documentation", summary: "Guida bilingue dell’intera applicazione con navigazione per area e ricerca intelligente interamente locale.", steps: ["Scrivi un obiettivo, un problema o il nome di un controllo nella barra di ricerca.", "La ricerca lessicale mostra subito i risultati; MiniLM li riordina poi per significato.", "Apri il risultato per raggiungere la sezione e segui il percorso operativo."], features: [
    { title: "Ricerca semantica", description: "MiniLM multilingue genera embedding locali; WebGPU è preferita e WASM è il fallback compatibile." },
    { title: "Privacy", description: "Query e indice restano nel browser. Nessun contenuto della ricerca viene inviato a servizi esterni." },
    { title: "Fallback immediato", description: "Se il modello non è disponibile, titoli, descrizioni e parole chiave restano ricercabili localmente." },
  ], keywords: ["documentazione", "guida", "cerca", "ricerca intelligente", "minilm", "semantic search", "aiuto"] }),
  topic({ id: "privacy", eyebrow: "SICUREZZA", title: "Dati, runtime ed esportazione", summary: "MLSM privilegia elaborazione e archivi locali, isola i runtime Python e rende esplicito quando usa API o endpoint esterni.", steps: ["Controlla il motore indicato prima di avviare un lavoro.", "Esci dall’area per chiudere il servizio Python dedicato quando non serve più.", "Conserva fuori da Git credenziali, modelli, DLL, file di lavoro e database locali."], features: [
    { title: "Runtime on demand", description: "Upscaler, Frame Booster, Quantizer, Song Player e TTS avviano il proprio ambiente soltanto quando richiesto e lo arrestano all’uscita." },
    { title: "Provider AI", description: "Locale e API configurate sono selezionabili dove previste; limiti RPM/token aiutano a serializzare le richieste." },
    { title: "Diagnostica", description: "Restore e i log dei backend distinguono download, avvio, health check, elaborazione ed errore." },
  ], keywords: ["privacy", "locale", "venv", "python", "runtime", "api", "credenziali", "gitignore", "log", "restore"] }),
];

const en: DocumentationTopic[] = it.map((source) => ({ ...source }));

const english: Record<string, Omit<DocumentationTopic, "id">> = {
  start: { eyebrow: "GETTING STARTED", title: "Finding your way around MLSM Studio", summary: "The Home screen separates tools into focused workspaces. Language, theme, Settings, Memory, Support and Lonely Bot remain available from the main bar.", steps: ["Enter the Studio and choose the workspace that matches the result you need.", "Import the required files; processing starts only after an explicit action.", "Review preview and parameters, then export in the required format."], features: [{ title: "Projects", description: "New, Open, Save, Undo and Redo manage work without mixing sessions across workspaces." }, { title: "Settings and Restore", description: "Configure AI providers and limits; Restore checks Node, npm, Python, FFmpeg, Rubber Band and isolated runtimes." }, { title: "Memory", description: "Local searchable memory for activities and context. Private data is never added to the repository." }, { title: "Lonely Bot", description: "Contextual assistant available from the main bar. It reads the current page and can use the selected provider or the local model." }], keywords: ["home", "getting started", "settings", "restore", "memory", "lonely bot", "theme", "language", "project"] },
  sound: { eyebrow: "AUDIO REACTIVE", title: "Sound Animation", summary: "Build visualizers, stories and kinetic typography synchronized to audio, rhythm and spectrum.", steps: ["Choose a mode and import audio.", "Complete analysis when required and configure elements in the collapsible panels.", "Generate a preview, verify synchronization and export."], features: [{ title: "Visualizers", description: "Instrumental Falling, Cover Sphere, Stereo Unfold, Cube Animation, Circular Spectrum Auto Detector and Overlay Spectral turn spectrum, channels and beats into animation." }, { title: "Stories and characters", description: "Teddy Walk/Sing and Comments Invasion create scenes driven by the track and supplied content." }, { title: "Text and subtitles", description: "Pro Subtitles and Pixels Subtitles import or generate cues and manage per-word styling." }, { title: "Formats and compositing", description: "From 9:16 to 16:9, Cassette Desk and Song Player adapt content to social layouts or complete players." }], keywords: ["spectrum", "visualizer", "subtitles", "cassette", "song player", "audio reactive"] },
  "photo-video": { eyebrow: "RESTORATION", title: "Photo & Video Studio", summary: "Repair, enhance and transform images or video while keeping local backends and remote services explicit.", steps: ["Load a source and choose Local, Gradio/Colab or MLX-DLSS when compatible.", "Configure model, resolution and adjustments; slow options are clearly identified.", "Start, monitor progress and download the verified output."], features: [{ title: "Static Watermark Remover", description: "Removes a static watermark with a mask or clean reference video, including FPS choice and temporal alignment." }, { title: "Upscaler", description: "Real-ESRGAN/RealESRNet models, photo batches, comparison, blending and final adjustments. MLX-DLSS appears only on compatible Apple Silicon." }, { title: "Frame Booster", description: "Interpolates frames through an isolated Python runtime with backend startup, model download, logs and progress." }], keywords: ["upscaler", "dlss", "frame booster", "interpolation", "watermark", "photo", "video"] },
  editor: { eyebrow: "EDITING", title: "Video Editor", summary: "Non-destructive editor with media pool, multitrack timeline, compositing, audio mixing and export.", steps: ["Import video, images and audio into the media pool.", "Drag onto the timeline, trim and align clips; add transitions, effects and automation.", "Check mix and preview, then choose export codec, resolution and FPS."], features: [{ title: "Timeline", description: "Multiple tracks, trim, split, snapping, reorder, visibility and locking." }, { title: "Compositing and colour", description: "Transforms, opacity, blend modes, transitions and colour correction preserve source files." }, { title: "Audio mix", description: "Pan, EQ, compressor, fades and envelope lines automate parameters over time." }, { title: "Export", description: "Video/audio settings and optional interpolation with visible status and diagnostics." }], keywords: ["timeline", "clip", "audio mix", "eq", "compressor", "pan", "fade", "editing", "export"] },
  music: { eyebrow: "AUDIO PRODUCTION", title: "Music · AI Quantizer", summary: "Analyze timing and beat maps, quantize, align, restore and master through a guided workflow.", steps: ["Import the track and complete forensic analysis.", "Run or explicitly skip Quantize, Align, Restore and Master.", "Compare mapping before and after, then download the prepared outputs."], features: [{ title: "Quantization", description: "Corrects timing when the beat map is valid; non-quantizable material is reported without producing a shifted track." }, { title: "Alignment", description: "Applies selected options without unnecessarily repeating completed quantization." }, { title: "Restoration and mastering", description: "Separate confirmable stages, professional warnings and no automatic playback on completion." }, { title: "Mapping", description: "Timing remains visible after quantization for comparison." }], keywords: ["quantizer", "beat map", "bpm", "alignment", "restoration", "mastering"] },
  lipsync: { eyebrow: "POST-PRODUCTION", title: "MLSM Post Lipsync", summary: "Realign lip movement to a new vocal or final master using word anchors and an editable time map.", steps: ["Import guide video and reference vocal or master.", "Analyze the voice and verify detected anchors.", "Correct the time map, preview and export."], features: [{ title: "Vocal analysis", description: "Detects segments and words useful for alignment while preserving visual review." }, { title: "Time map", description: "Maps source and destination timing before rendering." }, { title: "Lip-sync export", description: "Rebuilds synchronized video with the project’s intended audio/video format." }], keywords: ["lipsync", "time map", "vocal", "synchronization", "anchors"] },
  audio: { eyebrow: "TRANSCRIPTION AND VOICE", title: "Audio", summary: "Transcribe, review, translate and separate vocals with configurable runtimes and models.", steps: ["Import audio and select a local model or configured API provider.", "Run Whisper with precision compatible with the device.", "Review only when requested, export SRT/VTT/TXT/JSON, or use Demucs for separation."], features: [{ title: "Whisper", description: "Segmented transcription with timestamps and automatic compatible precision on Windows." }, { title: "LLM review", description: "Off by default and available only with reference text; compares Whisper data to real wording." }, { title: "Subtitles and translation", description: "Exports standard formats while preserving timing during correction or translation." }, { title: "Vocal separation", description: "Demucs isolates vocal and accompaniment in its dedicated runtime." }], keywords: ["whisper", "transcription", "srt", "vtt", "translation", "demucs", "float16", "cuda"] },
  stickman: { eyebrow: "ANIMATION", title: "Stickman Animations", summary: "Focused workspace for stylized vertical scenes, starting with Bivio.", steps: ["Choose the scene and supply its content.", "Configure style, timing and vertical format.", "Review and export."], features: [{ title: "Bivio", description: "Builds a choice-based story with stick figures in 9:16." }, { title: "Expandable collection", description: "New animations can use the same guided workflow." }], keywords: ["stickman", "bivio", "vertical animation", "9:16"] },
  autopost: { eyebrow: "PUBLISHING", title: "AutoPost", summary: "Import JSON articles and publish to one or more WordPress sites with taxonomy, media, queue and per-article controls.", steps: ["Configure blogs and verify /wp-json/wp/v2/categories.", "Load JSON, choose the source blog and review preview, image and text.", "Map categories, edit or remove articles, then schedule or publish."], features: [{ title: "WordPress categories", description: "Refreshes on open and blog change. Other blogs can use local MiniLM or an LLM, cosine threshold and First/All selection." }, { title: "Preview and editing", description: "Shows image and rendered article; text and image URL are editable." }, { title: "Queue", description: "Interval, posts per run, retries and status show what will publish and when." }, { title: "Multi-blog", description: "Every article is evaluated independently and every category above threshold can be selected." }], keywords: ["wordpress", "categories", "json", "publishing", "queue", "cosine", "vector db", "blog"] },
  reports: { eyebrow: "DATA VISUALIZATION", title: "Reports", summary: "Load datasets, create calculated fields and dashboards, animate time series and export shareable reports.", steps: ["Create a dashboard and load CSV, TXT or Excel; replace or append compatible files.", "Add widgets and assign dimensions/measures, aggregations, axes, labels and style.", "Save or export JSON/HTML and use read-only sharing."], features: [{ title: "Datasets", description: "Preview, append/replace per file, remove individual sources and identify calculated fields." }, { title: "Widgets", description: "KPI, line, area, horizontal/vertical bar, scatter, doughnut, real maps, pivot and Replicate XLS." }, { title: "Calculated fields", description: "Row and aggregate formulas such as SUM(a)/SUM(b), built-in guide and local/API LLM assistance." }, { title: "Animations", description: "Time Series and Bar Race support period/cumulative values, grouping, trends, maxima and progressive transitions." }, { title: "Replicate XLS", description: "Analyzes a template, preserves formatting and maps areas into a report that grows with data." }], keywords: ["reports", "dashboard", "excel", "csv", "widget", "chart", "calculated field", "bar race", "time series"] },
  postit: { eyebrow: "LOCAL KNOWLEDGE", title: "Post-it", summary: "Save private notes and links, organize them into flows and retrieve content with local semantic search.", steps: ["Create a post-it with title, text and link; its favicon is stored locally.", "Connect existing post-its into a described flow.", "Search by meaning and review cosine-ranked results."], features: [{ title: "Post-its", description: "Title, text, link and favicon; edit or delete without publishing to the repository." }, { title: "Flows", description: "Reusable sequences with descriptions, clickable links and removable items." }, { title: "Vector search", description: "Local embeddings compare queries, notes and flows in one vector space." }], keywords: ["post-it", "notes", "links", "favicon", "flow", "semantic search", "cosine", "private"] },
  streamer: { eyebrow: "LISTENING AND METERING", title: "Streamer Audio Viewer", summary: "Play local queues or official players and display professional stereo measurements in real time.", steps: ["Add files or a web source and select system-audio capture when required.", "Manage queue, favourites and automatic or manual advance.", "Customize widgets or enter full screen; the player remains active and audible."], features: [{ title: "Player and queue", description: "Turntable, uncropped artwork, favourites, remove tracks and automatic advance." }, { title: "Stereo analysis", description: "Meter, stereo spectrum, LUFS, stereo image and phase correlation use both channels, including Chrome system audio." }, { title: "Widgets", description: "Reorder, remove and restore from the side drawer; full screen adapts to the viewport and app theme." }], keywords: ["streamer", "stereo", "mono", "lufs", "meter", "spectrum", "phase", "system audio", "chrome", "queue"] },
  documentation: { eyebrow: "GUIDE", title: "Documentation", summary: "Bilingual guide for the complete application with workspace navigation and fully local intelligent search.", steps: ["Type an objective, issue or control name in search.", "Lexical search responds immediately; MiniLM then reranks by meaning.", "Open a result and follow its workflow."], features: [{ title: "Semantic search", description: "Multilingual MiniLM produces local embeddings with WebGPU preferred and WASM fallback." }, { title: "Privacy", description: "Queries and the index stay in the browser and are never sent to external services." }, { title: "Immediate fallback", description: "Titles, descriptions and keywords remain searchable if the model is unavailable." }], keywords: ["documentation", "guide", "search", "intelligent search", "minilm", "semantic"] },
  privacy: { eyebrow: "SECURITY", title: "Data, runtimes and export", summary: "MLSM prioritizes local processing and storage, isolates Python runtimes and clearly identifies external APIs or endpoints.", steps: ["Check the indicated engine before starting.", "Leave a workspace to stop its dedicated Python service.", "Keep credentials, models, DLLs, work files and local databases out of Git."], features: [{ title: "On-demand runtimes", description: "Upscaler, Frame Booster, Quantizer, Song Player and TTS start only when required and stop on exit." }, { title: "AI providers", description: "Local and configured API providers can be selected where supported; RPM/token limits serialize requests." }, { title: "Diagnostics", description: "Restore and backend logs distinguish download, startup, health check, processing and failure." }], keywords: ["privacy", "local", "venv", "python", "runtime", "api", "credentials", "gitignore", "logs", "restore"] },
};

for (const item of en) Object.assign(item, english[item.id]);

export function documentationTopics(language: UiLanguage): DocumentationTopic[] { return language === "en" ? en : it; }
export function documentationSearchText(item: DocumentationTopic): string {
  return [item.title, item.eyebrow, item.summary, ...item.steps, ...item.keywords, ...item.features.flatMap((feature) => [feature.title, feature.description])].join(". ");
}
