import { useEffect, useMemo, useRef, useState } from "react";
import type { LlmProvider, LlmSettings } from "../services/studio-settings";
import type { UiLanguage } from "../services/ui-preferences";
import { analyzeCalculatedFormula, MLSM_FORMULA_GUIDE, MLSM_FORMULA_GUIDE_IT } from "./calculated-fields";
import { getLlmSettings, loadReportsAiSettings, providerLabels, resolveReportsProvider, saveReportsAiSettings, suggestCalculatedField, type ReportsAiSettings } from "./reports-ai";
import { ReportIcon } from "./ReportIcon";
import type { ReportDataset } from "./types";

export function ReportsSettingsDialog({ language, onClose }: { language: UiLanguage; onClose: () => void }) {
  const [value, setValue] = useState<ReportsAiSettings>(loadReportsAiSettings);
  const [llm, setLlm] = useState<LlmSettings | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void getLlmSettings().then(setLlm).catch(reason => setError(reason instanceof Error ? reason.message : String(reason))); }, []);
  const configured = llm ? (Object.keys(llm.providers) as LlmProvider[]).filter(provider => llm.providers[provider].configured && llm.providers[provider].enabled) : [];
  const ready = Boolean(llm && resolveReportsProvider(value, llm));
  const save = () => { saveReportsAiSettings(value); onClose(); };
  return <div className="rpt-modal-backdrop" onClick={event => { if (event.target === event.currentTarget) onClose(); }}><section className="rpt-modal rpt-ai-settings" role="dialog" aria-modal="true" aria-labelledby="rpt-ai-settings-title"><header><div><span className="rpt-eyebrow">REPORTS · AI</span><h2 id="rpt-ai-settings-title">{language === "en" ? "Reports AI settings" : "Impostazioni AI di Reports"}</h2><p>{language === "en" ? "Choose which API model already configured in MLSM Studio will assist formulas and analyze Replicate XLS templates." : "Scegli quale modello API già configurato in MLSM Studio assisterà le formule e analizzerà i template Replica Excel."}</p></div><button className="rpt-icon-button" aria-label={language === "en" ? "Close settings" : "Chiudi impostazioni"} onClick={onClose}><ReportIcon name="close" /></button></header>
    {error && <p className="rpt-inline-error">{error}</p>}
    <label className="rpt-animation-toggle"><input type="checkbox" checked={value.enabled} onChange={event => setValue(current => ({ ...current, enabled: event.target.checked }))} /><span><strong>{language === "en" ? "Enable AI assistance" : "Abilita assistenza AI"}</strong><small>{language === "en" ? "Manual formulas and manual spreadsheet mapping remain available when disabled." : "Le formule e la mappatura manuale dei fogli restano disponibili anche se disattivata."}</small></span></label>
    <label className="rpt-control">{language === "en" ? "Provider for Reports" : "Provider per Reports"}<select value={value.provider} onChange={event => setValue(current => ({ ...current, provider: event.target.value as LlmProvider | "" }))}><option value="">{language === "en" ? "Use Studio active provider" : "Usa provider attivo di Studio"}</option>{configured.map(provider => <option key={provider} value={provider}>{providerLabels[provider]} · {llm!.providers[provider].model}</option>)}</select><small>{ready ? (language === "en" ? "Ready for formulas and spreadsheet models." : "Pronto per formule e modelli dei fogli.") : (language === "en" ? "No compatible configured API provider selected." : "Nessun provider API configurato e compatibile selezionato.")}</small></label>
    <div className="rpt-ai-settings-actions"><button className="rpt-button" onClick={() => { window.dispatchEvent(new Event("mlsm:open-settings")); onClose(); }}><ReportIcon name="settings" />{language === "en" ? "Manage API keys" : "Gestisci API key"}</button><button className="rpt-button rpt-button-primary" onClick={save}><ReportIcon name="save" />{language === "en" ? "Save Reports settings" : "Salva impostazioni Reports"}</button></div>
  </section></div>;
}

export function CalculatedFieldDialog({ dataset, language, onClose, onCreate }: { dataset: ReportDataset; language: UiLanguage; onClose: () => void; onCreate: (value: { name: string; formula: string; description: string }) => void }) {
  const [name, setName] = useState(""); const [formula, setFormula] = useState(""); const [description, setDescription] = useState("");
  const [request, setRequest] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [generatedBy, setGeneratedBy] = useState("");
  const abort = useRef<AbortController | null>(null);
  useEffect(() => () => abort.current?.abort(), []);
  const analysis = useMemo(() => { try { return formula.trim() ? analyzeCalculatedFormula(formula, dataset) : null; } catch { return null; } }, [dataset, formula]);
  const validate = () => { const result = analyzeCalculatedFormula(formula, dataset); if (!name.trim()) throw new Error(language === "en" ? "Give the calculated field a name." : "Assegna un nome al campo calcolato."); return result; };
  const generate = async () => {
    abort.current?.abort(); const controller = new AbortController(); abort.current = controller; setBusy(true); setError("");
    try { const suggestion = await suggestCalculatedField(request, dataset, language, controller.signal); setName(suggestion.name); setFormula(suggestion.formula); setDescription(suggestion.description); setGeneratedBy(`${providerLabels[suggestion.provider]} · ${suggestion.model}`); }
    catch (reason) { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : String(reason)); }
    finally { if (!controller.signal.aborted) setBusy(false); }
  };
  const submit = () => { try { validate(); onCreate({ name: name.trim(), formula: formula.trim(), description: description.trim() }); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } };
  return <div className="rpt-modal-backdrop" onClick={event => { if (event.target === event.currentTarget && !busy) onClose(); }}><section className="rpt-modal rpt-calculated-dialog" role="dialog" aria-modal="true" aria-labelledby="rpt-calculated-title"><header><div><span className="rpt-eyebrow">MLSM FORMULA</span><h2 id="rpt-calculated-title">{language === "en" ? "Create a calculated field" : "Crea un campo calcolato"}</h2><p>{language === "en" ? "Write the formula directly or describe the result: the configured LLM knows the complete language specification and available fields." : "Scrivi direttamente la formula oppure descrivi il risultato: il modello configurato conosce la specifica completa del linguaggio e i campi disponibili."}</p></div><button className="rpt-icon-button" disabled={busy} aria-label={language === "en" ? "Close" : "Chiudi"} onClick={onClose}><ReportIcon name="close" /></button></header>
    <div className="rpt-calculated-grid"><div className="rpt-calculated-editor">
      <section className="rpt-ai-prompt"><label className="rpt-control">{language === "en" ? "Describe what it should calculate" : "Descrivi cosa deve calcolare"}<textarea rows={3} value={request} placeholder={language === "en" ? "Example: revenue per distinct customer, calculated correctly for every chart group" : "Esempio: ricavo per cliente distinto, calcolato correttamente per ogni gruppo del grafico"} onChange={event => setRequest(event.target.value)} /></label><button className="rpt-button rpt-button-primary" disabled={busy || !request.trim()} onClick={() => void generate()}><ReportIcon name="sparkle" />{busy ? (language === "en" ? "Generating…" : "Generazione…") : (language === "en" ? "Generate with AI" : "Genera con AI")}</button>{generatedBy && <small>{language === "en" ? "Generated by" : "Generata da"} {generatedBy}</small>}</section>
      <label className="rpt-control">{language === "en" ? "Field name" : "Nome campo"}<input maxLength={120} value={name} onChange={event => setName(event.target.value)} /></label>
      <label className="rpt-control">Formula<textarea aria-label="Formula" className="rpt-formula-editor" rows={5} spellCheck={false} value={formula} placeholder="SUM([Revenue]) / SUM([Units])" onChange={event => { setFormula(event.target.value); setError(""); }} /><small>{analysis ? (analysis.aggregate ? (language === "en" ? "Aggregate formula · evaluated on each widget or pivot group" : "Formula aggregata · valutata su ogni gruppo di widget o pivot") : (language === "en" ? "Row formula · the widget applies its selected aggregation afterwards" : "Formula di riga · il widget applica poi l’aggregazione selezionata")) : (language === "en" ? "Use [Field name] to reference columns." : "Usa [Nome campo] per riferirti alle colonne.")}</small></label>
      <label className="rpt-control">{language === "en" ? "Description (optional)" : "Descrizione (opzionale)"}<input maxLength={2000} value={description} onChange={event => setDescription(event.target.value)} /></label>
      {error && <p className="rpt-inline-error" role="alert">{error}</p>}
      <div className="rpt-calculated-actions"><button className="rpt-button" disabled={busy} onClick={onClose}>{language === "en" ? "Cancel" : "Annulla"}</button><button className="rpt-button rpt-button-primary" disabled={busy || !name.trim() || !formula.trim()} onClick={submit}><ReportIcon name="plus" />{language === "en" ? "Create field" : "Crea campo"}</button></div>
    </div><aside className="rpt-formula-guide"><h3>{language === "en" ? "How MLSM Formula works" : "Come funziona MLSM Formula"}</h3><p>{language === "en" ? "A compact language inspired by Tableau calculated fields and spreadsheet formulas, with explicit aggregate semantics." : "Un linguaggio compatto ispirato ai campi calcolati Tableau e alle formule dei fogli di calcolo, con semantica aggregata esplicita."}</p><pre>{language === "en" ? MLSM_FORMULA_GUIDE : MLSM_FORMULA_GUIDE_IT}</pre></aside></div>
  </section></div>;
}
