import { beforeEach, describe, expect, it } from "vitest";
import type { AudioAnalysisResult } from "@rbs/audio-analysis";
import { buildPrimaryBeatEvents, useProjectStore } from "./project-store";

describe("project event history", () => {
  beforeEach(() => useProjectStore.getState().newProject());
  it("annulla e ripete aggiunta, spostamento e cancellazione", () => {
    const store = useProjectStore.getState();
    store.attachAudio({ path: "track.wav", fileName: "track.wav", hash: "a".repeat(64), durationSeconds: 10, sampleRate: 48_000, channels: 2, codec: "pcm", fileSize: 100 }, []);
    useProjectStore.getState().addEvent(2); const id = useProjectStore.getState().project.events[0]?.id; expect(id).toBeTruthy();
    useProjectStore.getState().moveEvent(id ?? "", 3); expect(useProjectStore.getState().project.events[0]?.timeSeconds).toBe(3);
    useProjectStore.getState().undoEvents(); expect(useProjectStore.getState().project.events[0]?.timeSeconds).toBe(2);
    useProjectStore.getState().redoEvents(); expect(useProjectStore.getState().project.events[0]?.timeSeconds).toBe(3);
    useProjectStore.getState().deleteEvent(id ?? ""); expect(useProjectStore.getState().project.events).toHaveLength(0);
    useProjectStore.getState().undoEvents(); expect(useProjectStore.getState().project.events).toHaveLength(1);
  });
  it("mantiene coerenti secondi e indice campione", () => { const store = useProjectStore.getState(); store.attachAudio({ path: "track.wav", fileName: "track.wav", hash: "b".repeat(64), durationSeconds: 10, sampleRate: 44_100, channels: 1, codec: "pcm", fileSize: 100 }, []); useProjectStore.getState().addEvent(1.25); const event = useProjectStore.getState().project.events[0]; expect(event?.timeSamples).toBe(55_125); });
  it("usa un solo impatto per beat e scarta classificazioni armoniche incerte", () => { const result: AudioAnalysisResult = { analyzerVersion: "test", durationSeconds: 2, sampleRate: 1_000, globalBpm: 120, bpmConfidence: .9, localTempo: [], beats: [.5, 1, 1.5], downbeats: [.5], events: [{ timeSeconds: .5, timeSamples: 500, type: "piano", strength: .7, confidence: .7, frequencyBand: "mid" }, { timeSeconds: .72, timeSamples: 720, type: "snare", strength: .9, confidence: .9, frequencyBand: "mid" }, { timeSeconds: 1, timeSamples: 1_000, type: "strings", strength: .75, confidence: .93, frequencyBand: "mid" }, { timeSeconds: 1.5, timeSamples: 1_500, type: "kick", strength: .9, confidence: .9, frequencyBand: "low" }], energy: [], onsetEnvelope: [], spectralFlux: [], lowEnergySegments: [] }; const events = buildPrimaryBeatEvents(result); expect(events).toHaveLength(3); expect(events.map((event) => event.eventType)).toEqual(["percussion", "strings", "kick"]); expect(events.map((event) => event.timeSeconds)).toEqual(result.beats); });
  it("interpreta in half-time una beat grid molto veloce", () => { const base: AudioAnalysisResult = { analyzerVersion: "test", durationSeconds: 2, sampleRate: 1_000, globalBpm: 180, bpmConfidence: .9, localTempo: [], beats: [0, .333, .666, .999, 1.332, 1.665], downbeats: [0], events: [], energy: [], onsetEnvelope: [], spectralFlux: [], lowEnergySegments: [] }; expect(buildPrimaryBeatEvents(base).map((event) => event.timeSeconds)).toEqual([0, .666, 1.332]); });
  it("trasforma le battute deboli in cadute e alcune battute normali in scorrimenti", () => { const base: AudioAnalysisResult = { analyzerVersion: "test", durationSeconds: 4, sampleRate: 1_000, globalBpm: 120, bpmConfidence: .9, localTempo: [], beats: [0, .5, 1, 1.5, 2, 2.5, 3, 3.5], downbeats: [0, 2], events: [], energy: [], onsetEnvelope: [], spectralFlux: [], lowEnergySegments: [{ startSeconds: .4, endSeconds: 1.6, averageRms: .01 }] }; const actions = buildPrimaryBeatEvents(base).map((event) => event.action); expect(actions).toContain("freeFall"); expect(actions).toContain("nearMiss"); expect(actions[0]).toBe("accentedCollision"); });
  it("mantiene una selezione multipla e la elimina con una sola operazione annullabile", () => { const store = useProjectStore.getState(); store.attachAudio({ path: "track.wav", fileName: "track.wav", hash: "c".repeat(64), durationSeconds: 10, sampleRate: 48_000, channels: 2, codec: "pcm", fileSize: 100 }, []); store.addEvent(1); useProjectStore.getState().addEvent(2); const ids = useProjectStore.getState().project.events.map((event) => event.id); useProjectStore.getState().selectEvent(ids[0] ?? null); useProjectStore.getState().selectEvent(ids[1] ?? null, true); expect(useProjectStore.getState().selectedEventIds).toEqual(ids); useProjectStore.getState().deleteEvents(ids); expect(useProjectStore.getState().project.events).toHaveLength(0); useProjectStore.getState().undoEvents(); expect(useProjectStore.getState().project.events).toHaveLength(2); });
  it("configura la base della modalità senza consentire una selezione vuota", () => { const store = useProjectStore.getState(); store.setBaseObjectEnabled("piano", true); expect(useProjectStore.getState().project.animation.baseObjectTypes).toContain("piano"); store.setAnimationMode("instrumentalFalling", ["strings"]); useProjectStore.getState().setBaseObjectEnabled("strings", false); expect(useProjectStore.getState().project.animation).toMatchObject({ modeId: "instrumentalFalling", baseObjectTypes: ["strings"] }); });
  it("configura numero, colori e volantini di New York Streets", () => { const store = useProjectStore.getState(); store.setAnimationMode("newYorkStreets", ["pebble"]); store.setNewYorkMarbleCount(13); store.setNewYorkGroupColor("#112233"); store.setNewYorkMarbleColor(2, "#abcdef"); store.addNewYorkFlyers(["data:image/png;base64,AAAA", "data:image/png;base64,BBBB"]); store.removeNewYorkFlyer(0); const settings = useProjectStore.getState().project.animation.newYorkStreets; expect(settings.secondaryMarbleCount).toBe(13); expect(settings.secondaryColors).toHaveLength(13); expect(settings.secondaryColors[0]).toBe("#112233"); expect(settings.secondaryColors[2]).toBe("#abcdef"); expect(settings.flyerImageUrls).toEqual(["data:image/png;base64,BBBB"]); });
  it("configura palette e movimento di Teddy Walk", () => { const store = useProjectStore.getState(); store.setAnimationMode("teddyWalk", ["platform"]); store.setTeddyWalkPalette(["#112233", "#445566", "#778899"]); store.updateTeddyWalk({ pulseIntensity: 1.2, danceEnabled: true }); expect(useProjectStore.getState().project.animation.teddyWalk).toMatchObject({ furColor: "#112233", patchColor: "#445566", roadColor: "#778899", pulseIntensity: 1.2, danceEnabled: true }); });
  it("configura poster, palette e labiale di Teddy Sing", () => { const store = useProjectStore.getState(); store.setAnimationMode("teddySing", ["platform"]); store.setTeddySingPalette(["#223344", "#556677", "#8899aa", "#101820"]); store.updateTeddySing({ posterImageUrl: "data:image/png;base64,AAAA", lipSyncIntensity: 1.35, vocalSensitivity: 1.2 }); expect(useProjectStore.getState().project.animation.teddySing).toMatchObject({ posterImageUrl: "data:image/png;base64,AAAA", furColor: "#223344", patchColor: "#556677", ledColor: "#8899aa", roomColor: "#101820", lipSyncIntensity: 1.35, vocalSensitivity: 1.2 }); });
  it("propaga la palette Cover Sphere ai sottotitoli finché il collegamento automatico è attivo", () => { const store = useProjectStore.getState(); store.setCoverSpherePalette(["#ef3f91", "#6747dd"]); expect(useProjectStore.getState().project.subtitles).toMatchObject({ color: "#ef3f91", glowColor: "#6747dd" }); useProjectStore.getState().updateSubtitles({ autoPalette: false, color: "#ffffff", glowColor: "#aaaaaa" }); useProjectStore.getState().setCoverSpherePalette(["#111111", "#222222"]); expect(useProjectStore.getState().project.subtitles).toMatchObject({ color: "#ffffff", glowColor: "#aaaaaa" }); });
  it("mantiene e riapplica esplicitamente la palette automatica delle 48 bande", () => { const store = useProjectStore.getState(); store.setCoverSpherePalette(["#aa3366", "#22bbdd"]); expect(useProjectStore.getState().project.animation.coverSphere).toMatchObject({ autoPalette: true, palettePrimary: "#aa3366", paletteSecondary: "#22bbdd", spectrumColor: "#aa3366", effectColor: "#22bbdd" }); useProjectStore.getState().setCoverSphereAutoPalette(false); useProjectStore.getState().updateCoverSphere({ spectrumColor: "#ffffff" }); useProjectStore.getState().setCoverSpherePalette(["#101820", "#ffd166"]); expect(useProjectStore.getState().project.animation.coverSphere).toMatchObject({ autoPalette: false, spectrumColor: "#ffffff", palettePrimary: "#101820" }); useProjectStore.getState().setCoverSphereAutoPalette(true); expect(useProjectStore.getState().project.animation.coverSphere).toMatchObject({ spectrumColor: "#101820", effectColor: "#ffd166" }); });
  it("configura Stereo Unfold e conserva la palette manuale", () => { const store = useProjectStore.getState(); store.setAnimationMode("stereoUnfold", ["platform"]); store.setStereoUnfoldPalette(["#ef476f", "#06d6a0"]); store.updateStereoUnfold({ coverImageUrl: "data:image/png;base64,AAAA", spectrumStyle: "aurora", stereoDepth: 1.8 }); expect(useProjectStore.getState().project.animation.stereoUnfold).toMatchObject({ primaryColor: "#ef476f", secondaryColor: "#06d6a0", coverImageUrl: "data:image/png;base64,AAAA", spectrumStyle: "aurora", stereoDepth: 1.8 }); useProjectStore.getState().setStereoUnfoldAutoPalette(false); useProjectStore.getState().updateStereoUnfold({ primaryColor: "#ffffff" }); useProjectStore.getState().setStereoUnfoldPalette(["#111111", "#222222"]); expect(useProjectStore.getState().project.animation.stereoUnfold).toMatchObject({ autoPalette: false, primaryColor: "#ffffff", palettePrimary: "#111111" }); });
  it("applica la cover Pixel Art a pantaloni, neon e sottotitoli mantenendo la felpa nera", () => { const store = useProjectStore.getState(); store.setAnimationMode("pixelArt", ["platform"]); store.setPixelArtPalette(["#ef476f", "#4252c8", "#06d6a0", "#ffd166"]); store.updatePixelArt({ venueName: "MIDNIGHT BAR", coverImageUrl: "data:image/png;base64,AAAA", hoodieColor: "#ff00ff" }); expect(useProjectStore.getState().project.animation.pixelArt).toMatchObject({ venueName: "MIDNIGHT BAR", hoodieColor: "#08090e", pantsColor: "#4252c8", neonPrimary: "#06d6a0", neonSecondary: "#ffd166" }); expect(useProjectStore.getState().project.subtitles).toMatchObject({ color: "#06d6a0", glowColor: "#ffd166" }); });
  it("inserisce manualmente un blocco sottotitolo al playhead", () => { const store = useProjectStore.getState(); store.attachAudio({ path: "track.wav", fileName: "track.wav", hash: "e".repeat(64), durationSeconds: 10, sampleRate: 48_000, channels: 2, codec: "pcm", fileSize: 100 }, []); const id = useProjectStore.getState().addSubtitleCue(4.25); expect(useProjectStore.getState().project.subtitles).toMatchObject({ enabled: true, cues: [{ id, startSeconds: 4.25, endSeconds: 6.25, text: "Nuovo sottotitolo", manual: true }] }); });
  it("salva, divide ed elimina i fonemi di Teddy Sing", () => {
    const store = useProjectStore.getState();
    store.setTeddySingPhonemes([{ id: "phoneme-a", startSeconds: .2, endSeconds: .9, viseme: "A", confidence: .84, manual: false }]);
    useProjectStore.getState().splitTeddySingPhoneme("phoneme-a", .55);
    let cues = useProjectStore.getState().project.animation.teddySing.phonemeCues;
    expect(cues).toHaveLength(2);
    expect(cues[0]).toMatchObject({ id: "phoneme-a", startSeconds: .2, endSeconds: .55, manual: true });
    expect(cues[1]).toMatchObject({ startSeconds: .55, endSeconds: .9, manual: true });
    useProjectStore.getState().deleteTeddySingPhoneme(cues[1]?.id ?? "");
    cues = useProjectStore.getState().project.animation.teddySing.phonemeCues;
    expect(cues).toHaveLength(1);
    expect(useProjectStore.getState().project.animation.teddySing.phonemesGenerated).toBe(true);
  });
});
