import { DiscordLink } from "../components/DiscordLink";
import { useCallback, useEffect, useRef, useState } from "react";
import { invoke, isTauri } from "@tauri-apps/api/core";
import { useUiPreferences } from "../services/ui-preferences";
import { SettingsButton } from "../components/StudioSettings";
import { OPEN_LONELY_BOT_EVENT } from "../components/ApplicationAssistant";
import { AnalyzerCanvas } from "./AnalyzerCanvas";
import { AnalyzerGrid } from "./AnalyzerGrid";
import { defaultLayout, readLayout, saveLayout, type WidgetId } from "./streamer-layout";
import { VinylTurntable } from "./VinylTurntable";
import { TrackArtwork } from "./TrackArtwork";
import { WaterSurface } from "./WaterSurface";
import { LiveTranscriptPanel } from "./LiveTranscriptPanel";
import { useLiveTranscript } from "./use-live-transcript";
import { useStreamerRecording } from "./use-streamer-recording";
import { recordingErrorMessage } from "./streamer-recording";
import { ProviderPlayer, type PlayerHandle, type PlaybackState } from "./ProviderPlayer";
import { loadProviderMetadata } from "./streamer-providers";
import { StreamerAudioRuntime, captureCapabilities, type CaptureCapabilities, type CaptureSource } from "./streamer-audio";
import type { CaptureInfo } from "./streamer-capture";
import { browserTrack, nativeTracks } from "./streamer-files";
import { defaultAnalysisSettings, type AnalysisSettings } from "./analysis-engine";
import { clearQueue, createTrackId, favoriteQueue, loadQueue, moveTrack, nextTrackId, parseProviderUrl, removeFavorite, removeTrack, restoreFavorite, saveQueue, type QueueState, type Track } from "./streamer-store";
import "./streamer.css";

const clock = (seconds: number) => Number.isFinite(seconds) ? `${Math.floor(seconds / 60)}:${Math.floor(seconds % 60).toString().padStart(2, "0")}` : "0:00";
const empty: QueueState = { tracks: [], currentId: null, autoAdvance: false, favorites: [] };
const settingsKey = "mlsm.streamer.analysis.v1";
const waterKey = "mlsm.streamer.water.v1";
function readSettings(): AnalysisSettings { try { const raw = JSON.parse(localStorage.getItem(settingsKey) ?? "{}"); return { fftSize: [2048, 4096, 8192].includes(raw.fftSize) ? raw.fftSize : 4096, smoothing: typeof raw.smoothing === "number" ? Math.max(0, Math.min(.95, raw.smoothing)) : .72, peakHold: typeof raw.peakHold === "number" ? Math.max(0, Math.min(10, raw.peakHold)) : 2 }; } catch { return defaultAnalysisSettings; } }

export function StreamerAudioViewer({ onHome }: { onHome: () => void }) {
  const { language, theme } = useUiPreferences(); const t = (it: string, en: string) => language === "it" ? it : en;
  const [runtime, setRuntime] = useState<StreamerAudioRuntime | null>(null), [queue, setQueue] = useState<QueueState>(empty), [loaded, setLoaded] = useState(false);
  const queueRef = useRef(queue); queueRef.current = queue;
  const [playback, setPlayback] = useState<PlaybackState>("IDLE"), [position, setPosition] = useState(0), [duration, setDuration] = useState(0), [volume, setVolume] = useState(.8);
  const [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [url, setUrl] = useState(""), [favoriteName, setFavoriteName] = useState("");
  const [layout, setLayout] = useState(readLayout), [widgetDrawerOpen, setWidgetDrawerOpen] = useState(false), [settings, setSettings] = useState(readSettings), [resetOnTrack, setResetOnTrack] = useState(true), [freeze, setFreeze] = useState(false), [spectrogramSpeed, setSpectrogramSpeed] = useState(2);
  const [capabilities, setCapabilities] = useState<CaptureCapabilities | null>(null), [source, setSource] = useState("local"), [captureState, setCaptureState] = useState("stopped"), [inputs, setInputs] = useState<MediaDeviceInfo[]>([]);
  const [captureInfo, setCaptureInfo] = useState<CaptureInfo | null>(null);
  const [showSetup, setShowSetup] = useState(() => localStorage.getItem("mlsm.streamer.setup.v1") !== "done"), [signal, setSignal] = useState(false), [elapsed, setElapsed] = useState(0);
  const [analyzersFullscreen, setAnalyzersFullscreen] = useState(false);
  const [water, setWater] = useState(() => { try { return localStorage.getItem(waterKey) !== "off"; } catch { return true; } });
  const player = useRef<PlayerHandle>(null), fileInput = useRef<HTMLInputElement>(null), setup = useRef<HTMLDialogElement>(null), persistence = useRef(Promise.resolve<unknown>(undefined)), playIntent = useRef<string | null>(null), selectionGeneration = useRef(0), mounted = useRef(true), queueLoaded = useRef(false);
  const selected = queue.tracks.find(track => track.id === queue.currentId) ?? null;
  const recording = useStreamerRecording();
  const { start: startRecording, pause: pauseRecording } = recording;
  const recordingPending = recording.info.phase === "arming" || recording.info.phase === "saving";
  const recordingEnabled = ["armed", "recording", "paused"].includes(recording.info.phase);
  const [liveText, setLiveText] = useState(true), [speechLanguage, setSpeechLanguage] = useState("auto");
  const transcript = useLiveTranscript(runtime, `${selected?.id ?? "idle"}:${source}`, source === "local" ? playback === "PLAYING" : captureState === "active", liveText && layout.some(panel => panel.id === "vinyl" && panel.visible), speechLanguage);
  const titles: Record<WidgetId, string> = { spectrum: t("Spettro stereo", "Stereo spectrum"), peaks: "Peak / True peak", loudness: "Loudness · LUFS", stereo: t("Immagine stereo", "Stereo image"), phase: t("Correlazione di fase", "Phase correlation"), spectrogram: t("Spettrogramma", "Spectrogram"), waveform: t("Oscilloscopio stereo", "Stereo oscilloscope"), dynamics: t("Dinamica", "Dynamics"), tonal: t("Distribuzione tonale", "Tonal distribution"), track: t("Informazioni brano", "Track information"), vinyl: "MLSM · Turntable" };

  const refreshCapabilities = useCallback(() => { void captureCapabilities().then(setCapabilities).catch(e => setError(String(e))); }, []);
  useEffect(() => {
    let active = true;
    mounted.current = true; const instance = new StreamerAudioRuntime(); setRuntime(instance);
    instance.onCaptureStatus = (state, message) => { if (!active) return; setCaptureState(state); if (message) setError(message); };
    instance.onCaptureInfo = info => { if (active) setCaptureInfo(info); };
    void loadQueue().then(value => { if (active) { queueLoaded.current = true; setQueue(value); setLoaded(true); } }).catch(e => { if (active) { setError(String(e)); setLoaded(true); } });
    refreshCapabilities();
    return () => { active = false; mounted.current = false; void instance.dispose(); };
  }, [refreshCapabilities]);
  useEffect(() => { if (!loaded || !queueLoaded.current) return; const timeout = window.setTimeout(() => { persistence.current = persistence.current.catch(() => undefined).then(() => saveQueue(queue)).catch(e => { if (mounted.current) setError(String(e)); }); }, 180); return () => window.clearTimeout(timeout); }, [queue, loaded]);
  useEffect(() => () => { if (!queueLoaded.current) return; const value = queueRef.current; persistence.current = persistence.current.catch(() => undefined).then(() => saveQueue(value)); }, []);
  useEffect(() => { runtime?.configure(settings); localStorage.setItem(settingsKey, JSON.stringify(settings)); }, [settings, runtime]);
  useEffect(() => { try { localStorage.setItem(waterKey, water ? "on" : "off"); } catch { /* Optional local preference; audio remains usable. */ } }, [water]);
  useEffect(() => { try { saveLayout(layout); } catch { setError(language === "it" ? "Impossibile salvare il layout locale." : "Could not save the local layout."); } }, [layout, language]);
  useEffect(() => { if (showSetup) setup.current?.showModal(); else setup.current?.close(); }, [showSetup]);
  useEffect(() => {
    if (!analyzersFullscreen) return;
    const close = (event: KeyboardEvent) => { if (event.key === "Escape") setAnalyzersFullscreen(false); };
    window.addEventListener("keydown", close);
    return () => window.removeEventListener("keydown", close);
  }, [analyzersFullscreen]);
  useEffect(() => { const update = () => { refreshCapabilities(); void navigator.mediaDevices?.enumerateDevices().then(devices => setInputs(devices.filter(d => d.kind === "audioinput"))).catch(() => undefined); }; navigator.mediaDevices?.addEventListener("devicechange", update); return () => navigator.mediaDevices?.removeEventListener("devicechange", update); }, [refreshCapabilities]);
  useEffect(() => { if (!runtime) return; const timer = window.setInterval(() => { const frame = runtime.frame; setSignal(!!frame && performance.now() - runtime.receivedAt < 500 && Math.max(...frame.peak) > -90); setElapsed(frame?.elapsed ?? 0); }, 300); return () => window.clearInterval(timer); }, [runtime]);

  const selectTrack = (id: string, play = false) => { playIntent.current = play ? id : null; setPlayback("LOADING"); setQueue(value => ({ ...value, currentId: id })); };
  const endedRef = useRef<() => void>(() => undefined);
  endedRef.current = () => { setPlayback("ENDED"); const next = nextTrackId(queueRef.current, true); if (next) selectTrack(next, true); else void recording.stop(); };
  useEffect(() => {
    if (playback === "PLAYING" && runtime) startRecording(runtime);
    else pauseRecording();
  }, [playback, runtime, startRecording, pauseRecording]);
  useEffect(() => {
    if (!runtime) return; const audio = runtime.audio;
    const onTime = () => setPosition(audio.currentTime), onMeta = () => { setDuration(Number.isFinite(audio.duration) ? audio.duration : 0); setPlayback("READY"); }, onPlay = () => setPlayback("PLAYING"), onPause = () => { if (!audio.ended) setPlayback("PAUSED"); }, onWaiting = () => setPlayback("BUFFERING"), onEnded = () => endedRef.current(), onError = () => { setPlayback("ERROR"); setError(language === "it" ? "Decodifica audio non riuscita. Verifica il file; nell’app desktop l’importazione usa FFmpeg per i formati aggiuntivi." : "Audio decoding failed. Check the file; desktop import uses FFmpeg for additional formats."); };
    const listeners = { timeupdate: onTime, loadedmetadata: onMeta, playing: onPlay, pause: onPause, waiting: onWaiting, ended: onEnded, error: onError };
    for (const [name, fn] of Object.entries(listeners)) audio.addEventListener(name, fn);
    return () => { for (const [name, fn] of Object.entries(listeners)) audio.removeEventListener(name, fn); };
  }, [runtime, language]);
  useEffect(() => {
    if (!runtime || !loaded) return; const track = queueRef.current.tracks.find(value => value.id === queue.currentId), generation = ++selectionGeneration.current; runtime.pause(); setPosition(0); setDuration(track?.duration ?? 0); setError(""); setFreeze(false); if (resetOnTrack) runtime.reset();
    if (!track) { setPlayback("IDLE"); runtime.stopLocal(); return; }
    setPlayback("LOADING");
    if (track.provider === "local") { setSource("local"); void runtime.loadLocal(track).then(async () => { if (generation !== selectionGeneration.current || !mounted.current) return; if (playIntent.current === track.id) { playIntent.current = null; await runtime.playLocal(); } }).catch(e => { if (generation === selectionGeneration.current) { setError(String(e)); setPlayback("ERROR"); } }); }
    else runtime.stopLocal();
    return () => { if (selectionGeneration.current === generation) selectionGeneration.current = generation + 1; };
  }, [queue.currentId, runtime, loaded]); // eslint-disable-line react-hooks/exhaustive-deps

  const importFiles = async (files?: FileList | File[], paths?: string[]) => { setBusy(true); setError(""); try { const tracks = paths || (!files && isTauri()) ? await nativeTracks(paths) : await Promise.all(Array.from(files ?? []).map(browserTrack)); if (mounted.current) setQueue(value => ({ ...value, tracks: [...value.tracks, ...tracks], currentId: value.currentId ?? tracks[0]?.id ?? null })); } catch (e) { setError(String(e)); } finally { if (mounted.current) setBusy(false); } };
  useEffect(() => { if (!isTauri()) return; let active = true; let off: (() => void) | undefined; void import("@tauri-apps/api/webviewWindow").then(async ({ getCurrentWebviewWindow }) => { const unlisten = await getCurrentWebviewWindow().onDragDropEvent(event => { if (event.payload.type === "drop" && active) void importFiles(undefined, event.payload.paths); }); if (active) off = unlisten; else unlisten(); }).catch(e => setError(String(e))); return () => { active = false; off?.(); }; }, []);
  const addLink = async (input = url) => { const parsed = parseProviderUrl(input); if (!parsed) { setError(t("Inserisci un link Spotify o YouTube valido.", "Enter a valid Spotify or YouTube link.")); return; } setBusy(true); setError(""); const track: Track = { id: createTrackId(), provider: parsed.provider, title: parsed.provider === "spotify" ? "Spotify" : "YouTube", url: parsed.canonicalUrl }; if (parsed.provider === "youtube") track.artwork = `https://i.ytimg.com/vi/${parsed.id}/hqdefault.jpg`; try { Object.assign(track, await loadProviderMetadata(parsed.provider, parsed.canonicalUrl)); } catch (e) { setNotice(String(e)); } if (!mounted.current) return; setQueue(value => ({ ...value, tracks: [...value.tracks, track], currentId: value.currentId ?? track.id })); setUrl(""); setBusy(false); };
  const play = async () => { if (!selected || !runtime || recordingPending) return; setError(""); try { recording.start(runtime); if (selected.provider === "local") { if (source !== "local") { await runtime.stopCapture(); setSource("local"); } await runtime.playLocal(); } else player.current?.play(); } catch (e) { recording.pause(); setError(String(e)); setPlayback("ERROR"); } };
  const pause = () => { recording.pause(); if (selected?.provider === "local") runtime?.pause(); else player.current?.pause(); };
  const stop = () => { void recording.stop(); runtime?.stopLocal(); player.current?.stop(); setPlayback(selected ? "READY" : "IDLE"); setPosition(0); };
  const toggleRecording = () => {
    if (recordingEnabled) { void recording.stop(); return; }
    if (selected?.provider !== "local" && captureState !== "active") { setError(t("Prima di registrare, abilita l’analisi audio di sistema e condividi l’audio della sorgente. Poi scegli la scheda o finestra di MLSM Studio per il video.", "Before recording, enable system audio analysis and share the source audio. Then choose the MLSM Studio tab or window for video.")); return; }
    pause(); void recording.arm();
  };
  const advance = (offset: number) => { const index = queue.tracks.findIndex(track => track.id === queue.currentId), next = queue.tracks[index + offset]; if (next) selectTrack(next.id, playback === "PLAYING"); };
  const dismissSetup = () => { setShowSetup(false); localStorage.setItem("mlsm.streamer.setup.v1", "done"); };
  const startCapture = async (chosen = source) => { if (!runtime || chosen === "local") return; setError(""); const [kind, ...id] = chosen.split(":"); const capture = { kind, ...(id.length ? { id: id.join(":") } : {}) } as CaptureSource | { kind: "input"; id?: string }; try { await runtime.startCapture(capture); dismissSetup(); if (kind === "input") { const devices = await navigator.mediaDevices.enumerateDevices(); setInputs(devices.filter(d => d.kind === "audioinput")); } } catch (e) { setError(String(e)); } };
  const setCaptureSource = async (value: string) => { await recording.stop(); await runtime?.stopCapture(); setSource(value); if (value === "local" && selected?.provider === "local") setPlayback("PAUSED"); };
  const clear = () => { stop(); setQueue(value => clearQueue(value)); };
  const remove = (id: string) => { if (id === queue.currentId) stop(); playIntent.current = null; setQueue(value => removeTrack(value, id)); };
  const onProviderState = (state: PlaybackState) => { if (state === "ENDED") endedRef.current(); else { setPlayback(state); if (state === "READY" && selected && playIntent.current === selected.id) { playIntent.current = null; player.current?.play(); } } };
  const onProviderMetadata = (metadata: Partial<Track>) => { const id = queueRef.current.currentId; setQueue(value => ({ ...value, tracks: value.tracks.map(track => track.id === id ? { ...track, ...metadata } : track) })); };
  const renderPanel = (id: WidgetId) => {
    if (!runtime) return null;
    if (id === "vinyl") return <div className="sav-listening-stage"><VinylTurntable trackId={selected?.id ?? "idle"} title={selected?.title ?? "MLSM Studio"} artwork={selected?.artwork} state={playback} cropArtwork={selected?.provider === "youtube"} /><LiveTranscriptPanel state={transcript} enabled={liveText} onToggle={() => setLiveText(value => !value)} language={language} speechLanguage={speechLanguage} onLanguage={setSpeechLanguage} /></div>;
    if (id === "track") return <div className="sav-track-info">{selected?.artwork && <TrackArtwork src={selected.artwork} alt="" youtube={selected.provider === "youtube"} />}<strong>{selected?.title ?? t("Nessun brano selezionato", "No track selected")}</strong><p>{[selected?.artist, selected?.album].filter(Boolean).join(" · ")}</p><dl>{[[t("Sorgente", "Source"), selected?.provider], [t("Durata", "Duration"), duration ? clock(duration) : "—"], ["Format / codec", [selected?.format, selected?.codec].filter(Boolean).join(" · ")], ["Sample rate", selected?.sampleRate ? `${selected.sampleRate / 1000} kHz` : null], ["Bit depth", selected?.bitDepth], [t("Canali", "Channels"), selected?.channels], ["Bitrate", selected?.bitrate ? `${Math.round(selected.bitrate / 1000)} kbps` : null]].map(([name, value]) => <div key={name}><dt>{name}</dt><dd>{value || "—"}</dd></div>)}</dl></div>;
    return <AnalyzerCanvas kind={id} runtime={runtime} language={language} theme={theme} freeze={id === "spectrum" && freeze} speed={spectrogramSpeed} water={water} />;
  };
  const waterToggle = <button className="sav-water-toggle" aria-pressed={water} title={t("Onde condivise: aperture stereo e variazioni forti dei picchi. Rispetta la preferenza di movimento ridotto.", "Shared ripples: stereo openings and strong peak changes. Respects reduced-motion preferences.")} onClick={() => setWater(value => !value)}><span aria-hidden="true">◎</span> {t("Onde reattive", "Reactive ripples")}</button>;
  const captureActive = captureState === "active", sourceLabel = source === "local" ? t("Lettore locale", "Local player") : source === "system" ? t("Audio di sistema", "System audio") : source.startsWith("input") ? t("Ingresso audio", "Audio input") : [...(capabilities?.applications ?? []), ...(capabilities?.outputDevices ?? [])].find(item => source.endsWith(`:${item.id}`))?.name ?? source;

  return <main className={`sav-workspace${analyzersFullscreen ? " sav-analyzers-fullscreen" : ""}`} data-ui-copy onDragOver={event => { if (event.dataTransfer.types.includes("Files") || event.dataTransfer.types.includes("text/uri-list")) event.preventDefault(); }} onDrop={event => { if (event.dataTransfer.files.length) { event.preventDefault(); void importFiles(event.dataTransfer.files); } else { const link = event.dataTransfer.getData("text/uri-list"); if (link) { event.preventDefault(); void addLink(link.split("\n").find(line => !line.startsWith("#")) ?? ""); } } }}>
    {analyzersFullscreen
      ? <header className="sav-fullscreen-topbar" aria-label={t("Analizzatori a schermo intero", "Fullscreen analyzers")}><div><small>MLSM · STREAMER AUDIO VIEWER</small><h1>{t("Analizzatori in tempo reale", "Live analyzers")}</h1></div>{waterToggle}<button className="sav-primary" onClick={() => setAnalyzersFullscreen(false)}>← {t("Torna alla visualizzazione classica", "Return to standard view")}</button></header>
      : <header className="sav-topbar"><button disabled={recordingPending} onClick={() => void recording.stop().then(onHome)}>← MLSM Studio</button><div><small>LISTEN · MEASURE · EXPLORE</small><h1>Streamer Audio Viewer</h1></div><button onClick={() => window.dispatchEvent(new Event(OPEN_LONELY_BOT_EVENT))}>LB · Lonely Bot</button><DiscordLink /><SettingsButton /><button onClick={() => { setWidgetDrawerOpen(false); setAnalyzersFullscreen(true); }}>{t("Widget a schermo intero", "Fullscreen widgets")} ⛶</button><button onClick={() => setShowSetup(true)}>{t("Sorgenti e privacy", "Sources & privacy")}</button></header>}
    <div className="sav-shell"><aside className="sav-sidebar"><section><h2>{t("Sorgenti audio", "Audio sources")}</h2><p className="sav-hint">{t("File locali, Spotify e YouTube in una sola coda.", "Local files, Spotify and YouTube in one queue.")}</p><input ref={fileInput} type="file" multiple accept="audio/*,.aiff,.aif,.flac,.ogg,.opus,.m4a,.aac" hidden onChange={event => { if (event.target.files) void importFiles(event.target.files); event.target.value = ""; }} /><button className="sav-primary sav-wide" disabled={busy} onClick={() => isTauri() ? void importFiles() : fileInput.current?.click()}>{busy ? t("Importazione…", "Importing…") : t("＋ Aggiungi file audio", "＋ Add audio files")}</button><form className="sav-link-form" onSubmit={event => { event.preventDefault(); void addLink(); }}><input aria-label="Spotify / YouTube URL" placeholder="Spotify / YouTube URL" value={url} onChange={event => setUrl(event.target.value)} /><button disabled={busy || !url.trim()} aria-label={t("Aggiungi link", "Add link")}>＋</button></form></section>
    <section className="sav-capture"><div className="sav-section-heading"><h2>{t("Sorgente di analisi", "Analysis source")}</h2><button onClick={refreshCapabilities} title={t("Aggiorna sorgenti", "Refresh sources")}>↻</button></div><select aria-label={t("Sorgente di analisi", "Analysis source")} value={source} onChange={event => void setCaptureSource(event.target.value)}><option value="local">{t("Lettore locale · PCM diretto", "Local player · direct PCM")}</option>{capabilities?.systemAudio && <option value="system">{t("Audio di sistema", "System audio")}</option>}{capabilities?.applicationCapture && <optgroup label={t("Applicazione", "Application")}>{capabilities.applications.map(item => <option key={item.id} value={`application:${item.id}`}>{item.name}</option>)}</optgroup>}{!!capabilities?.outputDevices.length && <optgroup label={t("Uscita audio", "Output device")}>{capabilities.outputDevices.map(item => <option key={item.id} value={`outputDevice:${item.id}`}>{item.name}</option>)}</optgroup>}{typeof navigator.mediaDevices?.getUserMedia === "function" && <optgroup label={t("Ingresso · autorizzazione richiesta", "Input · permission required")}><option value="input">{t("Ingresso predefinito", "Default input")}</option>{inputs.filter(item => item.deviceId !== "default").map((item, i) => <option key={item.deviceId} value={`input:${item.deviceId}`}>{item.label || `Input ${i + 1}`}</option>)}</optgroup>}</select>
      {source !== "local" && <button className={captureActive ? "sav-danger sav-wide" : "sav-primary sav-wide"} disabled={captureState === "starting"} onClick={() => captureActive ? void runtime?.stopCapture() : void startCapture()}>{captureActive ? t("■ Ferma cattura", "■ Stop capture") : captureState === "starting" ? t("Autorizzazione e avvio…", "Requesting access…") : t("Abilita analisi audio", "Enable audio analysis")}</button>}
      {captureInfo && <div className="sav-hint" role="status">
        <strong>{t("Canali ricevuti", "Received channels")}: {captureInfo.receivedChannels ?? "…"}</strong>
        {captureInfo.sampleRate ? ` · ${captureInfo.sampleRate / 1000} kHz` : ""}
        {signal && captureInfo.receivedChannels === 2 && <span> · {runtime?.frame && runtime.frame.width < .00001 && runtime.frame.correlation > .99999 ? t("L/R identici nel segnale", "Identical L/R in the signal") : t("L/R distinti", "Distinct L/R")}</span>}
        {captureInfo.receivedChannels === 1 && <p>{t("Chrome sta consegnando un solo canale. Ferma e riattiva la cattura scegliendo la scheda che riproduce il brano e abilitando la condivisione audio. I widget mostrano il segnale ricevuto.", "Chrome is delivering one channel. Stop and restart capture, choose the tab playing the track and enable audio sharing. The widgets show the received signal.")}</p>}
        {(captureInfo.echoCancellation || captureInfo.noiseSuppression || captureInfo.autoGainControl || captureInfo.constraintError) && <p>{t("Il browser non ha applicato tutte le impostazioni audio richieste. I dettagli sono nel log [Streamer capture].", "The browser did not apply all requested audio settings. Details are in the [Streamer capture] log.")}</p>}
      </div>}
      {capabilities?.reason && <p className="sav-hint">{capabilities.reason}</p>}{capabilities?.permission === "denied" && isTauri() && <button onClick={() => void invoke("streamer_permission_settings").catch(e => setError(String(e)))}>{t("Apri impostazioni privacy", "Open privacy settings")}</button>}
      {selected && selected.provider !== "local" && !captureActive && <p className="sav-hint">{t("Abilita l’audio di sistema per analizzare questo stream. Il player può funzionare anche senza analisi.", "Enable system audio to analyze this stream. Playback also works without analysis.")}</p>}
    </section>
    <section className="sav-queue-section"><div className="sav-section-heading"><h2>{t("Coda", "Queue")} <span>{queue.tracks.length}</span></h2><button disabled={!queue.tracks.length} onClick={clear}>{t("Svuota", "Clear")}</button></div><label className="sav-check"><input type="checkbox" checked={queue.autoAdvance} onChange={event => setQueue(value => ({ ...value, autoAdvance: event.target.checked }))} />{t("Avanza automaticamente", "Advance automatically")}</label><small className="sav-hint">{queue.autoAdvance ? t("Il brano successivo partirà alla fine del precedente.", "The next track starts when the current one ends.") : t("La riproduzione si ferma alla fine di ogni brano.", "Playback stops at the end of each track.")}</small>
      <ol className="sav-queue">{queue.tracks.map((track, index) => <li key={track.id} className={selected?.id === track.id ? "selected" : ""} draggable onDragStart={event => event.dataTransfer.setData("application/x-mlsm-track", track.id)} onDragOver={event => event.preventDefault()} onDrop={event => { const id = event.dataTransfer.getData("application/x-mlsm-track"); if (id) { event.preventDefault(); event.stopPropagation(); setQueue(value => moveTrack(value, id, index)); } }}><button className="sav-queue-select" onClick={() => selectTrack(track.id)} onDoubleClick={() => { if (selected?.id === track.id) void play(); else selectTrack(track.id, true); }}><span className="sav-artwork">{track.artwork ? <TrackArtwork src={track.artwork} alt="" youtube={track.provider === "youtube"} /> : <span>♫</span>}</span><span><strong>{track.title}</strong><small>{track.artist || track.provider} {track.duration ? `· ${clock(track.duration)}` : ""}</small></span></button><div className="sav-track-actions"><button disabled={!index} title={t("Sposta su", "Move up")} aria-label={`${t("Sposta su", "Move up")} ${track.title}`} onClick={() => setQueue(value => moveTrack(value, track.id, index - 1))}>↑</button><button disabled={index === queue.tracks.length - 1} title={t("Sposta giù", "Move down")} aria-label={`${t("Sposta giù", "Move down")} ${track.title}`} onClick={() => setQueue(value => moveTrack(value, track.id, index + 1))}>↓</button><button title={t("Rimuovi dalla coda", "Remove from queue")} aria-label={`${t("Rimuovi", "Remove")} ${track.title}`} onClick={() => remove(track.id)}>×</button></div></li>)}</ol>{!queue.tracks.length && <p className="sav-empty">{t("Trascina qui file audio o aggiungi un link.", "Drop audio files here or add a link.")}</p>}
    </section>
    <details className="sav-favorites"><summary>☆ {t("Code preferite", "Favorite queues")} · {queue.favorites.length}</summary><form onSubmit={event => { event.preventDefault(); setQueue(value => favoriteQueue(value, favoriteName)); setFavoriteName(""); setNotice(t("Coda salvata nei preferiti.", "Queue saved to favorites.")); }}><input aria-label={t("Nome coda preferita", "Favorite queue name")} value={favoriteName} onChange={event => setFavoriteName(event.target.value)} placeholder={t("Nome della coda", "Queue name")} /><button disabled={!queue.tracks.length || !favoriteName.trim()}>{t("Salva coda", "Save queue")}</button></form>{queue.favorites.map(favorite => <div className="sav-favorite" key={favorite.id}><button onClick={() => { stop(); playIntent.current = null; setQueue(value => restoreFavorite(value, favorite.id)); }}>{favorite.name}<small>{favorite.tracks.length} {t("brani", "tracks")}</small></button><button aria-label={`${t("Elimina preferito", "Delete favorite")} ${favorite.name}`} onClick={() => setQueue(value => removeFavorite(value, favorite.id))}>×</button></div>)}</details>
    {selected && selected.provider !== "local" && selected.url && <div className="sav-provider"><ProviderPlayer key={selected.id} ref={player} track={{ id: selected.id, provider: selected.provider, url: selected.url }} autoAdvance={queue.autoAdvance} onState={onProviderState} onProgress={(p, d) => { setPosition(p); setDuration(d); }} onMetadata={onProviderMetadata} onError={setError} /></div>}
    </aside><div className="sav-main"><div className="sav-analysis-toolbar"><div className={`sav-source-status ${captureActive ? "capturing" : ""}`}><i /><span>{captureActive ? sourceLabel : selected?.provider === "local" ? t("Analisi file locale", "Local file analysis") : t("Cattura disattivata", "Capture disabled")}</span><small>{signal ? t("Segnale presente", "Signal present") : t("Silenzio / attesa segnale", "Silence / waiting for signal")} · {clock(elapsed)}</small></div>{waterToggle}<button onClick={() => { runtime?.reset(); setFreeze(false); }}>{t("Azzera misure", "Reset measurement")}</button><button aria-pressed={freeze} onClick={() => setFreeze(value => !value)}>{freeze ? t("Riprendi spettro", "Resume spectrum") : t("Congela spettro", "Freeze spectrum")}</button><button className="sav-widget-drawer-toggle" aria-expanded={widgetDrawerOpen} aria-controls="streamer-widget-drawer" onClick={() => setWidgetDrawerOpen(value => !value)}>{t("Widget", "Widgets")} · {layout.filter(panel => !panel.visible).length}</button></div>
    <div className="sav-settings"><label>FFT<select value={settings.fftSize} onChange={event => setSettings(value => ({ ...value, fftSize: Number(event.target.value) as AnalysisSettings["fftSize"] }))}>{[2048, 4096, 8192].map(size => <option key={size}>{size}</option>)}</select></label><label>{t("Fluidità", "Smoothing")}<select value={settings.smoothing} onChange={event => setSettings(value => ({ ...value, smoothing: Number(event.target.value) }))}><option value={.3}>{t("Rapida", "Fast")}</option><option value={.72}>{t("Bilanciata", "Balanced")}</option><option value={.9}>{t("Fluida", "Smooth")}</option></select></label><label>Peak hold<select value={settings.peakHold} onChange={event => setSettings(value => ({ ...value, peakHold: Number(event.target.value) }))}>{[0, 1, 2, 5].map(s => <option key={s} value={s}>{s} s</option>)}</select></label><label>{t("Spettrogramma", "Spectrogram")}<select value={spectrogramSpeed} onChange={event => setSpectrogramSpeed(Number(event.target.value))}><option value={1}>1×</option><option value={2}>2×</option><option value={4}>4×</option></select></label><label className="sav-check"><input type="checkbox" checked={resetOnTrack} onChange={event => setResetOnTrack(event.target.checked)} />{t("Azzera al cambio brano", "Reset on track change")}</label><span className="sav-channel-key"><b>L</b> {t("rosa", "pink")} · <b>R</b> {theme === "night" ? t("bianco", "white") : t("nero", "black")}</span></div>
    {error && <div className="sav-message error" role="alert"><span>{error}</span><button aria-label={t("Chiudi", "Close")} onClick={() => setError("")}>×</button></div>}{notice && <div className="sav-message" role="status"><span>{notice}</span><button aria-label={t("Chiudi", "Close")} onClick={() => setNotice("")}>×</button></div>}
    {widgetDrawerOpen && <aside id="streamer-widget-drawer" className="sav-widget-drawer" aria-label={t("Gestione widget", "Widget manager")}><header><div><small>{t("WIDGET", "WIDGETS")}</small><strong>{t("Aggiungi o ripristina", "Add or restore")}</strong></div><button aria-label={t("Chiudi", "Close")} onClick={() => setWidgetDrawerOpen(false)}>×</button></header><p>{t("I widget rimossi restano qui e possono essere aggiunti di nuovo in qualsiasi momento.", "Removed widgets remain here and can be added back at any time.")}</p><ul>{layout.map(panel => <li key={panel.id}><span>{titles[panel.id]}</span><button disabled={panel.visible} onClick={() => setLayout(value => value.map(item => item.id === panel.id ? { ...item, visible: true } : item))}>{panel.visible ? t("Visibile", "Visible") : t("Aggiungi", "Add")}</button></li>)}</ul><footer><button onClick={() => { saveLayout(layout); setNotice(t("Layout salvato.", "Layout saved.")); }}>{t("Salva layout", "Save layout")}</button><button onClick={() => setLayout(defaultLayout())}>{t("Ripristina predefinito", "Restore default")}</button></footer></aside>}
    {runtime && <div className={`sav-analysis-stage${water ? " sav-water-enabled" : ""}`}>{water && <WaterSurface runtime={runtime} theme={theme} resetKey={`${selected?.id ?? "idle"}:${source}`} />}<AnalyzerGrid layout={layout} onChange={setLayout} render={renderPanel} titles={titles} language={language} /></div>}
    </div></div>
    {(recording.info.phase !== "idle" || recording.takes.length > 0 || recording.error) && <section className="sav-recording-tray" aria-label={t("Registrazioni locali", "Local recordings")}>
      {recording.info.phase !== "idle" && <div className="sav-recording-status" role="status"><span className={`sav-recording-led ${recording.info.phase}`} aria-hidden="true" /><strong>{recording.info.phase === "arming" ? t("Scegli la scheda o finestra MLSM Studio…", "Choose the MLSM Studio tab or window…") : recording.info.phase === "armed" ? t("Pronto · premi Play per registrare", "Armed · press Play to record") : recording.info.phase === "saving" ? t("Finalizzazione e salvataggio locale…", "Finalizing and saving locally…") : recording.info.phase === "paused" ? t("Registrazione in pausa", "Recording paused") : `REC · ${clock(recording.info.seconds)}`}</strong>{recording.info.width && <small>{recording.info.width} × {recording.info.height} · {Math.round(recording.info.fps ?? 0)} fps · {recording.info.mimeType?.split(";")[0]} · {Math.round((recording.info.videoBitrate ?? 0) / 1e6)} Mbps · WAV Float32 stereo</small>}<small>{t("Per una cattura pulita, scegli la scheda MLSM e passa ai widget a schermo intero.", "For a clean capture, choose the MLSM tab and switch to fullscreen widgets.")}</small></div>}
      {recording.error && <div className="sav-recording-error" role="alert"><strong>{t("Registrazione: ", "Recording: ")}</strong><span>{recordingErrorMessage(recording.error, language)}</span><button aria-label={t("Chiudi errore registrazione", "Dismiss recording error")} onClick={recording.clearError}>×</button></div>}
      {recording.takes.length > 0 && <details className="sav-recording-library" open={recording.info.phase === "idle"}><summary>{t("Registrazioni salvate su questo dispositivo", "Recordings saved on this device")} · {recording.takes.length}</summary><ul>{recording.takes.map(item => <li key={item.id}><div><strong>{new Date(item.created).toLocaleString(language === "it" ? "it-IT" : "en-GB")} · {clock(item.seconds)}{!item.complete && ` · ${t("Parziale", "Partial")}`}</strong><small>{item.width} × {item.height} · {Math.round(item.fps)} fps · {Math.round(item.videoBytes / 1e6)} MB · {item.sampleRate / 1000} kHz stereo</small></div><button className="sav-primary" onClick={() => void recording.save(item, "video")}>{t("Salva video", "Save video")}</button><button onClick={() => void recording.save(item, "audio")}>{t("Salva audio WAV", "Save WAV audio")}</button><button aria-label={`${t("Elimina registrazione locale", "Delete local recording")} ${item.created}`} onClick={() => void recording.remove(item)}>×</button></li>)}</ul></details>}
    </section>}
    <footer className="sav-transport"><div className="sav-now-playing"><strong>{selected?.title ?? t("Aggiungi il primo brano", "Add your first track")}</strong><small>{selected?.artist || playback}</small></div><div className="sav-transport-buttons"><button aria-label={t("Precedente", "Previous")} disabled={!selected || queue.tracks[0]?.id === selected.id} onClick={() => advance(-1)}>◀◀</button><button className="sav-primary sav-play" aria-label={playback === "PLAYING" ? t("Pausa", "Pause") : "Play"} disabled={!selected || playback === "LOADING" || recordingPending} onClick={() => playback === "PLAYING" ? pause() : void play()}>{playback === "PLAYING" ? "Ⅱ" : playback === "LOADING" || playback === "BUFFERING" ? "…" : "▶"} <span>{playback === "PLAYING" ? t("Pausa", "Pause") : "Play"}</span></button><button className="sav-record-toggle" aria-pressed={recordingEnabled} disabled={!selected || recordingPending} onClick={toggleRecording} title={t("Scegli la scheda MLSM Studio. Registra video ad alto bitrate e audio stereo della sorgente; nessun microfono aggiuntivo.", "Choose the MLSM Studio tab. Record high-bitrate video and source stereo audio; no additional microphone.")}><span aria-hidden="true">●</span> {t("Registra", "Record")}</button><button aria-label="Stop" disabled={!selected} onClick={stop}>■</button><button aria-label={t("Successivo", "Next")} disabled={!selected || queue.tracks.at(-1)?.id === selected.id} onClick={() => advance(1)}>▶▶</button></div><div className="sav-seek"><span>{clock(position)}</span><input type="range" aria-label={t("Posizione riproduzione", "Playback position")} min={0} max={duration || 1} step={.1} value={Math.min(position, duration || 1)} disabled={!duration} onChange={event => { const value = Number(event.target.value); setPosition(value); if (selected?.provider === "local") runtime?.seek(value); else player.current?.seek(value); if (resetOnTrack) runtime?.reset(); }} /><span>{clock(duration)}</span></div>{selected?.provider !== "spotify" && <label className="sav-volume">Vol<input aria-label={t("Volume", "Volume")} type="range" min={0} max={1} step={.01} value={volume} onChange={event => { const value = Number(event.target.value); setVolume(value); runtime?.setVolume(value); player.current?.setVolume(value); }} /></label>}</footer>
    <dialog className="sav-setup" ref={setup} onCancel={dismissSetup}><small>MLSM · STREAMER AUDIO VIEWER</small><h2>{t("Ascolta. Osserva. Comprendi.", "Listen. Observe. Understand.")}</h2><p>{t("I file locali vengono analizzati direttamente, senza permessi di cattura. Per Spotify, YouTube e altre applicazioni puoi autorizzare l’acquisizione dell’audio di sistema.", "Local files are analyzed directly, without capture permissions. For Spotify, YouTube and other apps you can authorize system audio capture.")}</p><p>{t("L’audio acquisito viene elaborato sul dispositivo e non viene caricato online. Viene registrato soltanto se attivi Registra e premi Play. Il microfono resta spento finché non scegli un ingresso e avvii la cattura.", "Captured audio is processed on this device and never uploaded. It is recorded only when you enable Record and press Play. The microphone stays off until you choose an input and start capture.")}</p><div>{capabilities?.systemAudio && <button className="sav-primary" onClick={() => { setSource("system"); dismissSetup(); void startCapture("system"); }}>{t("Abilita analisi audio di sistema", "Enable system audio analysis")}</button>}<button onClick={dismissSetup}>{t("Usa solo file locali", "Use local files only")}</button><button onClick={dismissSetup}>{t("Scegli sorgente nella barra laterale", "Choose source in the sidebar")}</button></div></dialog>
  </main>;
}
