import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useAudioStore } from "./store/audio-store";
import { useSceneStore } from "./store/scene-store";
import { useProjectStore } from "./store/project-store";
vi.mock("./components/Viewport", () => ({ Viewport: () => <main aria-label="Viewport scena" /> }));
import { App } from "./App";

describe("App", () => {
  it("non propone New York Streets nel selettore delle modalità", () => {
    render(<App />);
    const picker = screen.getByRole("combobox", { name: "Modalità animazione" });
    expect(within(picker).queryByRole("option", { name: "New York Streets" })).not.toBeInTheDocument();
  });
  beforeEach(() => { useProjectStore.getState().newProject(); localStorage.clear(); });
  afterEach(() => { cleanup(); useAudioStore.getState().reset(); useSceneStore.getState().reset(); });
  it("mostra il layout editor e permette di rinominare il progetto", () => {
    render(<App />);
    expect(screen.getByLabelText("Dynamic Sound Animation Studio")).toBeInTheDocument();
    expect(screen.getByRole("main", { name: "Viewport scena" })).toBeInTheDocument();
    expect(screen.getByRole("region", { name: "Timeline musicale" })).toBeInTheDocument();
    expect(screen.getByText("Sfondo e ambiente")).toBeInTheDocument(); expect(screen.getByText("Tubi in vetro")).toBeInTheDocument();
    const input = screen.getByLabelText("Nome");
    fireEvent.change(input, { target: { value: "Brano demo" } });
    expect(input).toHaveValue("Brano demo");
    fireEvent.click(screen.getByRole("button", { name: "16:9" })); expect(screen.getByRole("button", { name: "16:9" })).toHaveClass("active");
    fireEvent.click(screen.getByRole("button", { name: "Usurata" })); expect(screen.getByRole("button", { name: "Usurata" })).toHaveClass("active");
  });

  it("apre l’assistente locale con knowledge base e suggerimenti contestuali", () => {
    render(<App />);
    fireEvent.click(screen.getByRole("button", { name: "Apri assistente applicazione" }));
    const assistant = screen.getByRole("region", { name: "Assistente applicazione" });
    expect(within(assistant).getByText("SmolLM2 locale · knowledge base pronta")).toBeInTheDocument();
    fireEvent.click(within(assistant).getByRole("button", { name: "Modalità attiva" }));
    expect(within(assistant).getByLabelText("Domanda per l’assistente")).toHaveValue("Come uso bene la modalità Instrumental Falling?");
    fireEvent.click(within(assistant).getByRole("button", { name: "Chiudi assistente" }));
    expect(screen.getByRole("button", { name: "Apri assistente applicazione" })).toBeInTheDocument();
  });

  it("alterna la riproduzione con Spazio ma non mentre si scrive", async () => {
    const play = vi.spyOn(HTMLMediaElement.prototype, "play").mockResolvedValue();
    useAudioStore.getState().setImported({ url: "demo.mp3", waveform: [], metadata: { path: "demo.mp3", fileName: "demo.mp3", hash: "a".repeat(64), durationSeconds: 30, sampleRate: 48_000, channels: 2, codec: "audio/mpeg", fileSize: 1024 } });
    render(<App />); const name = screen.getByLabelText("Nome"); fireEvent.keyDown(name, { code: "Space", key: " " }); expect(play).not.toHaveBeenCalled();
    fireEvent.keyDown(window, { code: "Space", key: " " }); await waitFor(() => expect(play).toHaveBeenCalledOnce()); play.mockRestore();
  });

  it("seleziona e sostituisce un elemento dal pannello destro", () => {
    render(<App />); const inspector = screen.getByRole("complementary", { name: "Inspector" }); fireEvent.click(within(inspector).getByRole("button", { name: "Grancassa" })); const type = screen.getByLabelText("Nuovo tipo"); expect(within(type).getByRole("option", { name: "Pianoforte" })).toBeInTheDocument(); expect(within(type).getByRole("option", { name: "Chitarra / corde" })).toBeInTheDocument(); expect(within(type).getByRole("option", { name: "Violino / archi" })).toBeInTheDocument(); fireEvent.change(type, { target: { value: "cymbal" } }); expect(useSceneStore.getState().objects[0]).toMatchObject({ type: "cymbal", name: "Piatto", color: "#e94f70" });
  });
  it("cambia live l'oggetto del rimbalzo dalla timeline senza rigenerare", () => { const project = useProjectStore.getState(); project.attachAudio({ path: "track.wav", fileName: "track.wav", hash: "d".repeat(64), durationSeconds: 10, sampleRate: 48_000, channels: 2, codec: "pcm", fileSize: 100 }, []); useProjectStore.getState().addEvent(1); render(<App />); const selector = screen.getByLabelText("Oggetto del rimbalzo"); expect(within(selector).getByRole("option", { name: "Pianoforte" })).toBeInTheDocument(); fireEvent.change(selector, { target: { value: "piano" } }); expect(useSceneStore.getState().objects[0]).toMatchObject({ type: "piano", color: "#e94f70" }); expect(useProjectStore.getState().project.events[0]).toMatchObject({ assignedObjectType: "piano", assignedObjectId: "kick-1" }); });
  it("mostra Instrumental Falling e configura gli elementi della base", () => { render(<App />); const modes = screen.getByRole("complementary", { name: "Modalità animazione" }); expect(within(modes).getByRole("combobox", { name: "Modalità animazione" })).toHaveValue("instrumentalFalling"); const piano = within(modes).getByRole("checkbox", { name: /Pianoforte/ }); expect(piano).not.toBeChecked(); fireEvent.click(piano); expect(useProjectStore.getState().project.animation.baseObjectTypes).toContain("piano"); expect(within(modes).getByRole("checkbox", { name: /Chitarra \/ corde/ })).toBeInTheDocument(); expect(within(modes).getByRole("checkbox", { name: /Violino \/ archi/ })).toBeInTheDocument(); });
  it("isola il flusso Add Subtitles dai controlli 3D non pertinenti", () => { render(<App />); const modes = screen.getByRole("complementary", { name: "Modalità animazione" }); const picker = within(modes).getByRole("combobox", { name: "Modalità animazione" }); expect(within(picker).getByRole("option", { name: "Add Subtitles" })).toBeInTheDocument(); fireEvent.change(picker, { target: { value: "addSubtitles" } }); expect(within(modes).getByText("Video sorgente")).toBeInTheDocument(); expect(within(modes).getByLabelText("Carica video per sottotitoli")).toBeInTheDocument(); expect(screen.getByText("Adattamento video")).toBeInTheDocument(); expect(screen.queryByText("Sfondo e ambiente")).not.toBeInTheDocument(); expect(screen.queryByRole("checkbox", { name: "Inserisci la luce nella scena" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Importa audio" })).not.toBeInTheDocument(); expect(screen.getByRole("combobox", { name: "Modello Whisper locale" })).toHaveTextContent("Whisper Medium"); });
  it("inserisce e salva blocchi manuali nella libreria riutilizzabile", () => { useProjectStore.getState().attachAudio({ path: "voice.wav", fileName: "voice.wav", hash: "f".repeat(64), durationSeconds: 20, sampleRate: 48_000, channels: 1, codec: "pcm", fileSize: 100 }, []); render(<App />); expect(screen.getByText("Blocchi manuali e libreria")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: /Inserisci blocco al playhead/ })); const text = screen.getByLabelText("Testo sottotitolo"); fireEvent.change(text, { target: { value: "Blocco riutilizzabile" } }); fireEvent.click(screen.getByRole("button", { name: "Salva blocchi e stile nella libreria" })); expect(screen.getByRole("combobox", { name: "Traccia sottotitoli salvata" })).toHaveTextContent("Progetto senza titolo · 1 blocco"); expect(localStorage.getItem("dynamic-sound-animation-studio.subtitle-library.v1")).toContain("Blocco riutilizzabile"); });
  it("mantiene compatibili i controlli dei vecchi progetti New York Streets", () => { useProjectStore.getState().setAnimationMode("newYorkStreets", ["pebble"]); render(<App />); const modes = screen.getByRole("complementary", { name: "Modalità animazione" }); expect(within(modes).getByText("Gara di biglie")).toBeInTheDocument(); const count = within(modes).getByLabelText("Numero di sfere secondarie"); fireEvent.change(count, { target: { value: "13" } }); expect(useProjectStore.getState().project.animation.newYorkStreets.secondaryMarbleCount).toBe(13); fireEvent.change(within(modes).getByLabelText("Colore di tutte le sfere secondarie"), { target: { value: "#123456" } }); expect(useProjectStore.getState().project.animation.newYorkStreets.secondaryColors).toHaveLength(13); expect(within(modes).getByLabelText("Colore sfera secondaria 13")).toHaveValue("#123456"); expect(within(modes).getByLabelText("Carica volantini")).toHaveAttribute("multiple"); });
  it("mostra poster, palette, atmosfera e controlli vocali di Teddy Sing", () => { render(<App />); const modes = screen.getByRole("complementary", { name: "Modalità animazione" }); fireEvent.change(within(modes).getByRole("combobox", { name: "Modalità animazione" }), { target: { value: "teddySing" } }); expect(within(modes).getByText("Lip sync 3D")).toBeInTheDocument(); expect(within(modes).getByText("Importa la traccia vocale isolata.", { exact: false })).toBeInTheDocument(); fireEvent.change(within(modes).getByLabelText("Intensità lip sync Teddy Sing"), { target: { value: "1.4" } }); fireEvent.change(within(modes).getByLabelText("Colore LED Teddy Sing"), { target: { value: "#22aaff" } }); fireEvent.change(within(modes).getByLabelText("Colore particelle Teddy Sing"), { target: { value: "#ffaa33" } }); fireEvent.change(within(modes).getByLabelText("Densità particelle Teddy Sing"), { target: { value: "1.8" } }); expect(useProjectStore.getState().project.animation.teddySing).toMatchObject({ lipSyncIntensity: 1.4, ledColor: "#22aaff", particlesEnabled: true, particleColor: "#ffaa33", particleDensity: 1.8 }); });
  it("espone Stereo Unfold con apertura, pieghe, campo ed effetti stereo configurabili", () => { render(<App />); const modes = screen.getByRole("complementary", { name: "Modalità animazione" }); const picker = within(modes).getByRole("combobox", { name: "Modalità animazione" }); expect(within(picker).getByRole("option", { name: "Stereo Unfold" })).toBeInTheDocument(); fireEvent.change(picker, { target: { value: "stereoUnfold" } }); expect(within(modes).getByText("Cover fisica")).toBeInTheDocument(); expect(within(modes).getByText("Campo spettrale stereo")).toBeInTheDocument(); expect(within(modes).getByText("Effetti stereo in primo piano")).toBeInTheDocument(); expect(within(modes).getByText("Effetti a tutto schermo")).toBeInTheDocument(); fireEvent.change(within(modes).getByLabelText("Durata apertura Stereo Unfold"), { target: { value: "3.2" } }); fireEvent.change(within(modes).getByLabelText("Pieghe residue Stereo Unfold"), { target: { value: ".72" } }); fireEvent.change(within(modes).getByLabelText("Stile spettro Stereo Unfold"), { target: { value: "prisms" } }); fireEvent.click(within(modes).getByLabelText("Particelle stereo")); fireEvent.click(within(modes).getByLabelText("Raggi cromatici")); fireEvent.change(within(modes).getByLabelText("Intensità effetti Stereo Unfold"), { target: { value: "1.6" } }); expect(useProjectStore.getState().project.animation.stereoUnfold).toMatchObject({ unfoldDuration: 3.2, residualCrease: .72, spectrumStyle: "prisms", effectIntensity: 1.6, effects: { particles: false, lightTrails: true, pulseRings: true, fullScreenWaves: true, lightRays: false, chromaDust: true } }); });
  it("espone Pixel Art con sotto-modalità e nome del locale", () => { render(<App />); const modes = screen.getByRole("complementary", { name: "Modalità animazione" }); const picker = within(modes).getByRole("combobox", { name: "Modalità animazione" }); expect(within(picker).getByRole("option", { name: "Pixel Art" })).toBeInTheDocument(); fireEvent.change(picker, { target: { value: "pixelArt" } }); expect(within(modes).getByRole("option", { name: "Walking Through New York" })).toBeInTheDocument(); expect(within(modes).getByText("Regia legata alla durata")).toBeInTheDocument(); fireEvent.change(within(modes).getByLabelText("Nome locale Pixel Art"), { target: { value: "NIGHT BAR" } }); expect(useProjectStore.getState().project.animation.pixelArt).toMatchObject({ subMode: "walkingThroughNewYork", venueName: "NIGHT BAR" }); });
  it("mantiene la luce personalizzata disponibile in entrambe le modalità", () => { render(<App />); const enabled = screen.getByRole("checkbox", { name: "Inserisci la luce nella scena" }); fireEvent.click(enabled); fireEvent.change(screen.getByLabelText("Colore luce"), { target: { value: "#33aaff" } }); fireEvent.change(screen.getByLabelText("Intensità luce"), { target: { value: "72" } }); fireEvent.change(screen.getByLabelText("Densità fascio"), { target: { value: ".68" } }); fireEvent.change(screen.getByLabelText("Estensione fascio"), { target: { value: "3" } }); fireEvent.click(screen.getAllByRole("button", { name: "Scegli nella scena" })[0]!); expect(screen.getByRole("checkbox", { name: "Segui la biglia per tutto il percorso" })).toBeChecked(); expect(screen.getByRole("checkbox", { name: "Luce attiva per tutto il video" })).toBeChecked(); expect(useSceneStore.getState().light).toMatchObject({ enabled: true, color: "#33aaff", intensity: 72, beamVisible: true, beamDensity: .68, beamLengthMultiplier: 3, followBall: true, activeUntilSeconds: null }); expect(useSceneStore.getState().lightPickMode).toBe("origin"); const modes = screen.getByRole("complementary", { name: "Modalità animazione" }); fireEvent.change(within(modes).getByRole("combobox", { name: "Modalità animazione" }), { target: { value: "newYorkStreets" } }); expect(screen.getByRole("checkbox", { name: "Inserisci la luce nella scena" })).toBeChecked(); expect(screen.getByLabelText("Colore luce")).toHaveValue("#33aaff"); });
});
