import { type ChangeEvent } from "react";
import { getAnimationCategory, getAnimationMode } from "../services/animation-modes";
import { uiCopy, useUiPreferences } from "../services/ui-preferences";
import { useProjectStore } from "../store/project-store";
import { useSceneStore } from "../store/scene-store";
import { extractPaletteFromImage } from "../services/image-palette";
import { SubtitlePanel } from "./SubtitlePanel";
import { ProSubtitlesPanel } from "./ProSubtitlesPanel";
import { PixelsSubPanel } from "./PixelsSubPanel";
import { StaticWatermarkPanel } from "./StaticWatermarkPanel";
import { UpscalerPanel } from "./UpscalerPanel";
import { PortraitLandscapePanel } from "./PortraitLandscapePanel";
import { VideoEditorPanel } from "./VideoEditorPanel";
import { BackgroundAutoPanel } from "./BackgroundAutoPanel";
import { FrameBoosterPanel } from "./FrameBoosterPanel";
import { SongPlayerPanel } from "./SongPlayerPanel";
import { CassetteDeskPanel } from "./CassetteDeskPanel";
import { CommentsInvasionPanel } from "./CommentsInvasionPanel";
import { OverlaySpectralPanel } from "./OverlaySpectralPanel";
import { SoundSettingsAccordion } from "./SoundSettingsAccordion";

function imageDataUrl(file: File): Promise<string | null> {
  return new Promise((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(typeof reader.result === "string" ? reader.result : null); reader.onerror = () => resolve(null); reader.readAsDataURL(file); });
}

/** Modalità che portano già la propria timeline e il proprio pannello di testo. */
const standaloneEditingPanels = ["proSubtitles", "portraitLandscape", "commentsInvasion", "backgroundAuto", "staticWatermark", "upscaler", "frameBooster", "videoEditor", "songPlayer", "cassetteDesk", "overlaySpectral"] as const;

export function LibraryPanel({ canRegenerate, onRegenerate, onImportAudioFragment, onImportSubtitleVideo, audioUrl, duration, currentTime, selectedSubtitleId, onSelectSubtitle }: { canRegenerate: boolean; onRegenerate: () => void; onImportAudioFragment: () => Promise<void>; onImportSubtitleVideo: (file: File) => Promise<void>; audioUrl: string | null; duration: number; currentTime: number; selectedSubtitleId: string | null; onSelectSubtitle: (id: string | null) => void }) {
  const { language } = useUiPreferences(); const copy = uiCopy[language];
  const modeId = useProjectStore((state) => state.project.animation.modeId); const baseObjectTypes = useProjectStore((state) => state.project.animation.baseObjectTypes); const newYork = useProjectStore((state) => state.project.animation.newYorkStreets); const cover = useProjectStore((state) => state.project.animation.coverSphere); const stereoUnfold = useProjectStore((state) => state.project.animation.stereoUnfold); const walkingCube = useProjectStore((state) => state.project.animation.walkingCube); const portraitLandscape = useProjectStore((state) => state.project.animation.portraitLandscape); const teddy = useProjectStore((state) => state.project.animation.teddyWalk); const teddySing = useProjectStore((state) => state.project.animation.teddySing);
  const setAnimationMode = useProjectStore((state) => state.setAnimationMode); const setBaseObjectEnabled = useProjectStore((state) => state.setBaseObjectEnabled); const setNewYorkMarbleCount = useProjectStore((state) => state.setNewYorkMarbleCount); const setNewYorkGroupColor = useProjectStore((state) => state.setNewYorkGroupColor); const setNewYorkMarbleColor = useProjectStore((state) => state.setNewYorkMarbleColor); const addNewYorkFlyers = useProjectStore((state) => state.addNewYorkFlyers); const removeNewYorkFlyer = useProjectStore((state) => state.removeNewYorkFlyer); const updateCoverSphere = useProjectStore((state) => state.updateCoverSphere); const setCoverSphereAutoPalette = useProjectStore((state) => state.setCoverSphereAutoPalette); const setCoverSpherePalette = useProjectStore((state) => state.setCoverSpherePalette); const addCoverSphereFlyers = useProjectStore((state) => state.addCoverSphereFlyers); const removeCoverSphereFlyer = useProjectStore((state) => state.removeCoverSphereFlyer); const updateStereoUnfold = useProjectStore((state) => state.updateStereoUnfold); const setStereoUnfoldPalette = useProjectStore((state) => state.setStereoUnfoldPalette); const setStereoUnfoldAutoPalette = useProjectStore((state) => state.setStereoUnfoldAutoPalette); const updateWalkingCube = useProjectStore((state) => state.updateWalkingCube); const setWalkingCubePalette = useProjectStore((state) => state.setWalkingCubePalette); const updateTeddyWalk = useProjectStore((state) => state.updateTeddyWalk); const setTeddyWalkPalette = useProjectStore((state) => state.setTeddyWalkPalette); const updateTeddySing = useProjectStore((state) => state.updateTeddySing); const setTeddySingPalette = useProjectStore((state) => state.setTeddySingPalette);
  const ball = useSceneStore((state) => state.ball); const sceneBackground = useSceneStore((state) => state.background); const updateBall = useSceneStore((state) => state.updateBall); const updateBackground = useSceneStore((state) => state.updateBackground); const applyExtractedPalette = useSceneStore((state) => state.applyExtractedPalette); const mode = getAnimationMode(modeId); const category = getAnimationCategory(modeId);
  const loadFlyers = async (change: ChangeEvent<HTMLInputElement>) => { const urls = (await Promise.all([...change.target.files ?? []].slice(0, 8).map(imageDataUrl))).filter((url): url is string => Boolean(url)); if (urls.length) addNewYorkFlyers(urls); change.target.value = ""; };
  const loadCover = async (change: ChangeEvent<HTMLInputElement>) => { const file = change.target.files?.[0]; const url = file ? await imageDataUrl(file) : null; if (url) { updateBall({ innerImageUrl: url }); const colors = await extractPaletteFromImage(url).catch(() => []); if (colors.length) { applyExtractedPalette(colors); setCoverSpherePalette(colors); } } change.target.value = ""; };
  const loadStereoUnfoldCover = async (change: ChangeEvent<HTMLInputElement>) => { const file = change.target.files?.[0]; const url = file ? await imageDataUrl(file) : null; if (url) { updateStereoUnfold({ coverImageUrl: url }); const colors = await extractPaletteFromImage(url).catch(() => []); if (colors.length) { applyExtractedPalette(colors); setStereoUnfoldPalette(colors); } } change.target.value = ""; };
  const applyWalkingCubeImagePalette = async (url: string) => { const colors = await extractPaletteFromImage(url).catch(() => []); if (colors.length) { applyExtractedPalette(colors); setWalkingCubePalette(colors); } };
  const loadWalkingCubeImage = async (change: ChangeEvent<HTMLInputElement>) => { const file = change.target.files?.[0]; const url = file ? await imageDataUrl(file) : null; if (url) { updateWalkingCube({ imageUrl: url, autoPalette: true }); const colors = await extractPaletteFromImage(url).catch(() => []); if (colors.length) { applyExtractedPalette(colors); setWalkingCubePalette(colors); } } change.target.value = ""; };
  const toggleWalkingCubeAutoPalette = async (enabled: boolean) => { updateWalkingCube({ autoPalette: enabled }); if (enabled && walkingCube.imageUrl) await applyWalkingCubeImagePalette(walkingCube.imageUrl); };
  const loadWalkingCubeBackground = async (change: ChangeEvent<HTMLInputElement>) => { const file = change.target.files?.[0]; const url = file ? await imageDataUrl(file) : null; if (url) { updateWalkingCube({ backgroundImageUrl: url }); updateBackground({ imageUrl: url, mediaType: "image", presetId: "custom", opacity: 1, blur: 0 }); } change.target.value = ""; };
  const removeWalkingCubeBackground = () => { updateWalkingCube({ backgroundImageUrl: null }); updateBackground({ imageUrl: null, mediaType: "image", presetId: "gradient" }); };
  const loadCoverFlyers = async (change: ChangeEvent<HTMLInputElement>) => { const urls = (await Promise.all([...change.target.files ?? []].slice(0, 8).map(imageDataUrl))).filter((url): url is string => Boolean(url)); if (urls.length) addCoverSphereFlyers(urls); change.target.value = ""; };
  const loadTeddyCover = async (change: ChangeEvent<HTMLInputElement>) => { const file = change.target.files?.[0]; const url = file ? await imageDataUrl(file) : null; if (url) { updateTeddyWalk({ coverImageUrl: url }); const colors = await extractPaletteFromImage(url).catch(() => []); if (colors.length) { applyExtractedPalette(colors); setTeddyWalkPalette(colors); } } change.target.value = ""; };
  const loadTeddyPoster = async (change: ChangeEvent<HTMLInputElement>) => { const file = change.target.files?.[0]; const url = file ? await imageDataUrl(file) : null; if (url) { updateTeddySing({ posterImageUrl: url }); const colors = await extractPaletteFromImage(url).catch(() => []); if (colors.length) { applyExtractedPalette(colors); setTeddySingPalette(colors); } } change.target.value = ""; };
  const walkingCubeBackgroundPreview = walkingCube.backgroundImageUrl ?? (sceneBackground.mediaType === "image" ? sceneBackground.imageUrl : null);
  const selectMode = (selectedId: string) => { const selected = getAnimationMode(selectedId); setAnimationMode(selected.id, [...selected.defaultBaseObjectTypes]); };
  const activeGroup = category.groups.find((group) => group.modeIds.includes(mode.id)) ?? category.groups[0]!;
  const navigation = <section className="creative-navigation" aria-label={copy.navigation}><div className="animation-navigation-selectors"><label className="mode-picker">Tipo animazione<select aria-label="Tipo animazione" value={activeGroup.id} onChange={(change) => { const group = category.groups.find((item) => item.id === change.target.value); const firstModeId = group?.modeIds[0]; if (firstModeId) selectMode(firstModeId); }}>{category.groups.map((group) => <option key={group.id} value={group.id}>{copy[group.id]}</option>)}</select></label><label className="mode-picker">Animazione<select aria-label="Modalità animazione" value={mode.id} onChange={(change) => selectMode(change.target.value)}>{category.groups.map((group) => <optgroup key={group.id} label={copy[group.id]}>{group.modeIds.map((id) => { const item = getAnimationMode(id); return <option key={item.id} value={item.id}>{item.label}</option>; })}</optgroup>)}</select></label></div></section>;
  if (mode.panel === "cassetteDesk") return <aside className="panel library animation-mode-panel" aria-label="Modalità animazione"><div className="animation-mode-heading"><span>{copy.currentMode}</span><strong>{mode.label}</strong></div>{navigation}<p className="mode-description">{mode.description}</p><SoundSettingsAccordion resetKey={mode.id}><CassetteDeskPanel onImportAudio={() => void onImportAudioFragment()} /></SoundSettingsAccordion></aside>;
  if (mode.panel === "overlaySpectral") return <aside className="panel library animation-mode-panel" aria-label="Modalità animazione"><div className="animation-mode-heading"><span>{copy.currentMode}</span><strong>{mode.label}</strong></div>{navigation}<p className="mode-description">{mode.description}</p><SoundSettingsAccordion resetKey={mode.id}><OverlaySpectralPanel onImportAudio={() => void onImportAudioFragment()} /></SoundSettingsAccordion></aside>;
  return <aside className="panel library animation-mode-panel" aria-label="Modalità animazione">
    <div className="animation-mode-heading"><span>{copy.currentMode}</span><strong>{mode.label}</strong></div>
    {navigation}
    <p className="mode-description">{mode.description}</p>
    <SoundSettingsAccordion resetKey={mode.id}>{mode.panel === "instrumentalObjects" ? <section className="base-objects"><h2>Elementi della base</h2><p className="muted">Scegli le famiglie che il generatore può usare. Gli oggetti creati saranno poi modificabili singolarmente nel pannello destro.</p><div className="base-object-list">{mode.objectTypes.map((item) => { const checked = baseObjectTypes.includes(item.type); return <label key={item.type} className={checked ? "selected" : ""}><input type="checkbox" checked={checked} disabled={checked && baseObjectTypes.length === 1} onChange={(change) => setBaseObjectEnabled(item.type, change.target.checked)} /><span className={`object-icon icon-${item.type}`} /><span><strong>{item.label}</strong><small>{item.description}</small></span></label>; })}</div></section> : mode.panel === "newYorkStreets" ? <>
      <section className="street-marble-settings"><h2>Gara di biglie</h2><p className="muted">Ogni biglia corre in modo autonomo: cambia corsia, sorpassa, collide e rimbalza con una propria risposta fisica.</p><label>Secondarie: {newYork.secondaryMarbleCount}<input aria-label="Numero di sfere secondarie" type="range" min="1" max="13" step="1" value={newYork.secondaryMarbleCount} onChange={(change) => setNewYorkMarbleCount(Number(change.target.value))} /></label><div className="street-color-pair"><label>Principale<input aria-label="Colore sfera principale" type="color" value={ball.color} onChange={(change) => updateBall({ color: change.target.value })} /></label><label>Tutte le secondarie<input aria-label="Colore di tutte le sfere secondarie" type="color" value={newYork.secondaryGroupColor} onChange={(change) => setNewYorkGroupColor(change.target.value)} /></label></div><div className="secondary-marble-colors">{Array.from({ length: newYork.secondaryMarbleCount }, (_, index) => <label key={index}><span>Secondaria {index + 1}</span><input aria-label={`Colore sfera secondaria ${index + 1}`} type="color" value={newYork.secondaryColors[index] ?? newYork.secondaryGroupColor} onChange={(change) => setNewYorkMarbleColor(index, change.target.value)} /></label>)}</div></section>
      <section className="street-flyers"><h2>Volantini urbani</h2><p className="muted">Le immagini caricate diventano fogli accartocciati e strappati distribuiti sia sul marciapiede sia nelle fognature.</p><label className="flyer-upload">Carica immagini<input aria-label="Carica volantini" type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={(change) => void loadFlyers(change)} /></label>{newYork.flyerImageUrls.length ? <div className="flyer-list">{newYork.flyerImageUrls.map((url, index) => <div key={`${url.slice(0, 30)}-${index}`}><span style={{ backgroundImage: `url(${url})` }} /><button aria-label={`Rimuovi volantino ${index + 1}`} onClick={() => removeNewYorkFlyer(index)}>×</button></div>)}</div> : null}<p className="muted">L’immagine incorporata nella sfera principale resta configurabile nel pannello destro.</p></section>
    </> : mode.panel === "backgroundAuto" ? <><BackgroundAutoPanel /><ProSubtitlesPanel audioUrl={audioUrl} duration={duration} selectedSubtitleId={selectedSubtitleId} onSelectSubtitle={onSelectSubtitle} source={{ kind: "embedded", ready: true, name: "Circular Spectrum" }} /></> : mode.panel === "coverSphere" ? <section className="cover-visualizer-settings">
      <h2>Copertina nella sfera</h2><label className="flyer-upload">Carica immagine di copertina<input aria-label="Carica immagine di copertina" type="file" accept="image/png,image/jpeg,image/webp" onChange={(change) => void loadCover(change)} /></label>{ball.innerImageUrl ? <div className="cover-thumbnail" style={{ backgroundImage: `url(${ball.innerImageUrl})` }} /> : <p className="muted">Carica una copertina: verrà incorporata nella grande sfera e ne definirà automaticamente la palette.</p>}
      <h2>Spettrogramma a 48 bande</h2><label className="teddy-dance-toggle"><span>Colori automatici dalla cover</span><input aria-label="Palette automatica spettrogramma" type="checkbox" checked={cover.autoPalette} onChange={(change) => setCoverSphereAutoPalette(change.target.checked)} /></label><label>Colore bande<input aria-label="Colore spettrogramma" type="color" value={cover.spectrumColor} onChange={(change) => updateCoverSphere({ spectrumColor: change.target.value, autoPalette: false })} /></label><label>Rotazione fluida: {cover.rotationIntensity.toFixed(1)}×<input aria-label="Rotazione ritmica" type="range" min=".1" max="3" step=".1" value={cover.rotationIntensity} onChange={(change) => updateCoverSphere({ rotationIntensity: Number(change.target.value) })} /></label>
      <h2>Effetti davanti allo sfondo</h2><label>Colore effetti<input aria-label="Colore effetti visualizer" type="color" value={cover.effectColor} onChange={(change) => updateCoverSphere({ effectColor: change.target.value, autoPalette: false })} /></label><div className="visualizer-effects">{([["smoke", "Fumo"], ["particles", "Particelle"], ["windLeaves", "Vento e foglie"], ["rain", "Pioggia"], ["flyers", "Volantini"]] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={cover.effects[key]} onChange={(change) => updateCoverSphere({ effects: { ...cover.effects, [key]: change.target.checked } })} /> {label}</label>)}</div>
      <label className="flyer-upload">Carica immagini per i volantini<input aria-label="Carica volantini visualizer" type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={(change) => void loadCoverFlyers(change)} /></label>{cover.flyerImageUrls.length ? <div className="flyer-list">{cover.flyerImageUrls.map((url, index) => <div key={`${url.slice(0, 30)}-${index}`}><span style={{ backgroundImage: `url(${url})` }} /><button aria-label={`Rimuovi volantino visualizer ${index + 1}`} onClick={() => removeCoverSphereFlyer(index)}>×</button></div>)}</div> : null}
    </section> : mode.panel === "stereoUnfold" ? <section className="stereo-unfold-settings">
      <h2>Cover fisica</h2><label className="flyer-upload">Carica immagine di copertina<input aria-label="Carica cover Stereo Unfold" type="file" accept="image/png,image/jpeg,image/webp" onChange={(change) => void loadStereoUnfoldCover(change)} /></label>{stereoUnfold.coverImageUrl ? <div className="cover-thumbnail" style={{ backgroundImage: `url(${stereoUnfold.coverImageUrl})` }} /> : <p className="muted">La cover entrerà dall’alto come carta stropicciata, poi si aprirà conservando pieghe, ombre e bordi leggermente curvi.</p>}
      <label>Durata ingresso e apertura: {stereoUnfold.unfoldDuration.toFixed(1)} s<input aria-label="Durata apertura Stereo Unfold" type="range" min=".8" max="5" step=".1" value={stereoUnfold.unfoldDuration} onChange={(change) => updateStereoUnfold({ unfoldDuration: Number(change.target.value) })} /></label>
      <label>Pieghe residue: {Math.round(stereoUnfold.residualCrease * 100)}%<input aria-label="Pieghe residue Stereo Unfold" type="range" min=".08" max="1" step=".01" value={stereoUnfold.residualCrease} onChange={(change) => updateStereoUnfold({ residualCrease: Number(change.target.value) })} /></label>
      <h2>Campo spettrale stereo</h2><label>Stile<select aria-label="Stile spettro Stereo Unfold" value={stereoUnfold.spectrumStyle} onChange={(change) => updateStereoUnfold({ spectrumStyle: change.target.value as typeof stereoUnfold.spectrumStyle })}><option value="ribbons">Nastri luminosi</option><option value="prisms">Prismi di frequenza</option><option value="aurora">Aurora stereofonica</option></select></label>
      <label>Profondità stereo: {stereoUnfold.stereoDepth.toFixed(1)}×<input aria-label="Profondità stereo" type="range" min=".2" max="3" step=".05" value={stereoUnfold.stereoDepth} onChange={(change) => updateStereoUnfold({ stereoDepth: Number(change.target.value) })} /></label>
      <label>Intensità spettro: {stereoUnfold.spectrumIntensity.toFixed(1)}×<input aria-label="Intensità spettro Stereo Unfold" type="range" min=".2" max="3" step=".05" value={stereoUnfold.spectrumIntensity} onChange={(change) => updateStereoUnfold({ spectrumIntensity: Number(change.target.value) })} /></label>
      <label>Bagliore ambientale: {stereoUnfold.glowIntensity.toFixed(1)}×<input aria-label="Bagliore Stereo Unfold" type="range" min="0" max="3" step=".05" value={stereoUnfold.glowIntensity} onChange={(change) => updateStereoUnfold({ glowIntensity: Number(change.target.value) })} /></label>
      <h2>Effetti stereo in primo piano</h2><div className="visualizer-effects">{([["particles", "Particelle stereo"], ["lightTrails", "Scie luminose"], ["pulseRings", "Anelli d’impulso"]] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={stereoUnfold.effects[key]} onChange={(change) => updateStereoUnfold({ effects: { ...stereoUnfold.effects, [key]: change.target.checked } })} /> {label}</label>)}</div>
      <h2>Effetti a tutto schermo</h2><div className="visualizer-effects">{([["fullScreenWaves", "Onde stereo concentriche"], ["lightRays", "Raggi cromatici"], ["chromaDust", "Polvere luminosa"]] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={stereoUnfold.effects[key]} onChange={(change) => updateStereoUnfold({ effects: { ...stereoUnfold.effects, [key]: change.target.checked } })} /> {label}</label>)}</div>
      <label>Intensità effetti: {stereoUnfold.effectIntensity.toFixed(1)}×<input aria-label="Intensità effetti Stereo Unfold" type="range" min="0" max="3" step=".05" value={stereoUnfold.effectIntensity} onChange={(change) => updateStereoUnfold({ effectIntensity: Number(change.target.value) })} /></label>
      <label className="teddy-dance-toggle"><span>Palette automatica dalla cover</span><input aria-label="Palette automatica Stereo Unfold" type="checkbox" checked={stereoUnfold.autoPalette} onChange={(change) => setStereoUnfoldAutoPalette(change.target.checked)} /></label><div className="teddy-palette"><label>Canale sinistro<input aria-label="Colore canale sinistro" type="color" value={stereoUnfold.primaryColor} onChange={(change) => updateStereoUnfold({ primaryColor: change.target.value, autoPalette: false })} /></label><label>Canale destro<input aria-label="Colore canale destro" type="color" value={stereoUnfold.secondaryColor} onChange={(change) => updateStereoUnfold({ secondaryColor: change.target.value, autoPalette: false })} /></label></div>
      <p className="muted">I canali non sono duplicati: l’analisi conserva separatamente spettro ed energia L/R. I file mono usano automaticamente una composizione simmetrica.</p>
    </section> : mode.panel === "walkingCube" ? <section className="cover-visualizer-settings walking-cube-settings">
      <h2>Immagine sulle sei facce</h2><label className="flyer-upload">Carica immagine del cubo<input aria-label="Carica immagine Cube Animation" type="file" accept="image/png,image/jpeg,image/webp" onChange={(change) => void loadWalkingCubeImage(change)} /></label>{walkingCube.imageUrl ? <div className="cover-thumbnail" style={{ backgroundImage: `url(${walkingCube.imageUrl})` }} /> : <p className="muted">L’immagine verrà adattata senza tagli e applicata a ogni faccia sotto uno strato di vetro fisico.</p>}
      <h2>Palette della scena</h2><label className="teddy-dance-toggle"><span>Palette automatica dall’immagine</span><input aria-label="Palette automatica Cube Animation" type="checkbox" checked={walkingCube.autoPalette} onChange={(change) => void toggleWalkingCubeAutoPalette(change.target.checked)} /></label><div className="teddy-palette"><label>Primario<input aria-label="Colore primario Cube Animation" type="color" value={walkingCube.palettePrimary} onChange={(change) => updateWalkingCube({ palettePrimary: change.target.value, autoPalette: false })} /></label><label>Secondario<input aria-label="Colore secondario Cube Animation" type="color" value={walkingCube.paletteSecondary} onChange={(change) => updateWalkingCube({ paletteSecondary: change.target.value, autoPalette: false })} /></label><label>Accento<input aria-label="Colore accento Cube Animation" type="color" value={walkingCube.paletteAccent} onChange={(change) => updateWalkingCube({ paletteAccent: change.target.value, autoPalette: false })} /></label></div>
      <h2>Rotazione e vetro</h2><label>Risposta ritmica: {walkingCube.rotationIntensity.toFixed(1)}×<input aria-label="Intensità rotazione Cube Animation" type="range" min=".25" max="2.5" step=".05" value={walkingCube.rotationIntensity} onChange={(change) => updateWalkingCube({ rotationIntensity: Number(change.target.value) })} /></label><label>Presenza del vetro: {Math.round(walkingCube.glassOpacity * 100)}%<input aria-label="Presenza vetro Cube Animation" type="range" min=".08" max=".65" step=".01" value={walkingCube.glassOpacity} onChange={(change) => updateWalkingCube({ glassOpacity: Number(change.target.value) })} /></label>
      <h2>Sfondo immagine</h2><label className="flyer-upload">Carica immagine di sfondo<input aria-label="Carica sfondo Cube Animation" type="file" accept="image/png,image/jpeg,image/webp" onChange={(change) => void loadWalkingCubeBackground(change)} /></label>{walkingCubeBackgroundPreview ? <><div className="cover-thumbnail" style={{ backgroundImage: `url(${walkingCubeBackgroundPreview})` }} /><button type="button" onClick={removeWalkingCubeBackground}>Rimuovi sfondo</button></> : <p className="muted">Puoi caricarlo qui oppure dal pannello Scena: entrambi i controlli aggiornano lo stesso sfondo dietro il cubo.</p>}<label>Oscuramento sfondo: {Math.round(walkingCube.backgroundDim * 100)}%<input aria-label="Oscuramento sfondo Cube Animation" type="range" min="0" max=".9" step=".01" value={walkingCube.backgroundDim} onChange={(change) => updateWalkingCube({ backgroundDim: Number(change.target.value) })} /></label>
      <h2>Spettrogramma ed effetti</h2><label>Intensità spettro: {walkingCube.spectrumIntensity.toFixed(1)}×<input aria-label="Intensità spettrogramma Cube Animation" type="range" min=".1" max="3" step=".05" value={walkingCube.spectrumIntensity} onChange={(change) => updateWalkingCube({ spectrumIntensity: Number(change.target.value) })} /></label><div className="visualizer-effects">{([["waterRipples", "Increspature d’acqua"], ["halo", "Alone ottico"], ["orbitRings", "Anelli orbitali"], ["particles", "Particelle profonde"], ["lightSweeps", "Light sweep"]] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={walkingCube.effects[key]} onChange={(change) => updateWalkingCube({ effects: { ...walkingCube.effects, [key]: change.target.checked } })} /> {label}</label>)}</div>{walkingCube.effects.waterRipples ? <label>Intensità increspature: {walkingCube.rippleIntensity.toFixed(1)}×<input aria-label="Intensità increspature Cube Animation" type="range" min="0" max="3" step=".05" value={walkingCube.rippleIntensity} onChange={(change) => updateWalkingCube({ rippleIntensity: Number(change.target.value) })} /></label> : null}<div className="vocal-track-advice"><strong>Composizione centrale pulita</strong><span>Il cubo resta sospeso e ruota soltanto sui beat. Spettrogramma, increspature, alone e profondità reagiscono all’audio senza spostare il soggetto.</span></div>
    </section> : mode.panel === "songPlayer" ? <SongPlayerPanel onImportFragment={onImportAudioFragment} /> : mode.panel === "portraitLandscape" ? <><PortraitLandscapePanel onImportVideo={onImportSubtitleVideo} /><ProSubtitlesPanel audioUrl={audioUrl} duration={duration} selectedSubtitleId={selectedSubtitleId} onSelectSubtitle={onSelectSubtitle} source={{ kind: "embedded", ready: Boolean(portraitLandscape.videoUrl), name: portraitLandscape.videoName }} /></> : mode.panel === "commentsInvasion" ? <CommentsInvasionPanel onImportVideo={onImportSubtitleVideo} /> : mode.panel === "teddyWalk" ? <section className="teddy-walk-settings">
      <h2>Cover nello squarcio</h2><label className="flyer-upload">Carica cover del brano<input aria-label="Carica cover Teddy Walk" type="file" accept="image/png,image/jpeg,image/webp" onChange={(change) => void loadTeddyCover(change)} /></label>{teddy.coverImageUrl ? <div className="cover-thumbnail teddy-cover-thumbnail" style={{ backgroundImage: `url(${teddy.coverImageUrl})` }} /> : <p className="muted">La cover sarà incorporata nello squarcio sul petto e pulserà con la musica.</p>}
      <div className="teddy-palette"><label>Pelo<input aria-label="Colore pelo orsacchiotto" type="color" value={teddy.furColor} onChange={(change) => updateTeddyWalk({ furColor: change.target.value })} /></label><label>Toppe<input aria-label="Colore toppe orsacchiotto" type="color" value={teddy.patchColor} onChange={(change) => updateTeddyWalk({ patchColor: change.target.value })} /></label><label>Dettagli<input aria-label="Colore dettagli orsacchiotto" type="color" value={teddy.accentColor} onChange={(change) => updateTeddyWalk({ accentColor: change.target.value })} /></label><label>Asfalto<input aria-label="Colore asfalto Teddy Walk" type="color" value={teddy.roadColor} onChange={(change) => updateTeddyWalk({ roadColor: change.target.value })} /></label></div>
      <h2>Movimento · Motion capture</h2><label>Passo: {teddy.walkIntensity.toFixed(1)}×<input aria-label="Intensità camminata orsacchiotto" type="range" min=".1" max="3" step=".1" value={teddy.walkIntensity} onChange={(change) => updateTeddyWalk({ walkIntensity: Number(change.target.value) })} /></label><label className="teddy-dance-toggle"><span>Balla mentre cammina</span><input aria-label="Balla mentre cammina" type="checkbox" checked={teddy.danceEnabled} onChange={(change) => updateTeddyWalk({ danceEnabled: change.target.checked })} /></label><label>Pulsazione cover: {teddy.pulseIntensity.toFixed(1)}×<input aria-label="Pulsazione cover orsacchiotto" type="range" min="0" max="2" step=".05" value={teddy.pulseIntensity} onChange={(change) => updateTeddyWalk({ pulseIntensity: Number(change.target.value) })} /></label><p className="muted">{teddy.danceEnabled ? "Le clip Mixamo Hip Hop, Silly Dance e Jump vengono adattate al BPM, fuse con la camminata e riprodotte senza deriva laterale." : "La clip Walking viene adattata a un ciclo lento di quattro beat mantenendo il mezzo profilo."}</p>
    </section> : mode.panel === "teddySing" ? <section className="teddy-walk-settings teddy-sing-settings">
      <h2>Poster sulla parete</h2><label className="flyer-upload">Carica cover / poster<input aria-label="Carica poster Teddy Sing" type="file" accept="image/png,image/jpeg,image/webp" onChange={(change) => void loadTeddyPoster(change)} /></label>{teddySing.posterImageUrl ? <div className="cover-thumbnail teddy-cover-thumbnail" style={{ backgroundImage: `url(${teddySing.posterImageUrl})` }} /> : <p className="muted">L’immagine sarà montata per intero in una cornice fisica sulla parete e definirà automaticamente la palette della stanza.</p>}
      <div className="teddy-palette"><label>Pelo<input aria-label="Colore pelo Teddy Sing" type="color" value={teddySing.furColor} onChange={(change) => updateTeddySing({ furColor: change.target.value })} /></label><label>Toppe<input aria-label="Colore toppe Teddy Sing" type="color" value={teddySing.patchColor} onChange={(change) => updateTeddySing({ patchColor: change.target.value })} /></label><label>Stanza<input aria-label="Colore stanza Teddy Sing" type="color" value={teddySing.roomColor} onChange={(change) => updateTeddySing({ roomColor: change.target.value })} /></label><label>LED<input aria-label="Colore LED Teddy Sing" type="color" value={teddySing.ledColor} onChange={(change) => updateTeddySing({ ledColor: change.target.value })} /></label></div>
      <h2>Lip sync 3D</h2><div className="vocal-track-advice"><strong>Consiglio per un labiale preciso</strong><span>Importa la traccia vocale isolata. Il brano completo funziona, ma batteria e synth possono essere interpretati come consonanti.</span></div>
      <label>Espressività bocca: {teddySing.lipSyncIntensity.toFixed(1)}×<input aria-label="Intensità lip sync Teddy Sing" type="range" min=".1" max="2.5" step=".05" value={teddySing.lipSyncIntensity} onChange={(change) => updateTeddySing({ lipSyncIntensity: Number(change.target.value) })} /></label>
      <label>Sensibilità voce: {teddySing.vocalSensitivity.toFixed(1)}×<input aria-label="Sensibilità vocale Teddy Sing" type="range" min=".2" max="2.5" step=".05" value={teddySing.vocalSensitivity} onChange={(change) => updateTeddySing({ vocalSensitivity: Number(change.target.value) })} /></label>
      <label>Movimento testa: {teddySing.headMotion.toFixed(1)}×<input aria-label="Movimento testa Teddy Sing" type="range" min="0" max="2" step=".05" value={teddySing.headMotion} onChange={(change) => updateTeddySing({ headMotion: Number(change.target.value) })} /></label>
      <h2>Atmosfera</h2><label className="teddy-dance-toggle"><span>Particelle nella stanza</span><input aria-label="Particelle Teddy Sing" type="checkbox" checked={teddySing.particlesEnabled} onChange={(change) => updateTeddySing({ particlesEnabled: change.target.checked })} /></label>
      {teddySing.particlesEnabled ? <><label>Colore particelle<input aria-label="Colore particelle Teddy Sing" type="color" value={teddySing.particleColor} onChange={(change) => updateTeddySing({ particleColor: change.target.value })} /></label><label>Densità particelle: {teddySing.particleDensity.toFixed(1)}×<input aria-label="Densità particelle Teddy Sing" type="range" min=".1" max="2.5" step=".1" value={teddySing.particleDensity} onChange={(change) => updateTeddySing({ particleDensity: Number(change.target.value) })} /></label></> : null}
      <p className="muted">Il labiale deforma mandibola, labbra e lingua della geometria 3D. Analizza nuovamente il file dopo aver importato la voce.</p>
    </section> : mode.panel === "pixelsSub" ? <PixelsSubPanel duration={duration} onSelectSubtitle={onSelectSubtitle} /> : mode.panel === "proSubtitles" ? <ProSubtitlesPanel audioUrl={audioUrl} duration={duration} selectedSubtitleId={selectedSubtitleId} onSelectSubtitle={onSelectSubtitle} source={{ kind: "standalone", onImportVideo: onImportSubtitleVideo }} /> : mode.panel === "staticWatermark" ? <StaticWatermarkPanel onImportVideo={onImportSubtitleVideo} /> : mode.panel === "upscaler" ? <UpscalerPanel /> : mode.panel === "videoEditor" ? <VideoEditorPanel /> : null}
    {mode.panel === "frameBooster" ? <FrameBoosterPanel /> : null}
    {mode.panel === "instrumentalObjects" || mode.panel === "newYorkStreets" ? <button className="regenerate-base" onClick={onRegenerate} disabled={!canRegenerate}>{mode.id === "newYorkStreets" ? "Genera New York Streets" : "Applica e rigenera base"}</button> : null}
    {standaloneEditingPanels.some((panel) => panel === mode.panel) ? null : <><SubtitlePanel audioUrl={audioUrl} duration={duration} currentTime={currentTime} /><p className="muted mode-extension-note">Ogni modalità fornisce generatore, oggetti e controlli specifici senza modificare il layout comune dell’editor.</p></>}</SoundSettingsAccordion>
  </aside>;
}
