import { useProjectStore } from "../store/project-store";
import { overlaySpectralPreset } from "../services/overlay-spectral-catalog";
import { SoundInspectorAccordion } from "./SoundInspectorAccordion";

export function OverlaySpectralInspector({ aspectRatio, onAspectRatio }: { aspectRatio: string; onAspectRatio: (ratio: "9:16" | "16:9") => void }) {
  const settings = useProjectStore((state) => state.project.animation.overlaySpectral); const audio = useProjectStore((state) => state.project.audio); const setCanvasFormat = useProjectStore((state) => state.setCanvasFormat);
  const chooseRatio = (ratio: "9:16" | "16:9" | "1:1" | "4:5") => ratio === "9:16" || ratio === "16:9" ? onAspectRatio(ratio) : setCanvasFormat({ aspectRatio: ratio });
  return <SoundInspectorAccordion className="panel inspector overlay-spectral-inspector" aria-label="Inspector Overlay Spectral"><div className="panel-heading"><strong>Overlay Spectral</strong><span className="type-badge">48 bande reali</span></div><section><h2>Formato</h2><div className="segmented">{(["9:16", "16:9", "1:1", "4:5"] as const).map((ratio) => <button type="button" key={ratio} className={aspectRatio === ratio ? "active" : ""} aria-pressed={aspectRatio === ratio} onClick={() => chooseRatio(ratio)}>{ratio}</button>)}</div></section><section><h2>Stato</h2><p className="muted">Preset: {overlaySpectralPreset(settings.presetId).name}</p><p className="muted">Sfondo: {settings.backgroundImageUrl ? settings.backgroundMediaType === "video" ? "video" : "immagine" : "gradiente palette"}</p><p className="muted">Audio: {audio.durationSeconds > 0 ? `${audio.durationSeconds.toFixed(2)} s` : "non caricato"}</p><p className="muted">Anteprima ed export campionano la stessa analisi FFT al tempo esatto del fotogramma.</p></section></SoundInspectorAccordion>;
}
