import { useEffect, useRef } from "react";
import type { EnergyFrame } from "@rbs/audio-analysis";
import type { OverlaySpectralSettings, RhythmBallProject } from "@rbs/project-schema";
import { fitSongPlayerPreviewFrame } from "../services/song-player-preview-size";
import { OverlaySpectralRenderer } from "../services/overlay-spectral-renderer";

export function OverlaySpectralPreview({ settings, energyFrames, currentTime, playing, getPlaybackTime, aspectRatio, customWidth, customHeight, onRendererReady }: { settings: OverlaySpectralSettings; energyFrames: readonly EnergyFrame[]; currentTime: number; playing: boolean; getPlaybackTime: () => number; aspectRatio: RhythmBallProject["canvas"]["aspectRatio"]; customWidth: number; customHeight: number; onRendererReady?: (renderer: OverlaySpectralRenderer | null) => void }) {
  const hostRef = useRef<HTMLDivElement>(null); const frameRef = useRef<HTMLDivElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null); const rendererRef = useRef<OverlaySpectralRenderer | null>(null); const callbackRef = useRef(onRendererReady); const playbackClockRef = useRef(getPlaybackTime); const currentTimeRef = useRef(currentTime); const formatRef = useRef({ aspectRatio, customWidth, customHeight }); const resizeRef = useRef<() => void>(() => undefined); callbackRef.current = onRendererReady; playbackClockRef.current = getPlaybackTime; currentTimeRef.current = currentTime; formatRef.current = { aspectRatio, customWidth, customHeight };
  useEffect(() => { const host = hostRef.current; const frame = frameRef.current; const canvas = canvasRef.current; if (!host || !frame || !canvas) return; const renderer = new OverlaySpectralRenderer(canvas); rendererRef.current = renderer; const resize = () => { const format = formatRef.current; const fitted = fitSongPlayerPreviewFrame(host.clientWidth, host.clientHeight, format.aspectRatio, format.customWidth, format.customHeight, window.devicePixelRatio || 1); frame.style.width = `${fitted.cssWidth}px`; frame.style.height = `${fitted.cssHeight}px`; frame.style.aspectRatio = `${fitted.sourceWidth} / ${fitted.sourceHeight}`; renderer.setExportSize(fitted.pixelWidth, fitted.pixelHeight); renderer.renderNow(); }; resizeRef.current = resize; resize(); const observer = typeof ResizeObserver === "undefined" ? null : new ResizeObserver(resize); observer?.observe(host); window.addEventListener("resize", resize); callbackRef.current?.(renderer); return () => { observer?.disconnect(); window.removeEventListener("resize", resize); resizeRef.current = () => undefined; callbackRef.current?.(null); renderer.dispose(); rendererRef.current = null; }; }, []);
  useEffect(() => { resizeRef.current(); }, [aspectRatio, customHeight, customWidth]); useEffect(() => { const renderer = rendererRef.current; if (!renderer) return; renderer.setExternalBackground(settings.backgroundMediaType === "video" && Boolean(settings.backgroundImageUrl)); renderer.update({ settings, energyFrames, timeSeconds: currentTime }); }, [currentTime, energyFrames, settings]);
  useEffect(() => { rendererRef.current?.setPreviewPlaying(playing, playbackClockRef.current()); }, [playing]);
  useEffect(() => { if (!playing) return; let frame = 0; const draw = () => { const time = playbackClockRef.current(); rendererRef.current?.renderNow(Number.isFinite(time) ? Math.max(0, time) : currentTimeRef.current); frame = window.requestAnimationFrame(draw); }; frame = window.requestAnimationFrame(draw); return () => window.cancelAnimationFrame(frame); }, [playing]);
  return <div ref={hostRef} className="overlay-spectral-preview"><div ref={frameRef} className="overlay-spectral-preview-frame" data-aspect-ratio={aspectRatio}><canvas ref={canvasRef} aria-label="Anteprima Overlay Spectral" /></div></div>;
}
