import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { createProject } from "@rbs/project-schema";
const { start, loadPath, importLocal, extractPalette, releaseAudio, analyzeAudio, browserMatch } = vi.hoisted(() => ({ start: vi.fn(), loadPath: vi.fn(), importLocal: vi.fn(), extractPalette: vi.fn(), releaseAudio: vi.fn((audio: { url?: string } | null) => { if (audio?.url?.startsWith("blob:")) URL.revokeObjectURL(audio.url); }), analyzeAudio: vi.fn(), browserMatch: vi.fn() }));
vi.mock("../services/audio-import", () => ({ importFullTrackLocal: importLocal, loadAudioFromPath: loadPath, releaseImportedAudio: releaseAudio }));
vi.mock("../services/image-palette", () => ({ extractPaletteFromImage: extractPalette }));
vi.mock("../services/song-player-analysis", () => ({ analyzeSongPlayerAudio: analyzeAudio }));
vi.mock("../services/song-player-browser-audio", () => ({ matchSongPlayerInBrowser: browserMatch }));
vi.mock("../services/song-player-native", () => ({
  getSongPlayerCapabilities: vi.fn().mockResolvedValue({ desktop: true, importFullTrack: true, analysis: true, matching: true, download: true, reasons: [] }),
  startSongPlayerJob: start, getSongPlayerJob: vi.fn(), cancelSongPlayerJob: vi.fn().mockResolvedValue(undefined), subscribeSongPlayerJob: vi.fn(() => vi.fn()),
  isSongPlayerJobTerminal: (status: string) => ["completed", "succeeded", "failed", "cancelled"].includes(status), hasActiveSongPlayerNativeJob: () => false, subscribeSongPlayerNativeActivity: vi.fn(() => vi.fn()), decodeSongPlayerTerminalResult: (kind: string) => kind === "download" ? { kind: "download", path: "/download.wav", sourceUrl: "https://www.youtube.com/watch?v=canonical", videoId: null, title: null } : { kind: "match", status: "matched", offsetMs: 0, confidence: 1, candidates: [] }
}));
import { SongPlayerPanel } from "./SongPlayerPanel";
import { useProjectStore } from "../store/project-store";
import { useAudioStore } from "../store/audio-store";
import { useSongPlayerJobStore } from "../store/song-player-job-store";

describe("SongPlayerPanel", () => {
  beforeEach(() => { const analysis = { sourceHash: "a".repeat(64), durationSeconds: 10, chromaHopSeconds: 1, chroma: new Float32Array(120), fingerprintVersion: "v1", spectrogram: { version: 1, sourceHash: "a".repeat(64), sampleRate: 1, fftSize: 1024, hopSize: 512, bands: 96, frameCount: 10, durationSeconds: 10, minDb: -80, maxDb: 0, data: new ArrayBuffer(960) } }; Object.defineProperty(URL, "revokeObjectURL", { configurable: true, value: vi.fn() }); useProjectStore.getState().setProject(createProject(), null); useAudioStore.getState().reset(); useSongPlayerJobStore.getState().dispose(); useSongPlayerJobStore.getState().replaceProject(useProjectStore.getState().project.project.id); start.mockReset().mockRejectedValue(new Error("worker occupato")); loadPath.mockReset(); importLocal.mockReset().mockResolvedValue(null); extractPalette.mockReset().mockResolvedValue([]); releaseAudio.mockClear(); analyzeAudio.mockReset().mockResolvedValue(analysis); browserMatch.mockReset().mockResolvedValue({ kind: "match", status: "matched", offsetMs: 2500, confidence: .9, candidates: [{ offsetMs: 2500, score: .9 }] }); });
  afterEach(() => { cleanup(); useSongPlayerJobStore.getState().dispose(); });
  it("espone separatamente spezzone clip e canzone completa", () => { const importFragment = vi.fn().mockResolvedValue(undefined); render(<SongPlayerPanel onImportFragment={importFragment} />); fireEvent.click(screen.getByRole("button", { name: "Carica spezzone clip" })); expect(importFragment).toHaveBeenCalledOnce(); expect(screen.getByRole("button", { name: "Carica canzone completa" })).toBeEnabled(); expect(screen.getByText(/Questo è l’audio che viene riprodotto/)).toBeInTheDocument(); });
  it("esegue il matching automatico locale senza avviare il worker desktop", async () => { const project = createProject(); project.audio = { sourcePath: "clip.wav", storage: "external", hash: "a".repeat(64), durationSeconds: 10, sampleRate: 44_100, channels: 2, globalOffsetMs: 0 }; useProjectStore.getState().setProject(project, null); const fragmentAudio = { metadata: { path: "clip.wav", fileName: "clip.wav", hash: project.audio.hash, durationSeconds: 10, sampleRate: 44_100, channels: 2, codec: "wav", fileSize: 10 }, waveform: [0], url: "blob:clip" }; const fullTrackAudio = { metadata: { ...fragmentAudio.metadata, path: "song.wav", fileName: "song.wav", hash: "b".repeat(64), durationSeconds: 60 }, waveform: [0], url: "blob:song" }; useProjectStore.getState().registerSongPlayerFullTrack({ id: "full", kind: "fullTrack", source: "localImport", sourcePath: fullTrackAudio.metadata.path, fileName: fullTrackAudio.metadata.fileName, mimeType: fullTrackAudio.metadata.codec, hash: fullTrackAudio.metadata.hash, durationSeconds: fullTrackAudio.metadata.durationSeconds, sampleRate: fullTrackAudio.metadata.sampleRate, channels: fullTrackAudio.metadata.channels, fileSize: fullTrackAudio.metadata.fileSize, provider: { sourceUrl: null, videoId: null, title: null } }); useAudioStore.setState({ imported: fragmentAudio, fullTrack: fullTrackAudio }); render(<SongPlayerPanel />); await waitFor(() => expect(screen.getByRole("button", { name: "Riconosci posizione automaticamente" })).toBeEnabled()); fireEvent.click(screen.getByRole("button", { name: "Riconosci posizione automaticamente" })); await waitFor(() => expect(useProjectStore.getState().project.animation.songPlayer.match).toMatchObject({ state: "matched", selectedOffsetMs: 2500, confidence: .9 })); expect(analyzeAudio).toHaveBeenCalledTimes(2); expect(browserMatch).toHaveBeenCalledOnce(); expect(start).not.toHaveBeenCalled(); });
  it("catches native begin errors instead of leaking a rejected promise", async () => { render(<SongPlayerPanel />); fireEvent.change(screen.getByPlaceholderText("https://youtu.be/..."), { target: { value: "https://youtu.be/example" } }); fireEvent.click(screen.getByLabelText(/Confermo/)); await waitFor(() => expect(screen.getByRole("button", { name: "Scarica canzone completa" })).toBeEnabled()); fireEvent.click(screen.getByRole("button", { name: "Scarica canzone completa" })); expect(await screen.findByRole("alert")).toHaveTextContent("worker occupato"); });
  it("discards a downloaded blob if project ownership changes during decode", async () => { let resolve!: (value: unknown) => void; loadPath.mockReturnValue(new Promise((done) => { resolve = done; })); const owner = useProjectStore.getState().project.project.id; useSongPlayerJobStore.setState({ projectId: owner, activeJobId: "download-1", jobs: { "download-1": { jobId: "download-1", kind: "download", status: "completed", result: { path: "/download.wav" }, owner: { projectId: owner } } } }); const revoke = vi.fn(); Object.defineProperty(URL, "revokeObjectURL", { configurable: true, value: revoke }); render(<SongPlayerPanel />); await waitFor(() => expect(loadPath).toHaveBeenCalled()); const next = createProject(); next.project.id = "project-next"; useProjectStore.getState().setProject(next, null); resolve({ metadata: { path: "/download.wav", fileName: "download.wav", hash: "a".repeat(64), durationSeconds: 30, sampleRate: 44100, channels: 2, codec: "wav", fileSize: 10 }, waveform: [0], url: "blob:stale" }); await waitFor(() => expect(revoke).toHaveBeenCalledWith("blob:stale")); expect(useAudioStore.getState().fullTrack).toBeNull(); });
  it("persists match cancellation instead of leaving the project in running", async () => { const project = createProject(); const fragmentHash = "a".repeat(64); const fullTrackHash = "b".repeat(64); project.audio = { sourcePath: "/fragment.wav", storage: "external", hash: fragmentHash, durationSeconds: 10, sampleRate: 44100, channels: 2, globalOffsetMs: 0 }; project.animation.songPlayer.assets = [{ id: "full", kind: "fullTrack", source: "localImport", sourcePath: "/full.wav", fileName: "full.wav", mimeType: "wav", hash: fullTrackHash, durationSeconds: 30, sampleRate: 44100, channels: 2, fileSize: 10, provider: { sourceUrl: null, videoId: null, title: null } }]; project.animation.songPlayer.fullTrackAssetId = "full"; project.animation.songPlayer.match = { ...project.animation.songPlayer.match, state: "running", fragmentHash, fullTrackHash }; useProjectStore.getState().setProject(project, null); useAudioStore.getState().setFullTrack({ metadata: { path: "/full.wav", fileName: "full.wav", hash: fullTrackHash, durationSeconds: 30, sampleRate: 44100, channels: 2, codec: "wav", fileSize: 10 }, waveform: [0], url: "data:audio/wav;base64,AA==" }); useSongPlayerJobStore.setState({ projectId: project.project.id, activeJobId: "match-1", jobs: { "match-1": { jobId: "match-1", kind: "match", status: "cancelled", result: null, owner: { projectId: project.project.id, fragmentHash, fullTrackHash } } } }); render(<SongPlayerPanel />); await waitFor(() => expect(useProjectStore.getState().project.animation.songPlayer.match.state).toBe("idle")); });
  it("lets only the latest local full-track import commit within one project", async () => { let resolveFirst!: (value: unknown) => void; let resolveSecond!: (value: unknown) => void; importLocal.mockReturnValueOnce(new Promise((resolve) => { resolveFirst = resolve; })).mockReturnValueOnce(new Promise((resolve) => { resolveSecond = resolve; })); const older = { metadata: { path: "/older.wav", fileName: "older.wav", hash: "1".repeat(64), durationSeconds: 30, sampleRate: 44100, channels: 2, codec: "wav", fileSize: 10 }, waveform: [0], url: "blob:older" }; const newer = { metadata: { ...older.metadata, path: "/newer.wav", fileName: "newer.wav", hash: "2".repeat(64) }, waveform: [0], url: "blob:newer" }; render(<SongPlayerPanel />); const button = screen.getByRole("button", { name: "Carica canzone completa" }); fireEvent.click(button); fireEvent.click(button); resolveSecond(newer); await waitFor(() => expect(useAudioStore.getState().fullTrack?.metadata.fileName).toBe("newer.wav")); resolveFirst(older); await waitFor(() => expect(releaseAudio).toHaveBeenCalledWith(older)); expect(useAudioStore.getState().fullTrack?.metadata.fileName).toBe("newer.wav"); });
  it("invalidates download post-processing when a newer local import starts", async () => { let resolveDownload!: (value: unknown) => void; loadPath.mockReturnValueOnce(new Promise((resolve) => { resolveDownload = resolve; })); const local = { metadata: { path: "/local.wav", fileName: "local.wav", hash: "3".repeat(64), durationSeconds: 30, sampleRate: 44100, channels: 2, codec: "wav", fileSize: 10 }, waveform: [0], url: "blob:local" }; const staleDownload = { metadata: { ...local.metadata, path: "/download.wav", fileName: "download.wav", hash: "4".repeat(64) }, waveform: [0], url: "blob:download" }; importLocal.mockResolvedValueOnce(local); start.mockResolvedValueOnce({ jobId: "download-1", kind: "download", status: "completed", result: { path: "/download.wav", youtubeUrl: "https://www.youtube.com/watch?v=canonical" } }); render(<SongPlayerPanel />); fireEvent.change(screen.getByPlaceholderText("https://youtu.be/..."), { target: { value: "https://youtu.be/input" } }); fireEvent.click(screen.getByLabelText(/Confermo/)); await waitFor(() => expect(screen.getByRole("button", { name: "Scarica canzone completa" })).toBeEnabled()); fireEvent.click(screen.getByRole("button", { name: "Scarica canzone completa" })); await waitFor(() => expect(loadPath).toHaveBeenCalledWith("/download.wav")); fireEvent.click(screen.getByRole("button", { name: "Carica canzone completa" })); await waitFor(() => expect(useAudioStore.getState().fullTrack?.metadata.fileName).toBe("local.wav")); resolveDownload(staleDownload); await waitFor(() => expect(releaseAudio).toHaveBeenCalledWith(staleDownload)); expect(useAudioStore.getState().fullTrack?.metadata.fileName).toBe("local.wav"); });
  it("refreshes extracted colors for each cover while manual colors disable auto palette", async () => { extractPalette.mockResolvedValueOnce(["#111111", "#222222", "#333333"]).mockResolvedValueOnce(["#444444", "#555555", "#666666"]).mockResolvedValueOnce(["#777777", "#888888", "#999999"]); render(<SongPlayerPanel />); const coverInput = screen.getByLabelText("Cover"); fireEvent.change(coverInput, { target: { files: [new File(["first"], "first.png", { type: "image/png" })] } }); await waitFor(() => expect(useProjectStore.getState().project.animation.songPlayer.palette).toEqual(["#111111", "#222222", "#333333"])); expect(useProjectStore.getState().project.animation.songPlayer.autoPalette).toBe(true); fireEvent.change(screen.getByLabelText("Colore 1"), { target: { value: "#abcdef" } }); expect(useProjectStore.getState().project.animation.songPlayer).toMatchObject({ palette: ["#abcdef", "#222222", "#333333"], autoPalette: false }); fireEvent.click(screen.getByLabelText("Palette automatica")); await waitFor(() => expect(useProjectStore.getState().project.animation.songPlayer.palette).toEqual(["#444444", "#555555", "#666666"])); fireEvent.change(coverInput, { target: { files: [new File(["second"], "second.png", { type: "image/png" })] } }); await waitFor(() => expect(useProjectStore.getState().project.animation.songPlayer.palette).toEqual(["#777777", "#888888", "#999999"])); expect(useProjectStore.getState().project.animation.songPlayer.autoPalette).toBe(true); });
  it("keeps bar and spectrogram colors linked until the user overrides each group", () => { render(<SongPlayerPanel />); expect(screen.getByLabelText("Colori barre dalla palette")).toBeChecked(); expect(screen.getByLabelText("Colori spettrogramma dalla palette")).toBeChecked(); fireEvent.change(screen.getByLabelText("Barre colore 2"), { target: { value: "#123456" } }); fireEvent.change(screen.getByLabelText("Spettrogramma colore 3"), { target: { value: "#abcdef" } }); expect(useProjectStore.getState().project.animation.songPlayer).toMatchObject({ spectrumPaletteMode: "manual", spectrumPalette: ["#63f0d1", "#123456", "#ff4f9a"], spectrogramPaletteMode: "manual", spectrogramPalette: ["#63f0d1", "#7657ff", "#abcdef"] }); fireEvent.click(screen.getByLabelText("Colori spettrogramma dalla palette")); expect(useProjectStore.getState().project.animation.songPlayer).toMatchObject({ spectrogramPaletteMode: "auto", spectrogramPalette: ["#63f0d1", "#7657ff", "#ff4f9a"] }); expect(useProjectStore.getState().project.animation.songPlayer.spectrumPaletteMode).toBe("manual"); });
});
