import { useEffect, useState, type ChangeEvent } from "react";
import { generateSubtitles, llmModelOptions, reviseSubtitlesWithAgentInstruction, reviewSubtitles, subtitleSrt, subtitleTranscriptJson, whisperModelOptions, type SmartSubtitleAgentTarget, type WhisperTranscriptDocument } from "../services/subtitle-generation";
import { subtitleFontOptions } from "../services/subtitle-fonts";
import { createSavedSubtitleTrack, exportSubtitleLibrary, importSubtitleLibrary, instantiateSubtitleTrack, loadSubtitleLibrary, persistSubtitleLibrary, type SubtitleTrackPlacement } from "../services/subtitle-library";
import { useProjectStore } from "../store/project-store";
import { useSmartSubtitleGeneration } from "../hooks/use-smart-subtitle-generation";
import { SmartSubtitleGenerationModal } from "./SmartSubtitleGenerationModal";
import { warmLocalTextGenerator } from "../services/local-model-runtime";

function downloadText(name: string, text: string, type: string): void { const blob = new Blob([text], { type }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 10_000); }

export function SubtitlePanel({ audioUrl, duration, currentTime }: { audioUrl: string | null; duration: number; currentTime: number }) {
  const subtitles = useProjectStore((state) => state.project.subtitles); const projectName = useProjectStore((state) => state.project.project.name); const animationModeId = useProjectStore((state) => state.project.animation.modeId); const update = useProjectStore((state) => state.updateSubtitles); const addCue = useProjectStore((state) => state.addSubtitleCue); const setCues = useProjectStore((state) => state.setSubtitleCues); const updateCue = useProjectStore((state) => state.updateSubtitleCue); const deleteCue = useProjectStore((state) => state.deleteSubtitleCue); const splitCue = useProjectStore((state) => state.splitSubtitleCue);
  const [running, setRunning] = useState(false); const [reviewing, setReviewing] = useState(false); const [status, setStatus] = useState("I modelli vengono scaricati una sola volta al primo utilizzo e poi letti dalla cache locale."); const [whisperJson, setWhisperJson] = useState<WhisperTranscriptDocument | null>(null);
  const smartGeneration = useSmartSubtitleGeneration();
  const [library, setLibrary] = useState(loadSubtitleLibrary); const [libraryName, setLibraryName] = useState(projectName); const [selectedTrackId, setSelectedTrackId] = useState(""); const [placement, setPlacement] = useState<SubtitleTrackPlacement>("replace"); const [applyStyle, setApplyStyle] = useState(true);
  const segmentation = { preferredWords: subtitles.maxWordsPerPhrase, maxCueDuration: subtitles.maxCueDuration, maxCharsPerLine: subtitles.maxCharsPerLine, maxReadingSpeed: subtitles.maxReadingSpeed };
  useEffect(() => {
    if (!audioUrl || !subtitles.llmEnabled || !subtitles.sourceLyrics.trim()) return;
    let active = true;
    setStatus("Preparazione anticipata della redazione LLM locale…");
    void warmLocalTextGenerator(subtitles.llmModel, (message) => { if (active) setStatus(`LLM · ${message}`); }).then((ready) => {
      if (active) setStatus(ready ? "Redazione LLM locale pronta · la generazione non dovrà attendere il modello." : "LLM non disponibile · resteranno attivi montaggio e controlli deterministici.");
    });
    return () => { active = false; };
  }, [audioUrl, subtitles.llmEnabled, subtitles.llmModel, subtitles.sourceLyrics]);
  const run = async () => { if (!audioUrl || duration <= 0 || running) return; setRunning(true); setWhisperJson(null); smartGeneration.begin(); try { const cues = await generateSubtitles(audioUrl, duration, { lyrics: subtitles.sourceLyrics, maxWords: subtitles.maxWordsPerPhrase, maxCueDuration: subtitles.maxCueDuration, maxCharsPerLine: subtitles.maxCharsPerLine, maxReadingSpeed: subtitles.maxReadingSpeed, language: subtitles.language, whisperModel: subtitles.whisperModel, llmEnabled: subtitles.llmEnabled, llmModel: subtitles.llmModel, llmPasses: subtitles.llmPasses, onWhisperJson: setWhisperJson, onEvent: smartGeneration.receive }, setStatus); setCues(cues); update({ enabled: true }); setStatus(`${cues.length} frasi create · JSON parole/frasi pronto · ${cues.filter((cue) => cue.verified).length} verificate`); smartGeneration.finish(cues.length, cues.filter((cue) => cue.verified).length); } catch (error) { const message = error instanceof Error ? error.message : String(error); setStatus(message); smartGeneration.fail(message); } finally { setRunning(false); } };
  const review = async () => { if (!subtitles.cues.length || reviewing) return; setReviewing(true); smartGeneration.begin("Revisione dei sottotitoli esistenti con la redazione locale…"); try { const cues = await reviewSubtitles(subtitles.cues, subtitles.sourceLyrics, subtitles.llmModel, subtitles.llmPasses, setStatus, segmentation, undefined, smartGeneration.receive); setCues(cues); setStatus(`Revisione completata · ${cues.filter((cue) => cue.verified).length}/${cues.length} frasi confermate`); smartGeneration.finish(cues.length, cues.filter((cue) => cue.verified).length); } catch (error) { const message = error instanceof Error ? error.message : String(error); setStatus(message); smartGeneration.fail(message); } finally { setReviewing(false); } };
  const instructAgents = async (message: string, target: SmartSubtitleAgentTarget) => {
    const result = await reviseSubtitlesWithAgentInstruction(subtitles.cues, message, target, subtitles.llmModel, subtitles.sourceLyrics, segmentation, setStatus, smartGeneration.receive, {
      ...(whisperJson ? { exactWordTimeline: whisperJson.words } : {}),
      audioUrl,
      durationSeconds: duration,
      whisperModel: subtitles.whisperModel,
      language: subtitles.language
    });
    setCues(result.cues); update({ enabled: true });
    setStatus(result.summary ?? `Intervento agenti completato · ${result.changedCount} modifiche validate · ${result.cues.length} blocchi in timeline.`);
    return { cueCount: result.cues.length, changedCount: result.changedCount };
  };
  const exportSrt = () => downloadText("sottotitoli.srt", subtitleSrt(subtitles.cues), "application/x-subrip;charset=utf-8");
  const saveTrack = () => { if (!subtitles.cues.length) return; try { const track = createSavedSubtitleTrack(libraryName, subtitles, duration); const next = [track, ...library]; persistSubtitleLibrary(next); setLibrary(next); setSelectedTrackId(track.id); setStatus(`“${track.name}” salvata nella libreria locale con ${track.cues.length} blocchi e il relativo stile.`); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); } };
  const applyTrack = () => { const track = library.find((item) => item.id === selectedTrackId); if (!track || duration <= 0) return; const instantiated = instantiateSubtitleTrack(track, duration, placement, currentTime); const cues = placement === "insert" ? [...subtitles.cues, ...instantiated].sort((left, right) => left.startSeconds - right.startSeconds) : instantiated; if (applyStyle) update({ ...track.style, enabled: true, autoPalette: false }); setCues(cues); setStatus(placement === "insert" ? `${instantiated.length} blocchi di “${track.name}” inseriti dal playhead.` : `Traccia “${track.name}” applicata con ${instantiated.length} blocchi.`); };
  const removeTrack = () => { const track = library.find((item) => item.id === selectedTrackId); if (!track) return; try { const next = library.filter((item) => item.id !== track.id); persistSubtitleLibrary(next); setLibrary(next); setSelectedTrackId(next[0]?.id ?? ""); setStatus(`“${track.name}” rimossa dalla libreria locale.`); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); } };
  const importTracks = async (change: ChangeEvent<HTMLInputElement>) => { const file = change.target.files?.[0]; change.target.value = ""; if (!file) return; try { const imported = importSubtitleLibrary(await file.text()); const next = [...imported, ...library]; persistSubtitleLibrary(next); setLibrary(next); setSelectedTrackId(imported[0]?.id ?? ""); setStatus(`${imported.length} tracce importate nella libreria locale.`); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); } };
  return <section className="subtitle-settings">
    <h2>Sottotitoli globali</h2><label className="teddy-dance-toggle"><span>Mostra nel video</span><input type="checkbox" checked={subtitles.enabled} onChange={(event) => update({ enabled: event.target.checked })} /></label>
    <div className="subtitle-block-tools">
      <h3>Blocchi manuali e libreria</h3>
      <button className="add-subtitle-block" disabled={duration <= 0} onClick={() => addCue(currentTime)}>+ Inserisci blocco al playhead ({currentTime.toFixed(2)} s)</button>
      <p>Doppio clic sulla corsia Sottotitoli per inserire un blocco nel punto desiderato.</p>
      <label>Nome traccia<input aria-label="Nome traccia sottotitoli" value={libraryName} onChange={(event) => setLibraryName(event.target.value)} /></label>
      <button disabled={!subtitles.cues.length} onClick={saveTrack}>Salva blocchi e stile nella libreria</button>
      <label>Traccia salvata<select aria-label="Traccia sottotitoli salvata" value={selectedTrackId} onChange={(event) => setSelectedTrackId(event.target.value)}><option value="">Seleziona dalla libreria…</option>{library.map((track) => <option key={track.id} value={track.id}>{track.name} · {track.cues.length} {track.cues.length === 1 ? "blocco" : "blocchi"}</option>)}</select></label>
      <label>Modalità di applicazione<select aria-label="Modalità applicazione sottotitoli" value={placement} onChange={(event) => setPlacement(event.target.value as SubtitleTrackPlacement)}><option value="replace">Sostituisci · tempi originali</option><option value="stretch">Sostituisci · adatta alla durata</option><option value="insert">Inserisci dal playhead</option></select></label>
      <label className="teddy-dance-toggle"><span>Applica anche animazione e stile</span><input type="checkbox" checked={applyStyle} onChange={(event) => setApplyStyle(event.target.checked)} /></label>
      <div className="subtitle-library-actions"><button disabled={!selectedTrackId || duration <= 0} onClick={applyTrack}>Usa nel progetto</button><button className="danger" disabled={!selectedTrackId} onClick={removeTrack}>Rimuovi</button></div>
      <div className="subtitle-library-actions"><button disabled={!library.length} onClick={() => downloadText("dynamic-sound-subtitles.json", exportSubtitleLibrary(library), "application/json;charset=utf-8")}>Esporta libreria</button><label className="subtitle-library-import">Importa libreria<input aria-label="Importa libreria sottotitoli" type="file" accept=".json,application/json" onChange={(event) => void importTracks(event)} /></label></div>
      <small>{library.length} tracce salvate in locale · disponibili in tutte le modalità e nei nuovi progetti.</small>
    </div>
    {animationModeId !== "pixelsSub" ? <>{animationModeId === "coverSphere" || animationModeId === "stereoUnfold" || animationModeId === "walkingCube" || animationModeId === "pixelArt" ? <label className="teddy-dance-toggle"><span>Colori automatici dalla cover</span><input type="checkbox" checked={subtitles.autoPalette} onChange={(event) => update({ autoPalette: event.target.checked })} /></label> : null}
    <label>Animazione<select value={subtitles.animation} onChange={(event) => update({ animation: event.target.value as typeof subtitles.animation })}><option value="ledFall">LED in caduta</option><option value="cinematicFade">Dissolvenza cinematografica</option><option value="wordPop">Pop elastico</option><option value="karaokeGlow">Karaoke glow</option><option value="slideUp">Scorrimento dal basso</option></select></label></> : <p className="pixels-sub-workflow-note">In PixelsSub stile, colore e animazione delle frasi sono controllati dal campo pixel a tre colori. Qui gestisci trascrizione, timing, blocchi e revisione.</p>}
    <div className="local-model-panel"><h3>Trascrizione Whisper locale</h3><label>Modello Whisper<select aria-label="Modello Whisper locale" value={subtitles.whisperModel} onChange={(event) => update({ whisperModel: event.target.value as typeof subtitles.whisperModel })}>{whisperModelOptions.map((model) => <option key={model.id} value={model.id}>{model.label} · {model.localSize}</option>)}</select></label><p>{whisperModelOptions.find((model) => model.id === subtitles.whisperModel)?.detail}</p><span className="model-installed">● Download al primo utilizzo · poi cache locale · Q4</span></div>
    <label>Testo completo della canzone<textarea rows={6} value={subtitles.sourceLyrics} onChange={(event) => update({ sourceLyrics: event.target.value })} placeholder={"Incolla anche il testo Suno con tag [Verse], [Chorus] e [Instrumental]: verranno ripuliti prima dell’allineamento."} /></label>
    <label>Lingua Whisper<select aria-label="Lingua Whisper locale" value={subtitles.language} onChange={(event) => update({ language: event.target.value })}><option value="auto">Rilevamento automatico</option><option value="it">Italiano</option><option value="en">Inglese</option><option value="es">Spagnolo</option><option value="fr">Francese</option><option value="de">Tedesco</option></select></label>
    <label>Lunghezza indicativa: circa {subtitles.maxWordsPerPhrase} parole<input type="range" min="2" max="20" value={subtitles.maxWordsPerPhrase} onChange={(event) => update({ maxWordsPerPhrase: Number(event.target.value) })} /></label>
    <label>Durata massima reale: {subtitles.maxCueDuration.toFixed(1)} s<input aria-label="Durata massima sottotitolo" type="range" min="1.5" max="7" step=".1" value={subtitles.maxCueDuration} onChange={(event) => update({ maxCueDuration: Number(event.target.value) })} /></label>
    <label>Caratteri per riga: {subtitles.maxCharsPerLine}<input aria-label="Caratteri massimi per riga" type="range" min="18" max="60" step="1" value={subtitles.maxCharsPerLine} onChange={(event) => update({ maxCharsPerLine: Number(event.target.value) })} /></label>
    <label>Velocità di lettura: max {subtitles.maxReadingSpeed.toFixed(0)} caratteri/s<input aria-label="Velocità massima di lettura" type="range" min="10" max="28" step=".5" value={subtitles.maxReadingSpeed} onChange={(event) => update({ maxReadingSpeed: Number(event.target.value) })} /></label>
    <p className="muted phrase-segmentation-note">Le parole sono un obiettivo morbido. Pause vocali e punteggiatura decidono i tagli, mentre durata, due righe e velocità di lettura restano vincoli di qualità.</p>
    {animationModeId !== "pixelsSub" ? <><label>Font<select aria-label="Font sottotitoli" value={subtitles.fontFamily} onChange={(event) => update({ fontFamily: event.target.value })}>{subtitleFontOptions.some((font) => font.value === subtitles.fontFamily) ? null : <option value={subtitles.fontFamily}>{subtitles.fontFamily} · font del progetto</option>}{subtitleFontOptions.map((font) => <option key={font.value} value={font.value}>{font.label}</option>)}</select></label><label>Dimensione: {subtitles.fontSize}px<input type="range" min="18" max="180" value={subtitles.fontSize} onChange={(event) => update({ fontSize: Number(event.target.value) })} /></label>
    <div className="teddy-palette"><label>LED<input type="color" value={subtitles.color} onChange={(event) => update({ color: event.target.value })} /></label><label>Bagliore<input type="color" value={subtitles.glowColor} onChange={(event) => update({ glowColor: event.target.value })} /></label></div>
    <label>Velocità caduta: {subtitles.fallSpeed.toFixed(1)}×<input type="range" min=".2" max="4" step=".1" value={subtitles.fallSpeed} onChange={(event) => update({ fallSpeed: Number(event.target.value) })} /></label></> : null}
    <button className="regenerate-base" disabled={!audioUrl || running || reviewing} onClick={() => void run()}>{running ? "Analisi Whisper locale in corso…" : "Genera con Whisper locale"}</button>
    <div className="local-model-panel llm-review-panel"><h3>Redazione LLM locale multi-agente</h3><label className="teddy-dance-toggle"><span>Ripulisci, allinea e verifica dopo Whisper</span><input type="checkbox" checked={subtitles.llmEnabled} onChange={(event) => update({ llmEnabled: event.target.checked })} /></label><label>Modello<select aria-label="Modello LLM locale" value={subtitles.llmModel} onChange={(event) => update({ llmModel: event.target.value as typeof subtitles.llmModel })}>{llmModelOptions.map((model) => <option key={model.id} value={model.id}>{model.label} · {model.localSize}</option>)}</select></label><label>Passaggi tra agenti: {subtitles.llmPasses}<input type="range" min="1" max="10" step="1" value={subtitles.llmPasses} onChange={(event) => update({ llmPasses: Number(event.target.value) })} /></label><div className="subtitle-agent-flow"><span>Pulizia Suno</span><i>→</i><span>Allineamento</span><i>→</i><span>Pause</span><i>→</i><span>QC</span><i>→</i><span>Coordinatore</span></div><p>{llmModelOptions.find((model) => model.id === subtitles.llmModel)?.detail}. Gli agenti condividono rapporti validati; Whisper e il validatore deterministico mantengono l’autorità sui timestamp.</p>{subtitles.llmEnabled && !subtitles.sourceLyrics.trim() ? <p className="muted">LLM in attesa: incolla il testo completo della canzone per attivare preparazione e confronto multi-agente.</p> : null}<span className="model-installed">● Download al primo utilizzo · poi cache locale · nessuna API</span><button disabled={!subtitles.cues.length || !subtitles.sourceLyrics.trim() || reviewing || running} onClick={() => void review()}>{reviewing ? "Redazione locale in corso…" : "Rimonta, correggi e verifica"}</button><button disabled={!subtitles.llmEnabled || !subtitles.cues.length || reviewing || running} onClick={smartGeneration.reopen}>Parla con gli agenti</button></div>
    <div className="subtitle-library-actions"><button disabled={!subtitles.cues.length} onClick={exportSrt}>Esporta SRT</button><button disabled={!whisperJson} onClick={() => { if (whisperJson) downloadText("whisper-parole-frasi.json", subtitleTranscriptJson(whisperJson), "application/json;charset=utf-8"); }}>Esporta JSON Whisper</button></div><p className="muted">{status}</p>
    {subtitles.cues.length ? <div className="subtitle-cue-editor">{subtitles.cues.map((cue) => <article key={cue.id} className={cue.verified ? "verified" : ""}><header><span>{cue.verified ? "✓ LLM verificato" : "Da verificare"}</span><small>{Math.round(cue.confidence * 100)}%</small></header><input aria-label="Testo sottotitolo" value={cue.text} onChange={(event) => updateCue(cue.id, { text: event.target.value, verified: false })} /><div><input aria-label="Inizio sottotitolo" type="number" min="0" step=".01" value={cue.startSeconds} onChange={(event) => updateCue(cue.id, { startSeconds: Number(event.target.value), verified: false })} /><input aria-label="Fine sottotitolo" type="number" min=".01" step=".01" value={cue.endSeconds} onChange={(event) => updateCue(cue.id, { endSeconds: Number(event.target.value), verified: false })} /><button onClick={() => splitCue(cue.id, (cue.startSeconds + cue.endSeconds) / 2)}>Dividi</button><button onClick={() => deleteCue(cue.id)}>×</button></div></article>)}</div> : null}
    <SmartSubtitleGenerationModal controller={smartGeneration} canInteract={subtitles.llmEnabled && subtitles.cues.length > 0 && !running && !reviewing} interactiveDisabledReason={!subtitles.cues.length ? "Genera o inserisci prima almeno un blocco di sottotitoli." : !subtitles.llmEnabled ? "Abilita la redazione LLM locale per parlare con gli agenti." : "Attendi il completamento dell’operazione in corso."} onAgentInstruction={instructAgents} />
  </section>;
}
