import type { ImportedAudio } from "./audio-import";
import type { CassetteDeskMusicalAnalysis, CassetteDeskPitchFrame } from "./cassette-desk";
import { ensureSongPlayerRuntime, getSongPlayerCapabilities, getSongPlayerRuntimeSetup, isSongPlayerJobTerminal, startSongPlayerJob, waitForSongPlayerJob } from "./song-player-native";
import { separateBrowserCassetteDeskVocals } from "./cassette-desk-vocals-browser";
export interface CassetteDeskVocalSeparation { model:"htdemucs";pitchAlgorithm:"pyin";stemPath:string;notes:CassetteDeskPitchFrame[];musicalAnalysis:CassetteDeskMusicalAnalysis|null;musicalAnalysisError:string|null; }
function decodeMusicalAnalysis(value:unknown):CassetteDeskMusicalAnalysis|null{if(!value||typeof value!=="object")return null;const musical=value as Record<string,unknown>;if(typeof musical.bpm!=="number"||!Number.isFinite(musical.bpm)||musical.bpm<=0||typeof musical.keyRoot!=="number"||!Number.isInteger(musical.keyRoot)||musical.keyRoot<0||musical.keyRoot>11||(musical.keyMode!=="major"&&musical.keyMode!=="minor")||typeof musical.keyConfidence!=="number"||!Number.isFinite(musical.keyConfidence)||musical.keyConfidence<0||musical.keyConfidence>1)return null;return{bpm:musical.bpm,keyRoot:musical.keyRoot,keyMode:musical.keyMode,keyConfidence:musical.keyConfidence};}
export function decodeCassetteDeskVocalResult(value:unknown):CassetteDeskVocalSeparation{const source=value&&typeof value==="object"?value as Record<string,unknown>:null;if(!source||source.kind!=="separateVocals"||source.model!=="htdemucs"||source.pitchAlgorithm!=="pyin"||typeof source.path!=="string"||!Array.isArray(source.pitch))throw new Error("Risultato separazione vocale non valido.");const notes=source.pitch.flatMap(item=>{if(!Array.isArray(item)||item.length!==3)return[];const [time,midi,confidence]=item;return typeof time==="number"&&Number.isFinite(time)&&time>=0&&typeof midi==="number"&&Number.isFinite(midi)&&typeof confidence==="number"&&Number.isFinite(confidence)&&confidence>=0&&confidence<=1?[{timeSeconds:time,midi,confidence}]:[];});const musicalAnalysis=decodeMusicalAnalysis(source.musicalAnalysis);const musicalAnalysisError=typeof source.musicalAnalysisError==="string"?source.musicalAnalysisError:source.musicalAnalysis!==undefined&&!musicalAnalysis?"Analisi musicale non valida.":null;return{model:"htdemucs",pitchAlgorithm:"pyin",stemPath:source.path,notes,musicalAnalysis,musicalAnalysisError};}
const abortError=()=>new DOMException("Operazione annullata","AbortError");
const wait=(milliseconds:number,signal?:AbortSignal)=>new Promise<void>((resolve,reject)=>{if(signal?.aborted)return reject(abortError());const timer=globalThis.setTimeout(()=>{signal?.removeEventListener("abort",abort);resolve();},milliseconds);const abort=()=>{globalThis.clearTimeout(timer);reject(abortError());};signal?.addEventListener("abort",abort,{once:true});});
async function ensureVocalRuntime(signal?:AbortSignal,onProgress?:(progress:number,message:string)=>void){let capabilities=await getSongPlayerCapabilities();if(capabilities.vocalSeparation)return capabilities;if(!capabilities.desktop)return capabilities;let setup=await ensureSongPlayerRuntime();while(setup.status==="installing"||setup.status==="idle"){if(signal?.aborted)throw abortError();onProgress?.(setup.progress/100*.35,`${setup.message} · ${Math.round(setup.progress)}%`);await wait(500,signal);setup=await getSongPlayerRuntimeSetup();}if(setup.status==="failed")throw new Error(setup.error??"Installazione automatica del runtime vocale non riuscita.");capabilities=await getSongPlayerCapabilities();if(!capabilities.vocalSeparation)throw new Error("Il runtime vocale installato non ha superato la verifica finale.");return capabilities;}
export async function separateCassetteDeskVocals(audio:ImportedAudio,signal?:AbortSignal,onProgress?:(progress:number,message:string)=>void):Promise<CassetteDeskVocalSeparation>{const capabilities=await ensureVocalRuntime(signal,onProgress);if(!capabilities.desktop){const result=await separateBrowserCassetteDeskVocals(audio,signal,onProgress);return decodeCassetteDeskVocalResult(result);}if(!audio.metadata.path)throw new Error("Il file locale del brano non è più disponibile: ricaricalo e riprova.");if(signal?.aborted)throw abortError();const started=await startSongPlayerJob({kind:"separateVocals",inputPath:audio.metadata.path});const terminal=isSongPlayerJobTerminal(started.status)?started:await waitForSongPlayerJob(started.jobId,{...(signal?{signal}:{}),onSnapshot:snapshot=>onProgress?.(.35+(snapshot.progress??0)*.65,snapshot.message??"Separazione voce")});if(terminal.status==="failed"||terminal.status==="cancelled"||!terminal.result)throw new Error(typeof terminal.error==="string"?terminal.error:terminal.error?.message??"Separazione vocale fallita.");return decodeCassetteDeskVocalResult(terminal.result);}
