import { describe, expect, it } from "vitest";
import type { AudioAnalysisResult, EnergyFrame } from "@rbs/audio-analysis";
import { buildCassetteDeskAnalysis, cassetteDeskActiveNote, cassetteDeskMechanicalEvents, cassetteDeskSpectrumBars, cassetteDeskTimeline, stabilizeCassetteVocalMidi } from "./cassette-desk";
import { cassetteMechanicalLeadIn } from "./offline-video-exporter";
import { cassetteCaseLidMatrix, cassetteInsertionRotation, cassettePianoKeyIsActive, cassettePianoLayout, cassettePianoNoteLabel, cassetteStereoBayRect, fitCassetteArtwork, readableCassetteTextColor } from "./cassette-desk-renderer";

function frame(timeSeconds:number,band:number):EnergyFrame{const bands48=Array(48).fill(0);bands48[band]=.9;return{timeSeconds,rms:.2,low:.1,mid:.6,high:.1,flux:.2,spectralCentroid:440,spectralFlatness:.04,bands48};}
const analysis=(energy:EnergyFrame[]):AudioAnalysisResult=>({analyzerVersion:"test",durationSeconds:3,sampleRate:48_000,globalBpm:120,bpmConfidence:.9,localTempo:[],beats:[0,.5],downbeats:[0],events:[],energy,onsetEnvelope:[],spectralFlux:[],lowEnergySegments:[]});
describe("Cassette Desk reusable engine",()=>{
  it("keeps music silent until insertion, door close and play press are complete",()=>{expect(cassetteDeskTimeline(2).phase).toBe("inserting");expect(cassetteDeskTimeline(4).phase).toBe("closing");expect(cassetteDeskTimeline(4.5).phase).toBe("pressing");expect(cassetteDeskTimeline(4.8)).toMatchObject({phase:"playing",musicStarted:true,songTimeSeconds:0});expect(cassetteDeskTimeline(6).songTimeSeconds).toBeCloseTo(1.2);});
  it("uses only notes extracted from the separated vocal stem",()=>{const separated=[{timeSeconds:.3,midi:60.2,confidence:.94}];const result=buildCassetteDeskAnalysis(analysis([frame(0,14),frame(.1,14),frame(.2,14),frame(.3,14)]),[0,.4,.8],separated,42);expect(result.bpm).toBe(120);expect(result.keyLabel).toMatch(/major|minor/);expect(result.vocalNotes).toHaveLength(1);expect(cassetteDeskActiveNote(result,.3)).toMatchObject({midi:60,confidence:.94});});
  it("never turns mixed-track spectrum energy into alleged vocal notes",()=>{const result=buildCassetteDeskAnalysis(analysis([frame(0,14),frame(.1,14),frame(.2,14)]),[0,.7,.3]);expect(result.vocalNotes).toEqual([]);expect(cassetteDeskActiveNote(result,.1)).toBeNull();});
  it("synthesizes all mechanical events before the song lead-in",()=>{const events=cassetteDeskMechanicalEvents();expect(events.map(item=>item.kind)).toEqual(["slide","door","play"]);const samples=cassetteMechanicalLeadIn(8_000,2,4.8,events);expect(samples.length).toBe(8_000*2*4.8);expect(samples.some(value=>Math.abs(value)>.001)).toBe(true);});
  it("fits the 3:4 artwork on case and cassette labels without ever deforming it",()=>{const portrait=fitCassetteArtwork(900,1200,{x:0,y:0,width:320,height:180});expect(portrait.width/portrait.height).toBeCloseTo(.75);expect(portrait.height).toBe(180);const cassette=fitCassetteArtwork(900,1200,{x:10,y:20,width:75,height:100});expect(cassette).toEqual({x:10,y:20,width:75,height:100});});
  it("lays out one real octave with the correct two-black/three-black pattern",()=>{const keys=cassettePianoLayout();const whites=keys.filter(key=>key.kind==="white");const blacks=keys.filter(key=>key.kind==="black");expect(whites.map(key=>key.midi)).toEqual([60,62,64,65,67,69,71]);expect(blacks.map(key=>key.midi)).toEqual([61,63,66,68,70]);expect(keys.some(key=>key.midi===65&&key.kind==="white")).toBe(true);expect(keys.some(key=>key.midi===64&&key.kind==="black")).toBe(false);expect(keys.some(key=>key.midi===71&&key.kind==="black")).toBe(false);});
  it("highlights only the note class and deliberately ignores the detected octave",()=>{expect(cassettePianoKeyIsActive(60,36)).toBe(true);expect(cassettePianoKeyIsActive(60,72)).toBe(true);expect(cassettePianoKeyIsActive(61,73)).toBe(true);expect(cassettePianoKeyIsActive(60,61)).toBe(false);expect(cassettePianoKeyIsActive(60,null)).toBe(false);expect(cassettePianoNoteLabel(36)).toBe("DO");expect(cassettePianoNoteLabel(73)).toBe("DO♯");});
  it("validates uncertain out-of-scale vocal detections against the detected key",()=>{expect(stabilizeCassetteVocalMidi(61.3,.5,0,"major",42)).toBe(62);expect(stabilizeCassetteVocalMidi(61,.5,0,"major",42)).toBe(61);expect(stabilizeCassetteVocalMidi(61.3,.91,0,"major",100)).toBe(61);expect(stabilizeCassetteVocalMidi(60.48,.5,11,"major",60)).toBe(61);expect(stabilizeCassetteVocalMidi(64.1,.6,0,"major",42)).toBe(64);});
  it("opens the portrait cassette case around its vertical hinge",()=>{expect(cassetteCaseLidMatrix(0)).toEqual({horizontalScale:1,verticalShear:-0});const half=cassetteCaseLidMatrix(.5);expect(Math.abs(half.horizontalScale)).toBeLessThan(.2);const open=cassetteCaseLidMatrix(1);expect(open.horizontalScale).toBeLessThan(0);expect(Math.abs(open.verticalShear)).toBeLessThan(1e-10);});
  it("keeps the cassette vertical behind the closed portrait cover, then rotates it for the stereo",()=>{expect(cassetteInsertionRotation(0)).toBeCloseTo(Math.PI/2-.075);expect(cassetteInsertionRotation(.5)).toBeGreaterThan(0);expect(cassetteInsertionRotation(1)).toBeCloseTo(0);});
  it("uses real harmonic analysis and exposes half-time without altering the detected notes",()=>{const result=buildCassetteDeskAnalysis(analysis([frame(0,14)]),[],[{timeSeconds:.2,midi:69.1,confidence:.9}],42,{musicalAnalysis:{bpm:123.4,keyRoot:9,keyMode:"major",keyConfidence:.88},halfTime:true});expect(result.bpm).toBeCloseTo(61.7);expect(result.keyLabel).toBe("A major");expect(result.vocalNotes[0]?.midi).toBe(69);});
  it("allows exact manual BPM and key correction after automatic analysis",()=>{const result=buildCassetteDeskAnalysis(analysis([]),[],[],42,{musicalAnalysis:{bpm:127,keyRoot:5,keyMode:"minor",keyConfidence:.7},tempoDetectionMode:"manual",manualBpm:121.5,keyDetectionMode:"manual",manualKeyRoot:9,manualKeyMode:"major"});expect(result.bpm).toBe(121.5);expect(result.keyLabel).toBe("A major");});
  it("reduces the real 48-band analysis to exactly 12 animated display bars",()=>{const result=buildCassetteDeskAnalysis(analysis([frame(0,0),frame(.1,47)]),[],[],42);expect(result.spectrumFrames).toHaveLength(2);expect(cassetteDeskSpectrumBars(result,0)).toHaveLength(12);expect(cassetteDeskSpectrumBars(result,0)[0]).toBeGreaterThan(0);expect(cassetteDeskSpectrumBars(result,.1)[11]).toBeGreaterThan(0);});
  it("chooses guaranteed contrasting text for light and dark palette chips",()=>{expect(readableCassetteTextColor("#050709")).toBe("#ffffff");expect(readableCassetteTextColor("#f4e8c8")).toBe("#08090b");expect(readableCassetteTextColor("invalid")).toBe("#ffffff");});
  it("gives the poster stereo a tall central cassette bay",()=>{const stereo={x:100,y:50,width:600,height:800};const classic=cassetteStereoBayRect("classic",stereo);const poster=cassetteStereoBayRect("poster",stereo);expect(poster.height).toBeGreaterThan(poster.width);expect(poster.width).toBeLessThan(classic.width);expect(poster.x+poster.width/2).toBeCloseTo(stereo.x+stereo.width/2);});
});
