import type { CassetteDeskSettings } from "@rbs/project-schema";
import { cassetteDeskActiveNote, cassetteDeskSpectrumBars, cassetteDeskTimeline, type CassetteDeskAnalysis } from "./cassette-desk";

export interface CassetteDeskRenderInput { settings: CassetteDeskSettings; analysis: CassetteDeskAnalysis | null; timeSeconds: number; songDurationSeconds: number; }
const ease = (value: number) => value * value * (3 - 2 * value);
const rounded = (context: CanvasRenderingContext2D, x: number, y: number, width: number, height: number, radius: number) => { context.beginPath(); context.roundRect(x, y, width, height, radius); };
const resolvedColor = (mode: "auto" | "manual", manual: string, automatic: string) => mode === "manual" ? manual : automatic;
const mixCassetteColor=(color:string,target:string,amount:number)=>{const parse=(value:string)=>{const match=value.match(/^#([\da-f]{6})$/i);return match?[0,2,4].map(offset=>parseInt(match[1]!.slice(offset,offset+2),16)):null;};const source=parse(color),destination=parse(target);if(!source||!destination)return color;return`#${source.map((channel,index)=>Math.round(channel+(destination[index]!-channel)*amount).toString(16).padStart(2,"0")).join("")}`;};
const elide = (context: CanvasRenderingContext2D, text: string, maxWidth: number) => { if (context.measureText(text).width <= maxWidth) return text; let value=text; while(value.length>1&&context.measureText(`${value}…`).width>maxWidth)value=value.slice(0,-1);return `${value}…`; };
export function readableCassetteTextColor(color:string){const match=color.trim().match(/^#([\da-f]{6})$/i);if(!match)return"#ffffff";const value=match[1]!;const channel=(offset:number)=>{const raw=parseInt(value.slice(offset,offset+2),16)/255;return raw<=.04045?raw/12.92:Math.pow((raw+.055)/1.055,2.4);};const luminance=.2126*channel(0)+.7152*channel(2)+.0722*channel(4);return luminance>.38?"#08090b":"#ffffff";}
export function cassetteCaseLidMatrix(openAmount:number){const open=Math.max(0,Math.min(1,openAmount));return{horizontalScale:1-open*1.76,verticalShear:-.12*Math.sin(open*Math.PI)};}
export function cassetteInsertionRotation(insertProgress:number){const progress=Math.max(0,Math.min(1,insertProgress));return(Math.PI/2-.075)*(1-ease(progress));}
export interface CassetteArtworkRect { x: number; y: number; width: number; height: number; }
export function fitCassetteArtwork(sourceWidth:number,sourceHeight:number,box:CassetteArtworkRect):CassetteArtworkRect{if(sourceWidth<=0||sourceHeight<=0||box.width<=0||box.height<=0)return{x:box.x,y:box.y,width:0,height:0};const scale=Math.min(box.width/sourceWidth,box.height/sourceHeight);const width=sourceWidth*scale,height=sourceHeight*scale;return{x:box.x+(box.width-width)/2,y:box.y+(box.height-height)/2,width,height};}
export function cassetteStereoBayRect(style:CassetteDeskSettings["stereoStyle"],stereo:CassetteArtworkRect):CassetteArtworkRect{return style==="poster"?{x:stereo.x+stereo.width*.35,y:stereo.y+stereo.height*.33,width:stereo.width*.3,height:stereo.height*.48}:{x:stereo.x+stereo.width*.29,y:stereo.y+stereo.height*.34,width:stereo.width*.42,height:stereo.height*.43};}
export interface CassettePianoKey { midi:number;kind:"white"|"black";x:number;width:number; }
const whitePitchClasses=new Set([0,2,4,5,7,9,11]);
export function cassettePianoLayout(startMidi=60,endMidi=71):CassettePianoKey[]{const whiteMidis=Array.from({length:Math.max(0,endMidi-startMidi+1)},(_,index)=>startMidi+index).filter(midi=>whitePitchClasses.has((midi%12+12)%12));if(!whiteMidis.length)return[];const whiteWidth=1/whiteMidis.length,blackWidth=whiteWidth*.58;const whites=whiteMidis.map((midi,index)=>({midi,kind:"white" as const,x:index*whiteWidth,width:whiteWidth}));const blacks=Array.from({length:Math.max(0,endMidi-startMidi+1)},(_,index)=>startMidi+index).filter(midi=>!whitePitchClasses.has((midi%12+12)%12)).flatMap(midi=>{const boundary=whiteMidis.filter(whiteMidi=>whiteMidi<midi).length;if(boundary<=0||boundary>=whiteMidis.length)return[];return[{midi,kind:"black" as const,x:boundary*whiteWidth-blackWidth/2,width:blackWidth}];});return[...whites,...blacks];}
export function cassettePianoKeyIsActive(keyMidi:number,activeMidi:number|null|undefined){return activeMidi!==null&&activeMidi!==undefined&&((keyMidi%12+12)%12===((activeMidi%12+12)%12));}
const italianNoteNames=["DO","DO♯","RE","RE♯","MI","FA","FA♯","SOL","SOL♯","LA","LA♯","SI"] as const;
export function cassettePianoNoteLabel(midi:number){return italianNoteNames[(midi%12+12)%12]??"—";}
const drawContainedArtwork=(context:CanvasRenderingContext2D,image:HTMLImageElement|null,box:CassetteArtworkRect,radius:number,backdrop:string)=>{context.fillStyle=backdrop;rounded(context,box.x,box.y,box.width,box.height,radius);context.fill();if(!image?.complete||!image.naturalWidth||!image.naturalHeight)return;context.save();rounded(context,box.x,box.y,box.width,box.height,radius);context.clip();const fitted=fitCassetteArtwork(image.naturalWidth,image.naturalHeight,box);context.drawImage(image,fitted.x,fitted.y,fitted.width,fitted.height);context.restore();};

export class CassetteDeskRenderer {
  readonly canvas: HTMLCanvasElement; private context: CanvasRenderingContext2D | null; private input: CassetteDeskRenderInput | null = null; private width = 1; private height = 1; private image: HTMLImageElement | null = null; private imageUrl: string | null = null; private imagePromise: Promise<void> | null = null; private disposed = false;
  constructor(canvas?: HTMLCanvasElement) { this.canvas = canvas ?? document.createElement("canvas"); this.context = this.canvas.getContext("2d"); }
  setExportSize(width: number, height: number) { this.width = Math.max(1, Math.round(width)); this.height = Math.max(1, Math.round(height)); this.canvas.width = this.width; this.canvas.height = this.height; }
  restorePreviewSize() { const box = this.canvas.getBoundingClientRect(); const dpr = typeof window === "undefined" ? 1 : window.devicePixelRatio || 1; this.setExportSize((box.width || this.width) * dpr, (box.height || this.height) * dpr); }
  update(input: CassetteDeskRenderInput) { this.input = input; this.ensureImage(input.settings.coverImageUrl); this.renderNow(input.timeSeconds); }
  private ensureImage(url: string | null) { if (url === this.imageUrl) return; this.imageUrl = url;this.image=null;this.imagePromise=null;if(!url){this.renderNow();return;}const image = new Image(); this.image = image; this.imagePromise = new Promise((resolve, reject) => { image.onload = () => { if(this.image===image)this.renderNow();resolve(); }; image.onerror = () => {if(this.image===image)this.image=null;reject(new Error("Immagine Cassette Desk non caricabile."));}; }); void this.imagePromise.catch(() => undefined); image.src = url; }
  async prepare() { if (this.disposed) throw new Error("Renderer Cassette Desk dismesso."); this.ensureImage(this.input?.settings.coverImageUrl ?? null); await this.imagePromise; if (this.disposed) throw new Error("Renderer Cassette Desk dismesso."); }
  renderNow(timeSeconds = this.input?.timeSeconds ?? 0) {
    const context = this.context; const input = this.input; if (!context || !input) return; const { settings, analysis } = input; const timeline = cassetteDeskTimeline(timeSeconds, settings.introDurationSeconds); const palette = settings.palette; const waveformColor = resolvedColor(settings.waveformColorMode, settings.waveformColor, palette[2]);const displaySpectrumColor=resolvedColor(settings.displaySpectrumColorMode,settings.displaySpectrumColor,palette[2]);const stereoBodyColor=resolvedColor(settings.stereoBodyColorMode,settings.stereoBodyColor,palette[0]); const pianoColor = resolvedColor(settings.pianoColorMode, settings.pianoColor, palette[0]); const deskColor = resolvedColor(settings.deskColorMode, settings.deskColor, palette[1]); const w = this.width; const h = this.height; const landscape = w >= h;
    context.clearRect(0, 0, w, h); const wall = context.createLinearGradient(0, 0, 0, h); wall.addColorStop(0, "#17151a"); wall.addColorStop(.62, "#282227"); wall.addColorStop(1, deskColor); context.fillStyle = wall; context.fillRect(0, 0, w, h);
    context.save(); context.globalAlpha = .16; context.fillStyle = palette[0]; for (let i = 0; i < 80; i++) context.fillRect((i * 97) % w, (i * 53) % h, 1, 1); context.restore();
    const horizon = h * .55; context.fillStyle = deskColor; context.beginPath(); context.moveTo(0, horizon); context.lineTo(w, horizon * .94); context.lineTo(w, h); context.lineTo(0, h); context.closePath(); context.fill();
    // Fogli, penne e lattine rosse schiacciate: dettagli procedurali e sempre riutilizzabili.
    context.save(); context.translate(w * .12, horizon + h * .08); context.rotate(-.12); context.fillStyle = "#e4dfcf"; context.fillRect(0, 0, w * .23, h * .17); context.strokeStyle = palette[1]; context.globalAlpha = .5; for (let i = 1; i < 6; i++) { context.beginPath(); context.moveTo(w * .02, h * .02 + i * h * .022); context.lineTo(w * .2, h * .02 + i * h * .022); context.stroke(); } context.restore();
    context.save(); context.translate(w * .72, horizon + h * .12); context.rotate(.18); context.fillStyle = "#c5283d"; rounded(context, 0, 0, w * .055, h * .14, w * .018); context.fill(); context.fillStyle = "rgba(255,255,255,.55)"; context.fillRect(w * .008, h * .055, w * .039, h * .012); context.restore();
    context.save(); context.translate(w * .25, horizon + h * .28); context.rotate(-.32); context.fillStyle = palette[2]; rounded(context, 0, 0, w * .22, h * .012, h * .006); context.fill(); context.restore();
    const stereo = { x: w * (landscape ? .47 : .3), y: h * .105, width: w * (landscape ? .47 : .64), height: h * .43 };const posterStereo=settings.stereoStyle==="poster";context.save();context.shadowColor="#000b";context.shadowBlur=Math.min(w,h)*.045;context.shadowOffsetY=h*.018;const body=context.createLinearGradient(stereo.x,stereo.y,stereo.x,stereo.y+stereo.height);if(posterStereo){body.addColorStop(0,mixCassetteColor(stereoBodyColor,"#ffffff",.68));body.addColorStop(.55,stereoBodyColor);body.addColorStop(1,mixCassetteColor(stereoBodyColor,"#000000",.24));}else{body.addColorStop(0,"#42454b");body.addColorStop(.08,"#1c1e23");body.addColorStop(1,"#090a0d");}context.fillStyle=body;rounded(context,stereo.x,stereo.y,stereo.width,stereo.height,Math.min(w,h)*.025);context.fill();context.restore();context.strokeStyle=posterStereo?"#15161a":"#777b84";context.lineWidth=Math.max(1,w*.0015);context.stroke();if(posterStereo){context.save();rounded(context,stereo.x,stereo.y,stereo.width,stereo.height,Math.min(w,h)*.025);context.clip();context.strokeStyle=palette[2];context.globalAlpha=.34;context.lineWidth=Math.max(1,w*.0011);for(let i=0;i<15;i++){const sx=stereo.x+stereo.width*(.04+((i*37)%89)/100),sy=stereo.y+stereo.height*(.1+((i*23)%74)/100);context.beginPath();context.moveTo(sx,sy);context.lineTo(sx+stereo.width*(.025+(i%4)*.014),sy-stereo.height*(.018+(i%3)*.012));context.lineTo(sx+stereo.width*(.04+(i%5)*.01),sy+stereo.height*.012);context.stroke();}context.globalAlpha=.9;context.fillStyle=palette[2];context.fillRect(stereo.x+stereo.width*.955,stereo.y+stereo.height*.13,stereo.width*.012,stereo.height*.67);context.restore();}
    const waveformPulse=timeline.musicStarted&&analysis?.waveform.length?Math.abs(analysis.waveform[Math.floor((timeline.songTimeSeconds*24)%analysis.waveform.length)]??0):0;const drawSpeaker=(cx:number)=>{const cy=stereo.y+stereo.height*.58;const radius=Math.min(stereo.width*.135,stereo.height*.29)*(1+waveformPulse*.035);const cone=context.createRadialGradient(cx,cy,0,cx,cy,radius);cone.addColorStop(0,timeline.musicStarted?palette[2]:posterStereo?"#2a2b30":"#5b5d63");cone.addColorStop(.18,"#111318");cone.addColorStop(.7,"#292c32");cone.addColorStop(1,"#050609");context.fillStyle=cone;context.beginPath();context.arc(cx,cy,radius,0,Math.PI*2);context.fill();context.strokeStyle=posterStereo?palette[2]:"#6a6d72";context.lineWidth=posterStereo?Math.max(2,w*.0025):Math.max(1,w*.001);context.stroke();context.fillStyle="#090a0d";context.beginPath();context.arc(cx,cy-radius*1.55,radius*.27,0,Math.PI*2);context.fill();if(posterStereo){context.strokeStyle=palette[2];context.lineWidth=Math.max(1,w*.0015);context.stroke();}};drawSpeaker(stereo.x+stereo.width*.13);drawSpeaker(stereo.x+stereo.width*.87);
    const display={x:stereo.x+stereo.width*.235,y:stereo.y+stereo.height*.075,width:stereo.width*.53,height:stereo.height*.235};context.fillStyle="#050709";rounded(context,display.x,display.y,display.width,display.height,6);context.fill();context.strokeStyle=timeline.musicStarted?displaySpectrumColor:"#59645c";context.lineWidth=Math.max(1,w*.001);context.stroke();context.fillStyle="#f4f7f0";context.textAlign="center";context.font=`800 ${Math.max(9,Math.min(w*.014,h*.018))}px ui-sans-serif`;context.fillText(elide(context,settings.title||"UNTITLED TAPE",display.width*.88),display.x+display.width*.5,display.y+display.height*.25);context.globalAlpha=.9;context.font=`600 ${Math.max(7,Math.min(w*.0105,h*.013))}px ui-sans-serif`;context.fillText(elide(context,settings.artist||"UNKNOWN ARTIST",display.width*.88),display.x+display.width*.5,display.y+display.height*.47);context.globalAlpha=1;if(timeline.musicStarted){const bars=cassetteDeskSpectrumBars(analysis,timeline.songTimeSeconds),regionX=display.x+display.width*.08,regionY=display.y+display.height*.57,regionW=display.width*.84,regionH=display.height*.34,step=regionW/12,barW=step*.58;context.fillStyle=displaySpectrumColor;for(let index=0;index<12;index++){const energy=Math.max(.08,bars[index]??0);const barH=regionH*(.18+energy*.82);rounded(context,regionX+index*step+(step-barW)/2,regionY+regionH-barH,barW,barH,Math.min(3,barW*.3));context.fill();}}else{context.font=`700 ${Math.max(6,Math.min(w*.0075,h*.009))}px ui-monospace`;context.fillText("TAPE READY",display.x+display.width*.5,display.y+display.height*.82);}context.textAlign="start";
    const bay=cassetteStereoBayRect(settings.stereoStyle,stereo);context.fillStyle="#050609";rounded(context,bay.x,bay.y,bay.width,bay.height,8);context.fill();if(posterStereo){context.strokeStyle="#34363c";context.lineWidth=Math.max(2,w*.002);context.stroke();}const installed=timeline.phase==="closing"||timeline.phase==="pressing"||timeline.musicStarted;if(installed){const cx=bay.x+bay.width*.5,cy=bay.y+bay.height*.5,cw=Math.min(stereo.width*.31,bay.width*.84),ch=cw*.62;context.fillStyle=palette[0];rounded(context,cx-cw/2,cy-ch/2,cw,ch,5);context.fill();const installedLabelHeight=ch*.72,installedLabelWidth=installedLabelHeight*.75;drawContainedArtwork(context,this.image,{x:cx-installedLabelWidth/2,y:cy-installedLabelHeight/2,width:installedLabelWidth,height:installedLabelHeight},2,"#111318");context.fillStyle="#17191d";const rotation=timeline.songTimeSeconds*4;for(const side of[-1,1]){const reelX=cx+side*cw*.27;context.beginPath();context.arc(reelX,cy,cw*.085,0,Math.PI*2);context.fill();context.save();context.translate(reelX,cy);context.rotate(rotation*side);context.strokeStyle="#d8d8d3";context.lineWidth=Math.max(1,w*.0015);for(let spoke=0;spoke<3;spoke++){context.rotate(Math.PI*2/3);context.beginPath();context.moveTo(0,0);context.lineTo(cw*.07,0);context.stroke();}context.restore();}}const doorProgress=timeline.phase==="closing"?1-ease(timeline.phaseProgress):timeline.phase==="playing"||timeline.phase==="pressing"?0:1;context.save();context.translate(bay.x+bay.width*.5,bay.y+bay.height);context.transform(1,-.24*doorProgress,0,Math.max(.2,1-.68*doorProgress),0,0);context.fillStyle=posterStereo?"rgba(64,67,74,.72)":"rgba(95,101,109,.78)";context.fillRect(-bay.width*.5,-bay.height,bay.width,bay.height);context.strokeStyle=palette[2];context.lineWidth=Math.max(1,w*.002);context.strokeRect(-bay.width*.5,-bay.height,bay.width,bay.height);context.restore();
    const buttonX=stereo.x+stereo.width*.76;const buttonY=stereo.y+stereo.height*.84;const pressed=timeline.phase==="pressing"?ease(timeline.phaseProgress):timeline.musicStarted?1:0;if(posterStereo){const radius=Math.min(stereo.width*.07,stereo.height*.08),cx=buttonX+radius,cy=buttonY+radius+pressed*h*.006;context.fillStyle="#101116";context.beginPath();context.arc(cx,cy,radius,0,Math.PI*2);context.fill();context.strokeStyle=palette[2];context.lineWidth=Math.max(2,w*.0025);context.stroke();context.fillStyle=palette[2];context.beginPath();context.moveTo(cx-radius*.22,cy-radius*.38);context.lineTo(cx+radius*.42,cy);context.lineTo(cx-radius*.22,cy+radius*.38);context.closePath();context.fill();}else{context.fillStyle=pressed?palette[2]:"#d8d9dc";rounded(context,buttonX,buttonY+pressed*h*.006,stereo.width*.12,stereo.height*.065,4);context.fill();context.fillStyle="#090a0d";context.font=`700 ${Math.max(7,w*.008)}px ui-monospace`;context.fillText("▶ PLAY",buttonX+4,buttonY+stereo.height*.045);}
    const caseX=w*(landscape?.22:.18),caseY=h*.405,caseW=Math.min(w*(landscape?.18:.3),h*.25),caseH=caseW*4/3;const openAmount=timeline.phase==="opening"?ease(timeline.phaseProgress):timeline.phase==="inserting"||timeline.phase==="closing"||timeline.phase==="pressing"||timeline.musicStarted?1:0;
    // Il fondo resta dietro alla cassetta. La cover viene disegnata sul coperchio
    // solo dopo la cassetta, così da nasconderla completamente a custodia chiusa.
    context.save();context.translate(caseX,caseY);context.rotate(-.075);context.shadowColor="#0009";context.shadowBlur=Math.min(w,h)*.018;context.fillStyle="#0d0e12";rounded(context,-caseW/2,-caseH/2,caseW,caseH,caseW*.045);context.fill();context.shadowColor="transparent";context.fillStyle="#202127";rounded(context,-caseW*.43,-caseH*.43,caseW*.86,caseH*.86,caseW*.025);context.fill();context.strokeStyle="rgba(240,247,246,.72)";context.lineWidth=Math.max(1,w*.002);rounded(context,-caseW/2,-caseH/2,caseW,caseH,caseW*.045);context.stroke();context.restore();
    const insertP=timeline.phase==="inserting"?ease(timeline.phaseProgress):timeline.phase==="closing"||timeline.phase==="pressing"||timeline.musicStarted?1:0;const cassetteX=caseX+(stereo.x+stereo.width*.5-caseX)*insertP;const cassetteY=caseY+(stereo.y+stereo.height*.53-caseY)*insertP-Math.sin(insertP*Math.PI)*h*.21;const cassetteRotation=cassetteInsertionRotation(insertP);const cassetteScale=1-insertP*.43;
    if(!timeline.musicStarted&&insertP<.92){const cw=caseW*.92*cassetteScale;const ch=cw*.62;context.save();context.translate(cassetteX,cassetteY);context.rotate(cassetteRotation);context.shadowColor="#0009";context.shadowBlur=Math.min(w,h)*.018;context.fillStyle=palette[0];rounded(context,-cw/2,-ch/2,cw,ch,cw*.055);context.fill();context.shadowColor="transparent";context.strokeStyle="#121318";context.lineWidth=Math.max(2,w*.003);context.stroke();const labelH=ch*.55,labelW=labelH*.75;drawContainedArtwork(context,this.image,{x:-labelW/2,y:-labelH*.62,width:labelW,height:labelH},3,"#17191d");context.fillStyle="#17191d";for(const side of[-1,1]){context.beginPath();context.arc(side*cw*.28,ch*.18,cw*.09,0,Math.PI*2);context.fill();context.strokeStyle="#a6a8aa";context.stroke();}context.restore();}
    context.save();context.translate(caseX,caseY);context.rotate(-.075);const lid=cassetteCaseLidMatrix(openAmount);context.translate(-caseW/2,0);context.transform(lid.horizontalScale,lid.verticalShear,0,1,0,0);context.fillStyle="#17181d";rounded(context,0,-caseH/2,caseW,caseH,caseW*.045);context.fill();drawContainedArtwork(context,this.image,{x:caseW*.05,y:-caseH*.45,width:caseW*.9,height:caseH*.9},caseW*.025,"#202127");context.fillStyle="rgba(218,228,230,.10)";rounded(context,0,-caseH/2,caseW,caseH,caseW*.045);context.fill();context.strokeStyle="rgba(240,247,246,.82)";context.lineWidth=Math.max(1,w*.002);context.stroke();context.restore();
    const card={x:w*.045,y:h*.585,width:w*.91,height:h*.37};context.fillStyle="rgba(6,7,10,.91)";rounded(context,card.x,card.y,card.width,card.height,Math.min(w,h)*.022);context.fill();context.strokeStyle="rgba(255,255,255,.18)";context.lineWidth=Math.max(1,w*.001);context.stroke();const pad=card.width*.035;const titleY=card.y+card.height*.12;
    if(settings.showTrackInfo){const chipY=titleY;const chip=(label:string,value:string,x:number,color:string)=>{const fontSize=Math.max(12,Math.min(w*.019,h*.018)),height=Math.max(h*.048,fontSize*1.75);context.font=`900 ${fontSize}px ui-monospace`;const width=context.measureText(`${label}  ${value}`).width+pad*.75;context.fillStyle=color;rounded(context,x,chipY,width,height,height*.24);context.fill();context.strokeStyle="rgba(255,255,255,.34)";context.lineWidth=Math.max(1,w*.001);context.stroke();context.fillStyle=readableCassetteTextColor(color);context.fillText(`${label}  ${value}`,x+pad*.32,chipY+height*.68);return x+width+pad*.22;};let chipX=card.x+pad;chipX=chip("BPM",analysis?.bpm?analysis.bpm.toFixed(1):"—",chipX,palette[0]);chip("KEY",analysis?.keyLabel??"—",chipX,palette[2]);}
    if(settings.showWaveform){const waveform=analysis?.waveform??[];const x=card.x+pad,width=card.width-pad*2,center=card.y+card.height*.59;context.strokeStyle=waveformColor;context.lineWidth=Math.max(1,w*.002);context.beginPath();const columns=Math.min(520,Math.max(100,Math.floor(width/2.5)));for(let i=0;i<columns;i++){const sample=Math.abs(waveform[Math.floor(i/columns*waveform.length)]??.025);const amp=(.08+sample*.92)*card.height*.16*(timeline.musicStarted?1:.2);const px=x+i/(columns-1)*width;context.moveTo(px,center-amp);context.lineTo(px,center+amp);}context.stroke();const progress=timeline.musicStarted?Math.min(1,timeline.songTimeSeconds/Math.max(.001,input.songDurationSeconds)):0;context.fillStyle="#fff";context.fillRect(x+width*progress-1,center-card.height*.19,2,card.height*.38);}
    if(settings.showPiano){const pianoY=card.y+card.height*.76,pianoX=card.x+pad,pianoW=card.width-pad*2,keyH=card.height*.17;const active=cassetteDeskActiveNote(analysis,timeline.songTimeSeconds);const keyboard=cassettePianoLayout();context.fillStyle="#111318";rounded(context,pianoX-pad*.12,pianoY-pad*.12,pianoW+pad*.24,keyH+pad*.24,6);context.fill();context.strokeStyle="#3d4047";context.lineWidth=Math.max(1,w*.0007);for(const key of keyboard){if(key.kind!=="white")continue;context.fillStyle=cassettePianoKeyIsActive(key.midi,active?.midi)?pianoColor:"#f1eee8";context.fillRect(pianoX+key.x*pianoW,pianoY,key.width*pianoW,keyH);context.strokeRect(pianoX+key.x*pianoW,pianoY,key.width*pianoW,keyH);}for(const key of keyboard){if(key.kind!=="black")continue;context.fillStyle=cassettePianoKeyIsActive(key.midi,active?.midi)?palette[2]:"#101116";context.fillRect(pianoX+key.x*pianoW,pianoY,key.width*pianoW,keyH*.62);}}
    context.save(); context.globalAlpha=.22; context.fillStyle="#000"; context.fillRect(0,0,w,h*.018); context.restore();
  }
  dispose() { this.disposed=true; if(this.image){this.image.onload=null;this.image.onerror=null;} this.image=null;this.context=null;this.input=null; }
}
