import { describe, expect, it, vi } from "vitest";
import { boundedExportDuration, createCanvasFrameCapture, exportFrameIndex, mediaDrawRect, recordingBitrate, selectRecordingFormat } from "./live-video-exporter";

describe("live video exporter", () => {
  it("preferisce MP4 e usa WebM come fallback", () => { expect(selectRecordingFormat((type) => type.startsWith("video/mp4"))?.extension).toBe(".mp4"); expect(selectRecordingFormat((type) => type.includes("vp9"))?.mimeType).toContain("vp9"); expect(selectRecordingFormat(() => false)).toBeNull(); });
  it("dimensiona il bitrate professionale senza superare i limiti operativi", () => { expect(recordingBitrate(540, 960, 30)).toBe(12_000_000); expect(recordingBitrate(3840, 2160, 120)).toBe(160_000_000); expect(recordingBitrate(1920, 1080, 60)).toBeGreaterThan(25_000_000); });
  it("mantiene la qualità massima sopra il profilo alta", () => { expect(recordingBitrate(1920, 1080, 60, "maximum")).toBeGreaterThan(recordingBitrate(1920, 1080, 60, "high")); });
  it("usa la cattura temporizzata per mantenere timestamp video monotoni", () => { const stream = { getVideoTracks: () => [{}], getTracks: () => [] } as unknown as MediaStream; const canvas = { captureStream: vi.fn(() => stream) } as unknown as HTMLCanvasElement; const capture = createCanvasFrameCapture(canvas, 60); expect(capture).toMatchObject({ stream, manual: false }); expect(canvas.captureStream).toHaveBeenCalledWith(60); });
  it("usa la cattura manuale soltanto come fallback", () => { const requestFrame = vi.fn(); const manual = { getVideoTracks: () => [{ requestFrame }], getTracks: () => [] } as unknown as MediaStream; const canvas = { captureStream: vi.fn().mockImplementationOnce(() => { throw new Error("unsupported"); }).mockReturnValueOnce(manual) } as unknown as HTMLCanvasElement; const capture = createCanvasFrameCapture(canvas, 60); expect(capture.manual).toBe(true); capture.requestFrame(); expect(requestFrame).toHaveBeenCalledOnce(); expect(canvas.captureStream).toHaveBeenNthCalledWith(2, 0); });
  it("avanza il contatore lungo tutta la durata invece di fermarsi al primo frame", () => { const indices = [0, 16.7, 33.4, 500, 999, 1_000].map((elapsed) => exportFrameIndex(elapsed, 60, 1)); expect(indices).toEqual([0, 1, 2, 30, 59, 59]); expect(new Set(indices).size).toBeGreaterThan(4); });
  it("riempie lo sfondo Cube senza zoom o ritaglio", () => { expect(mediaDrawRect(1_200, 1_200, 1_080, 1_920, "fill")).toEqual({ x: 0, y: 0, width: 1_080, height: 1_920 }); });
  it("limita la durata alla traccia reale senza tagliare il reveal finale", () => { expect(boundedExportDuration(1_200, 60, 60)).toBe(60); expect(boundedExportDuration(65, 60, 60, 5)).toBe(65); expect(boundedExportDuration(60, 60, Number.NaN)).toBe(60); });
});
