import { describe, expect, it, vi } from "vitest";
import { createCanvasFrameCapture, exportFrameIndex, recordingBitrate, selectRecordingFormat } from "./live-video-exporter";

describe("live video exporter", () => {
  it("preferisce MP4 e usa WebM come fallback", () => { expect(selectRecordingFormat((type) => type.startsWith("video/mp4"))?.extension).toBe(".mp4"); expect(selectRecordingFormat((type) => type.includes("vp9"))?.mimeType).toContain("vp9"); expect(selectRecordingFormat(() => false)).toBeNull(); });
  it("dimensiona il bitrate professionale senza superare i limiti operativi", () => { expect(recordingBitrate(540, 960, 30)).toBe(12_000_000); expect(recordingBitrate(3840, 2160, 120)).toBe(160_000_000); expect(recordingBitrate(1920, 1080, 60)).toBeGreaterThan(25_000_000); });
  it("mantiene la qualità massima sopra il profilo alta", () => { expect(recordingBitrate(1920, 1080, 60, "maximum")).toBeGreaterThan(recordingBitrate(1920, 1080, 60, "high")); });
  it("richiede esplicitamente ogni frame quando il browser lo supporta", () => { const requestFrame = vi.fn(); const stop = vi.fn(); const stream = { getVideoTracks: () => [{ requestFrame }], getTracks: () => [{ stop }] } as unknown as MediaStream; const canvas = { captureStream: vi.fn(() => stream) } as unknown as HTMLCanvasElement; const capture = createCanvasFrameCapture(canvas, 60); expect(capture.manual).toBe(true); capture.requestFrame(); capture.requestFrame(); expect(requestFrame).toHaveBeenCalledTimes(2); expect(canvas.captureStream).toHaveBeenCalledWith(0); expect(stop).not.toHaveBeenCalled(); });
  it("ripiega sulla cattura temporizzata se requestFrame non esiste", () => { const stop = vi.fn(); const manual = { getVideoTracks: () => [{}], getTracks: () => [{ stop }] } as unknown as MediaStream; const automatic = { getVideoTracks: () => [{}], getTracks: () => [] } as unknown as MediaStream; const canvas = { captureStream: vi.fn().mockReturnValueOnce(manual).mockReturnValueOnce(automatic) } as unknown as HTMLCanvasElement; const capture = createCanvasFrameCapture(canvas, 30); expect(capture.manual).toBe(false); expect(capture.stream).toBe(automatic); expect(stop).toHaveBeenCalledOnce(); expect(canvas.captureStream).toHaveBeenNthCalledWith(2, 30); });
  it("ripiega sulla cattura temporizzata anche quando frameRate zero viene rifiutato", () => { const automatic = { getVideoTracks: () => [{}], getTracks: () => [] } as unknown as MediaStream; const canvas = { captureStream: vi.fn().mockImplementationOnce(() => { throw new Error("unsupported"); }).mockReturnValueOnce(automatic) } as unknown as HTMLCanvasElement; expect(createCanvasFrameCapture(canvas, 60)).toMatchObject({ stream: automatic, manual: false }); });
  it("avanza il contatore lungo tutta la durata invece di fermarsi al primo frame", () => { const indices = [0, 16.7, 33.4, 500, 999, 1_000].map((elapsed) => exportFrameIndex(elapsed, 60, 1)); expect(indices).toEqual([0, 1, 2, 30, 59, 59]); expect(new Set(indices).size).toBeGreaterThan(4); });
});
