import { afterEach, describe, expect, it, vi } from "vitest";
import { createProject } from "@rbs/project-schema";
import { overlaySpectralPresetIds } from "./overlay-spectral-catalog";
import { OverlaySpectralRenderer, resolveOverlaySpectralImageFit } from "./overlay-spectral-renderer";

function contextMock() { const gradient = () => ({ addColorStop: vi.fn() }); return { fillStyle: "", strokeStyle: "", lineWidth: 1, globalAlpha: 1, globalCompositeOperation: "source-over", font: "", createLinearGradient: vi.fn(gradient), createRadialGradient: vi.fn(gradient), clearRect: vi.fn(), fillRect: vi.fn(), drawImage: vi.fn(), save: vi.fn(), restore: vi.fn(), translate: vi.fn(), rotate: vi.fn(), beginPath: vi.fn(), moveTo: vi.fn(), lineTo: vi.fn(), closePath: vi.fn(), stroke: vi.fn(), fill: vi.fn(), arc: vi.fn(), fillText: vi.fn() }; }
const energy = [{ timeSeconds: 0, rms: .2, low: .4, mid: .5, high: .3, flux: .2, spectralCentroid: 1000, spectralFlatness: .2, bands48: Array.from({ length: 48 }, (_, index) => (index + 1) / 48) }, { timeSeconds: 1, rms: .25, low: .5, mid: .6, high: .35, flux: .15, spectralCentroid: 1200, spectralFlatness: .2, bands48: Array.from({ length: 48 }, (_, index) => (48 - index) / 48) }];

describe("overlay spectral renderer", () => {
  afterEach(() => vi.restoreAllMocks());
  it("adatta cover e contain senza deformare", () => { expect(resolveOverlaySpectralImageFit(100, 50, 100, 100, "contain")).toEqual({ x: 0, y: 25, width: 100, height: 50 }); expect(resolveOverlaySpectralImageFit(100, 50, 100, 100, "cover")).toEqual({ x: -50, y: 0, width: 200, height: 100 }); });
  it("campiona sempre 48 bande reali in modo deterministico", () => { const context = contextMock(); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D); const renderer = new OverlaySpectralRenderer(document.createElement("canvas")); renderer.setExportSize(1080, 1920); renderer.update({ settings: createProject().animation.overlaySpectral, energyFrames: energy, timeSeconds: .5 }); const values = [...renderer.lastBandValues]; expect(values).toHaveLength(48); expect(values.some((value) => value > 0)).toBe(true); renderer.renderNow(.5); expect(renderer.lastBandValues).toEqual(values); });
  it("non applica la vignetta nera automatica sopra un'immagine caricata", () => { const context = contextMock(); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D); const renderer = new OverlaySpectralRenderer(document.createElement("canvas")); renderer.setExportSize(640, 360); renderer.update({ settings: { ...createProject().animation.overlaySpectral, backgroundImageUrl: "data:image/png;base64,AAAA", backgroundMediaType: "image", backgroundDim: 0 }, energyFrames: energy, timeSeconds: 0 }); context.createRadialGradient.mockClear(); renderer.renderNow(0); expect(context.createRadialGradient).not.toHaveBeenCalled(); renderer.dispose(); });
  it("renderizza l'intero catalogo adattato senza stato casuale", () => { const context = contextMock(); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D); const renderer = new OverlaySpectralRenderer(document.createElement("canvas")); renderer.setExportSize(640, 640); overlaySpectralPresetIds.forEach((presetId) => renderer.update({ settings: { ...createProject().animation.overlaySpectral, presetId }, energyFrames: energy, timeSeconds: 1 })); expect(overlaySpectralPresetIds).toHaveLength(14); expect(context.fillRect).toHaveBeenCalled(); expect(context.stroke).toHaveBeenCalled(); expect(context.fill).toHaveBeenCalled(); });
  it("riproduce realmente lo sfondo video e corregge solo un drift significativo", () => {
    const context = contextMock(); const host = document.createElement("div"); const canvas = document.createElement("canvas"); host.appendChild(canvas); const video = document.createElement("video"); const createElement = document.createElement.bind(document);
    vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D);
    const play = vi.spyOn(video, "play").mockResolvedValue(undefined); const pause = vi.spyOn(video, "pause").mockImplementation(() => undefined); vi.spyOn(video, "load").mockImplementation(() => undefined);
    Object.defineProperties(video, { videoWidth: { configurable: true, value: 1920 }, videoHeight: { configurable: true, value: 1080 }, duration: { configurable: true, value: 10 }, currentTime: { configurable: true, writable: true, value: 0 } });
    vi.spyOn(document, "createElement").mockImplementation(((tagName: string, options?: ElementCreationOptions) => tagName === "video" ? video : createElement(tagName, options)) as typeof document.createElement);
    const renderer = new OverlaySpectralRenderer(canvas); renderer.setExportSize(640, 360); renderer.update({ settings: { ...createProject().animation.overlaySpectral, backgroundImageUrl: "data:video/mp4;base64,AAAA", backgroundMediaType: "video" }, energyFrames: energy, timeSeconds: 2 });
    expect(video.parentElement).toBe(host); expect(video.defaultMuted).toBe(true); expect(video.style.objectFit).toBe("cover");
    video.onloadeddata?.(new Event("loadeddata")); renderer.setPreviewPlaying(true, 2);
    expect(video.currentTime).toBe(2); expect(play).toHaveBeenCalledOnce();
    renderer.renderNow(2.2); expect(video.currentTime).toBe(2);
    renderer.renderNow(2.6); expect(video.currentTime).toBe(2.6); expect(context.drawImage).toHaveBeenCalledWith(video, expect.any(Number), expect.any(Number), expect.any(Number), expect.any(Number));
    renderer.setPreviewPlaying(false, 3.1); expect(pause).toHaveBeenCalled(); expect(video.currentTime).toBe(3.1); renderer.dispose(); expect(video.parentElement).toBeNull();
  });
  it("lascia trasparente il canvas quando il video è il livello preview sottostante", () => { const context = contextMock(); const host = document.createElement("div"); const canvas = document.createElement("canvas"); host.appendChild(canvas); const video = document.createElement("video"); const createElement = document.createElement.bind(document); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D); vi.spyOn(video, "pause").mockImplementation(() => undefined); vi.spyOn(video, "load").mockImplementation(() => undefined); Object.defineProperties(video, { videoWidth: { configurable: true, value: 640 }, videoHeight: { configurable: true, value: 360 }, duration: { configurable: true, value: 10 }, currentTime: { configurable: true, writable: true, value: 0 } }); vi.spyOn(document, "createElement").mockImplementation(((tagName: string, options?: ElementCreationOptions) => tagName === "video" ? video : createElement(tagName, options)) as typeof document.createElement); const renderer = new OverlaySpectralRenderer(canvas); renderer.setExportSize(640, 360); renderer.setExternalBackground(true); renderer.update({ settings: { ...createProject().animation.overlaySpectral, backgroundImageUrl: "data:video/mp4;base64,AAAA", backgroundMediaType: "video", backgroundDim: .25 }, energyFrames: energy, timeSeconds: 1 }); video.onloadeddata?.(new Event("loadeddata")); context.drawImage.mockClear(); context.createLinearGradient.mockClear(); context.createRadialGradient.mockClear(); renderer.renderNow(1.2); expect(context.drawImage).not.toHaveBeenCalled(); expect(context.createLinearGradient).not.toHaveBeenCalled(); expect(context.createRadialGradient).not.toHaveBeenCalled(); expect(context.fillRect).toHaveBeenCalled(); renderer.dispose(); });
});
