import type { ExportProgress } from "@rbs/export-engine";
import type { OverlaySpectralSettings } from "@rbs/project-schema";
import { exportOfflineSceneVideo, type ExportQuality, type SharedViewportRenderer } from "./offline-video-exporter";

export interface OverlaySpectralOfflineExportSettings { width: number; height: number; fps: number; durationSeconds: number; sourceUrl: string; aspectRatio: "9:16" | "16:9" | "1:1" | "4:5" | "custom"; projectName: string; quality: ExportQuality; overlaySettings: OverlaySpectralSettings; renderer: SharedViewportRenderer & { prepare?: () => Promise<void>; setExternalBackground?: (enabled: boolean) => void }; }
export async function exportOverlaySpectralOfflineVideo(settings: OverlaySpectralOfflineExportSettings, signal: AbortSignal, onProgress?: (progress: ExportProgress) => void) {
  if (!settings.sourceUrl || settings.durationSeconds <= 0) throw new Error("L’export Overlay Spectral richiede un brano analizzato."); settings.renderer.setExternalBackground?.(true);
  try { await settings.renderer.prepare?.(); if (signal.aborted) throw new DOMException("Export annullato", "AbortError");
    return await exportOfflineSceneVideo({ width: settings.width, height: settings.height, fps: settings.fps, durationSeconds: settings.durationSeconds, projectName: settings.projectName, quality: settings.quality, sourceUrl: settings.sourceUrl, sourceDuration: settings.durationSeconds, aspectRatio: settings.aspectRatio, background: { colors: [settings.overlaySettings.palette[0], settings.overlaySettings.palette[1]], imageUrl: settings.overlaySettings.backgroundImageUrl, mediaType: settings.overlaySettings.backgroundMediaType, presetId: "custom", finish: "clean", opacity: 1, blur: 0, effects: { glow: false, particles: false, vignette: false }, neon: { enabled: false, text: "", color: "#fff" } }, backgroundDimming: 0, backgroundFit: settings.overlaySettings.backgroundFit, ball: { radius: .4, color: "#fff", emission: 0, metalness: 0, trailEnabled: false, innerColor: "#fff", innerShape: "orb", innerImageUrl: null, endRevealEnabled: false, revealMode: "end", revealTimeSeconds: 0, revealHoldSeconds: 0 } }, settings.renderer, () => undefined, signal, (progress) => onProgress?.(progress));
  } finally { settings.renderer.setExternalBackground?.(settings.overlaySettings.backgroundMediaType === "video" && Boolean(settings.overlaySettings.backgroundImageUrl)); settings.renderer.renderNow(); }
}
