import { beforeEach, describe, expect, it, vi } from "vitest";
import { createProject } from "@rbs/project-schema";
const { exportScene } = vi.hoisted(() => ({ exportScene: vi.fn() }));
vi.mock("./offline-video-exporter", async (importOriginal) => ({ ...await importOriginal<typeof import("./offline-video-exporter")>(), exportOfflineSceneVideo: exportScene }));
import { exportOverlaySpectralOfflineVideo } from "./overlay-spectral-offline-exporter";

describe("overlay spectral exporter", () => {
  beforeEach(() => exportScene.mockReset().mockResolvedValue({ fileName: "overlay-spectral.mp4", width: 1080, height: 1920, fps: 30, encodedFrameCount: 300, audioPacketCount: 10 }));
  it("prepara il renderer e muxa il brano originale con sfondo video frame-accurate", async () => { const renderer = { canvas: document.createElement("canvas"), setExportSize: vi.fn(), restorePreviewSize: vi.fn(), renderNow: vi.fn(), prepare: vi.fn().mockResolvedValue(undefined), setExternalBackground: vi.fn() }; const overlaySettings = { ...createProject().animation.overlaySpectral, backgroundImageUrl: "data:video/mp4;base64,AAAA", backgroundMediaType: "video" as const, backgroundFit: "contain" as const, backgroundDim: .4 }; await exportOverlaySpectralOfflineVideo({ width: 1080, height: 1920, fps: 30, durationSeconds: 10, sourceUrl: "blob:audio", aspectRatio: "9:16", projectName: "test", quality: "high", overlaySettings, renderer }, new AbortController().signal); expect(renderer.prepare).toHaveBeenCalledOnce(); expect(renderer.setExternalBackground).toHaveBeenNthCalledWith(1, true); expect(renderer.setExternalBackground).toHaveBeenLastCalledWith(true); expect(exportScene).toHaveBeenCalledWith(expect.objectContaining({ sourceUrl: "blob:audio", sourceDuration: 10, durationSeconds: 10, aspectRatio: "9:16", background: expect.objectContaining({ imageUrl: overlaySettings.backgroundImageUrl, mediaType: "video" }), backgroundDimming: 0, backgroundFit: "contain" }), renderer, expect.any(Function), expect.any(AbortSignal), expect.any(Function)); });
  it("rifiuta l’export senza audio", async () => { const renderer = { canvas: document.createElement("canvas"), setExportSize: vi.fn(), restorePreviewSize: vi.fn(), renderNow: vi.fn() }; await expect(exportOverlaySpectralOfflineVideo({ width: 10, height: 10, fps: 30, durationSeconds: 1, sourceUrl: "", aspectRatio: "1:1", projectName: "test", quality: "high", overlaySettings: createProject().animation.overlaySpectral, renderer }, new AbortController().signal)).rejects.toThrow(/brano analizzato/); });
});
