import { describe, expect, it } from "vitest";
import { createProject } from "@rbs/project-schema";
import { generateScene, isVerticalDescent } from "./scene-generator";
describe("scene generator", () => {
  it("rigenera la stessa scena con lo stesso seed", () => { const project = createProject(); expect(generateScene(project.events, 42)).toEqual(generateScene(project.events, 42)); expect(generateScene(project.events, 42)).not.toEqual(generateScene(project.events, 43)); });
  it("evita sovrapposizioni critiche", () => { const objects = generateScene([], 9, "neon", 10); for (let a = 0; a < objects.length; a += 1) for (let b = a + 1; b < objects.length; b += 1) expect(Math.hypot((objects[a]?.position[0] ?? 0) - (objects[b]?.position[0] ?? 0), (objects[a]?.position[1] ?? 0) - (objects[b]?.position[1] ?? 0))).toBeGreaterThan(.7); });
  it("crea un percorso strettamente discendente", () => { const objects = generateScene([], 99, "neon", 40); for (let index = 1; index < objects.length; index += 1) expect(objects[index]?.position[1]).toBeLessThan(objects[index - 1]?.position[1] ?? Infinity); });
  it("rispetta lo strumento assegnato manualmente all'evento", () => { const event = { id: "manual", timeSeconds: 1, timeSamples: 48_000, eventType: "manual" as const, confidence: 1, strength: .8, frequencyBand: "full" as const, assignedObjectType: "cymbal", assignedObjectId: null, enabled: true, accent: false, manualOverride: true, action: "collision" as const, expectedBallPosition: { x: 0, y: 0, z: 0 }, expectedBallVelocity: { x: 0, y: 0, z: 0 }, expectedImpactNormal: { x: 0, y: 1, z: 0 } }; expect(generateScene([event], 12, "neon", 1)[0]?.type).toBe("cymbal"); });
  it("mantiene l'override manuale anche fuori dalla base automatica", () => { const event = { id: "piano-manual", timeSeconds: 1, timeSamples: 48_000, eventType: "manual" as const, confidence: 1, strength: .8, frequencyBand: "mid" as const, assignedObjectType: "piano", assignedObjectId: null, enabled: true, accent: false, manualOverride: true, action: "collision" as const, expectedBallPosition: { x: 0, y: 0, z: 0 }, expectedBallVelocity: { x: 0, y: 0, z: 0 }, expectedImpactNormal: { x: 0, y: 1, z: 0 } }; expect(generateScene([event], 12, "neon", 1, ["kick", "snare"])[0]?.type).toBe("piano"); });
  it("genera piano, corde di chitarra e violino quando abilitati dalla modalità", () => { const base = { id: "piano", timeSeconds: 0, timeSamples: 0, eventType: "piano" as const, confidence: 1, strength: .8, frequencyBand: "mid" as const, assignedObjectType: null, assignedObjectId: null, enabled: true, accent: false, manualOverride: false, action: "collision" as const, expectedBallPosition: { x: 0, y: 0, z: 0 }, expectedBallVelocity: { x: 0, y: 0, z: 0 }, expectedImpactNormal: { x: 0, y: 1, z: 0 } }; const events = [base, { ...base, id: "guitar", timeSeconds: 1, timeSamples: 48_000, eventType: "guitar" as const }, { ...base, id: "strings", timeSeconds: 2, timeSamples: 96_000, eventType: "strings" as const }]; expect(generateScene(events, 12, "neon", 3, ["piano", "guitar", "strings"]).map((object) => object.type)).toEqual(["piano", "guitar", "strings"]); });
  it("inserisce almeno una volta ogni famiglia scelta nella base normalizzata", () => { const selected = ["kick", "snare", "drum", "cymbal", "piano", "guitar", "strings"] as const; expect(generateScene([], 12, "neon", selected.length, selected).map((object) => object.type)).toEqual(selected); });
  it("mantiene la maggioranza dei tratti orizzontale e cambia direzione ai margini", () => { const objects = generateScene([], 21, "neon", 16); const directions = new Set<number>(); let horizontal = 0; for (let index = 1; index < objects.length; index += 1) { const dx = (objects[index]?.position[0] ?? 0) - (objects[index - 1]?.position[0] ?? 0); const dy = (objects[index]?.position[1] ?? 0) - (objects[index - 1]?.position[1] ?? 0); if (Math.abs(dx) > Math.abs(dy)) horizontal += 1; directions.add(Math.sign(dx)); } expect(horizontal / (objects.length - 1)).toBeGreaterThan(.7); expect(directions).toEqual(new Set([1, -1])); });
  it("crea una grande caduta verticale quando un marker debole separa due rimbalzi", () => { const project = createProject(); const base = project.events[0] ?? { id: "a", timeSeconds: 0, timeSamples: 0, eventType: "percussion" as const, confidence: 1, strength: .5, frequencyBand: "full" as const, assignedObjectType: null, assignedObjectId: null, enabled: true, accent: false, manualOverride: false, action: "collision" as const, expectedBallPosition: { x: 0, y: 0, z: 0 }, expectedBallVelocity: { x: 0, y: 0, z: 0 }, expectedImpactNormal: { x: 0, y: 1, z: 0 } }; const events = [base, { ...base, id: "gap", timeSeconds: .5, timeSamples: 24_000, action: "freeFall" as const }, { ...base, id: "b", timeSeconds: 1, timeSamples: 48_000 }]; const objects = generateScene(events, 4); expect((objects[0]?.position[1] ?? 0) - (objects[1]?.position[1] ?? 0)).toBeGreaterThan(1.65); });
  it("mantiene i piatti dorati nella generazione predefinita", () => { const cymbal = generateScene([], 2, "neon", 4).find((object) => object.type === "cymbal"); expect(cymbal?.color).toBe("#d6a83f"); });
  it("organizza il percorso in lunghe corsie orizzontali separate da discese nette", () => { const objects = generateScene([], 31, "neon", 24); const drops = objects.slice(1).map((object, index) => (objects[index]?.position[1] ?? 0) - object.position[1]); expect(drops.filter((drop) => drop < .2).length).toBeGreaterThan(15); expect(drops.some((drop) => drop > 2.8)).toBe(true); });
  it("occupa la profondità e sposta nettamente avanti o indietro ogni discesa verticale", () => { const objects = generateScene([], 17, "neon", 24); const depths = objects.map((object) => object.position[2]); expect(Math.max(...depths) - Math.min(...depths)).toBeGreaterThan(3); const verticalSegments = objects.slice(0, -1).map((object, index) => [object, objects[index + 1]] as const).filter(([start, end]) => isVerticalDescent(start, end)); expect(verticalSegments.length).toBeGreaterThan(0); expect(verticalSegments.every(([start, end]) => Math.abs((end?.position[2] ?? 0) - start.position[2]) > 1.5)).toBe(true); });
});
