import { beforeEach, describe, expect, it, vi } from "vitest";
const { cancel, wait, capabilities, browserAnalysis } = vi.hoisted(() => ({ cancel: vi.fn(), wait: vi.fn(), capabilities: vi.fn(), browserAnalysis: vi.fn() }));
vi.mock("./song-player-native", () => ({ getSongPlayerCapabilities: capabilities, startSongPlayerJob: vi.fn().mockResolvedValue({ jobId: "analysis-1", status: "queued" }), waitForSongPlayerJob: wait, cancelSongPlayerJob: cancel, isSongPlayerJobTerminal: () => false }));
vi.mock("./song-player-browser-audio", () => ({ analyzeSongPlayerInBrowser: browserAnalysis }));
import { analyzeSongPlayerAudio } from "./song-player-analysis";

describe("native song player analysis cancellation", () => {
  beforeEach(() => { const fallback = { sourceHash: "e".repeat(64), durationSeconds: 10, chromaHopSeconds: 1, chroma: new Float32Array(120), fingerprintVersion: "v1", spectrogram: { version: 1, sourceHash: "e".repeat(64), sampleRate: 1, fftSize: 1024, hopSize: 512, bands: 96, frameCount: 10, durationSeconds: 10, minDb: -80, maxDb: 0, data: new ArrayBuffer(960) } }; cancel.mockReset().mockResolvedValue(undefined); wait.mockReset().mockRejectedValue(new DOMException("annullata", "AbortError")); capabilities.mockReset().mockResolvedValue({ desktop: true, analysis: true, nativeAnalysis: true, reasons: [] }); browserAnalysis.mockReset().mockResolvedValue(fallback); });
  it("cancels the native worker when project ownership aborts", async () => { const controller = new AbortController(); wait.mockImplementationOnce((_jobId, options: { signal: AbortSignal }) => new Promise((_resolve, reject) => options.signal.addEventListener("abort", () => reject(new DOMException("annullata", "AbortError")), { once: true }))); const audio = { metadata: { path: "/full.wav", fileName: "full.wav", hash: "d".repeat(64), durationSeconds: 10, sampleRate: 44100, channels: 2, codec: "wav", fileSize: 10 }, waveform: [0], url: "blob:full" }; const pending = analyzeSongPlayerAudio(audio, undefined, controller.signal); await vi.waitFor(() => expect(wait).toHaveBeenCalled()); controller.abort(); await expect(pending).rejects.toMatchObject({ name: "AbortError" }); expect(cancel).toHaveBeenCalledWith("analysis-1"); });
  it("falls back to a real browser FFT when the native worker fails", async () => { wait.mockRejectedValueOnce(new Error("decoder FFT guasto")); const audio = { metadata: { path: "/full.wav", fileName: "full.wav", hash: "e".repeat(64), durationSeconds: 10, sampleRate: 44100, channels: 2, codec: "wav", fileSize: 10 }, waveform: [1, 0, 1], url: "blob:full" }; await expect(analyzeSongPlayerAudio(audio)).resolves.toMatchObject({ sourceHash: "e".repeat(64) }); expect(browserAnalysis).toHaveBeenCalledWith(audio, undefined, undefined); });
  it("uses the real browser FFT when no native worker exists", async () => { capabilities.mockResolvedValueOnce({ desktop: false, analysis: true, nativeAnalysis: false, reasons: [] }); const audio = { metadata: { path: "full.wav", fileName: "full.wav", hash: "f".repeat(64), durationSeconds: 10, sampleRate: 44100, channels: 2, codec: "wav", fileSize: 10 }, waveform: [1, 0, 1], url: "blob:full" }; browserAnalysis.mockResolvedValueOnce({ sourceHash: audio.metadata.hash, durationSeconds: 10, chromaHopSeconds: 1, chroma: new Float32Array(120), fingerprintVersion: "v1", spectrogram: { version: 1, sourceHash: audio.metadata.hash, sampleRate: 1, fftSize: 1024, hopSize: 512, bands: 96, frameCount: 10, durationSeconds: 10, minDb: -80, maxDb: 0, data: new ArrayBuffer(960) } }); await expect(analyzeSongPlayerAudio(audio)).resolves.toMatchObject({ sourceHash: audio.metadata.hash }); expect(wait).not.toHaveBeenCalled(); });
});
