import { afterEach, describe, expect, it, vi } from "vitest";
import { createProject } from "@rbs/project-schema";
import { ensureSongPlayerRuntimeProject, rehydrateSongPlayerFullTrack, resetSongPlayerRuntimeForProjectReplacement } from "./song-player-lifecycle";
import { getSongPlayerRuntimeAsset, registerSongPlayerRuntimeAsset } from "./song-player-types";

const hash = "a".repeat(64); const audio = { metadata: { path: "/full.wav", fileName: "full.wav", hash, durationSeconds: 10, sampleRate: 44100, channels: 2, codec: "wav", fileSize: 100 }, waveform: [0], url: "data:audio/wav;base64,AA==" };
describe("song player lifecycle", () => {
  afterEach(() => resetSongPlayerRuntimeForProjectReplacement(`cleanup-${Math.random()}`));
  it("does not revoke runtime assets when the same project remounts", () => { resetSongPlayerRuntimeForProjectReplacement("p1"); registerSongPlayerRuntimeAsset("p1", { ...audio, assetId: "asset", kind: "fullTrack" }); ensureSongPlayerRuntimeProject("p1"); expect(getSongPlayerRuntimeAsset("asset")).not.toBeNull(); });
  it("rehydrates the selected persisted source and rejects stale content", async () => { const project = createProject(); project.project.id = "p2"; project.animation.songPlayer.assets = [{ id: "asset", kind: "fullTrack", source: "localImport", sourcePath: "/full.wav", fileName: "full.wav", mimeType: "wav", hash, durationSeconds: 10, sampleRate: 44100, channels: 2, fileSize: 100, provider: { sourceUrl: null, videoId: null, title: null } }]; project.animation.songPlayer.fullTrackAssetId = "asset"; resetSongPlayerRuntimeForProjectReplacement("p2"); expect(await rehydrateSongPlayerFullTrack(project, vi.fn().mockResolvedValue(audio))).toEqual(audio); await expect(rehydrateSongPlayerFullTrack(project, vi.fn().mockResolvedValue({ ...audio, metadata: { ...audio.metadata, hash: "b".repeat(64) } }))).rejects.toThrow(/cambiata/); });
  it("revokes a full track decoded by an obsolete project-open operation", async () => { const project = createProject(); project.project.id = "p3"; project.animation.songPlayer.assets = [{ id: "asset", kind: "fullTrack", source: "localImport", sourcePath: "/full.wav", fileName: "full.wav", mimeType: "wav", hash, durationSeconds: 10, sampleRate: 44100, channels: 2, fileSize: 100, provider: { sourceUrl: null, videoId: null, title: null } }]; project.animation.songPlayer.fullTrackAssetId = "asset"; let current = true; let resolve!: (value: typeof audio) => void; const revoke = vi.fn(); Object.defineProperty(URL, "revokeObjectURL", { configurable: true, value: revoke }); const loading = rehydrateSongPlayerFullTrack(project, () => new Promise((done) => { resolve = done; }), { isCurrent: () => current }); current = false; resolve({ ...audio, url: "blob:stale-open" }); await expect(loading).rejects.toMatchObject({ name: "AbortError" }); expect(revoke).toHaveBeenCalledWith("blob:stale-open"); expect(getSongPlayerRuntimeAsset("asset")).toBeNull(); });
  it("evicts and revokes the oldest runtime asset beyond the persisted cap", () => { resetSongPlayerRuntimeForProjectReplacement("p4"); const revoke = vi.fn(); Object.defineProperty(URL, "revokeObjectURL", { configurable: true, value: revoke }); for (let index = 0; index < 9; index += 1) registerSongPlayerRuntimeAsset("p4", { ...audio, assetId: `asset-${index}`, url: `blob:asset-${index}`, kind: "fullTrack" }); expect(getSongPlayerRuntimeAsset("asset-0")).toBeNull(); expect(getSongPlayerRuntimeAsset("asset-1")).not.toBeNull(); expect(getSongPlayerRuntimeAsset("asset-8")).not.toBeNull(); expect(revoke).toHaveBeenCalledWith("blob:asset-0"); });
});
