import { afterEach, describe, expect, it, vi } from "vitest";
import { createProject } from "@rbs/project-schema";
import { projectSongPlayerCube, resolveSongPlayerElementPalette, resolveSongPlayerImageFit, SongPlayerRenderer } from "./song-player-renderer";
import type { SongPlayerAnalysis } from "./song-player-types";

function contextMock() {
  return { fillStyle: "", strokeStyle: "", lineWidth: 1, globalAlpha: 1, imageSmoothingEnabled: true, font: "", createLinearGradient: vi.fn(() => ({ addColorStop: vi.fn() })), fillRect: vi.fn(), strokeRect: vi.fn(), drawImage: vi.fn(), save: vi.fn(), restore: vi.fn(), translate: vi.fn(), rotate: vi.fn(), beginPath: vi.fn(), moveTo: vi.fn(), lineTo: vi.fn(), closePath: vi.fn(), clip: vi.fn(), stroke: vi.fn(), fillText: vi.fn(), createImageData: vi.fn((width: number, height: number) => ({ data: new Uint8ClampedArray(width * height * 4), width, height })), putImageData: vi.fn() };
}
const analysis: SongPlayerAnalysis = { sourceHash: "a".repeat(64), durationSeconds: 3, chromaHopSeconds: 1, chroma: new Float32Array(36).fill(.4), fingerprintVersion: "v1", spectrogram: { version: 1, sourceHash: "a".repeat(64), sampleRate: 1, fftSize: 2, hopSize: 1, bands: 2, frameCount: 3, durationSeconds: 3, minDb: -80, maxDb: 0, data: Uint8Array.from([1, 10, 2, 20, 3, 30]).buffer } };
describe("song player renderer", () => {
  afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); });
  it("resolves cover and contain without stretching", () => { expect(resolveSongPlayerImageFit(100, 50, 100, 100, "contain")).toEqual({ x: 0, y: 25, width: 100, height: 50 }); expect(resolveSongPlayerImageFit(100, 50, 100, 100, "cover")).toEqual({ x: -50, y: 0, width: 200, height: 100 }); });
  it("renders the full matrix and exactly 48 deterministic spectrum bars", () => { const context = contextMock(); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D); const renderer = new SongPlayerRenderer(document.createElement("canvas")); renderer.setExportSize(540, 960); const settings = createProject().animation.songPlayer; renderer.update({ settings, analysis, playbackRange: { startSeconds: 1, endSeconds: 2, durationSeconds: 1 }, localTimeSeconds: 1 }); const first = [...renderer.lastBars]; expect(first).toHaveLength(48); expect(renderer.spectrogramCellCount).toBe(6); expect(context.drawImage).toHaveBeenCalled(); renderer.renderNow(1); expect(renderer.lastBars).toEqual(first); });
  it("uses independent manual palettes and opaque spectrogram pixels", () => { const context = contextMock(); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D); const settings = { ...createProject().animation.songPlayer, palette: ["#010101", "#020202", "#030303"] as [string, string, string], spectrumPaletteMode: "manual" as const, spectrumPalette: ["#111111", "#222222", "#333333"] as [string, string, string], spectrogramPaletteMode: "manual" as const, spectrogramPalette: ["#aa0000", "#00bb00", "#0000cc"] as [string, string, string] }; expect(resolveSongPlayerElementPalette(settings, "spectrum")).toEqual(settings.spectrumPalette); expect(resolveSongPlayerElementPalette(settings, "spectrogram")).toEqual(settings.spectrogramPalette); const renderer = new SongPlayerRenderer(document.createElement("canvas")); renderer.setExportSize(540, 960); renderer.update({ settings, analysis, playbackRange: { startSeconds: 1, endSeconds: 2, durationSeconds: 1 }, localTimeSeconds: 1 }); const imageData = context.putImageData.mock.calls[0]?.[0] as ImageData; expect(Array.from(imageData.data).filter((_, index) => index % 4 === 3)).toEqual(new Array(6).fill(255)); });
  it("resolves automatic element colors from the current cover palette", () => { const settings = { ...createProject().animation.songPlayer, palette: ["#101010", "#202020", "#303030"] as [string, string, string], spectrumPalette: ["#aaaaaa", "#bbbbbb", "#cccccc"] as [string, string, string], spectrogramPalette: ["#dddddd", "#eeeeee", "#ffffff"] as [string, string, string] }; expect(resolveSongPlayerElementPalette(settings, "spectrum")).toBe(settings.palette); expect(resolveSongPlayerElementPalette(settings, "spectrogram")).toBe(settings.palette); });
  it("projects a real time-dependent rotating cube deterministically", () => { expect(projectSongPlayerCube(1, 50, 50, 40)).toEqual(projectSongPlayerCube(1, 50, 50, 40)); expect(projectSongPlayerCube(2, 50, 50, 40)).not.toEqual(projectSongPlayerCube(1, 50, 50, 40)); expect(projectSongPlayerCube(1, 50, 50, 40)).toHaveLength(8); });
  it("renders three visible cube faces instead of a single flat polygon", () => { const context = contextMock(); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D); const renderer = new SongPlayerRenderer(document.createElement("canvas")); renderer.setExportSize(540, 960); renderer.update({ settings: { ...createProject().animation.songPlayer, coverStyle: "cube" }, playbackRange: { startSeconds: 0, endSeconds: 3, durationSeconds: 3 }, localTimeSeconds: 1 }); expect(renderer.lastCubeVertices).toHaveLength(8); expect(context.clip).toHaveBeenCalledTimes(3); });
  it("restores a responsive DPR-aware backing store from the rendered canvas size", () => { const context = contextMock(); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D); vi.spyOn(window, "devicePixelRatio", "get").mockReturnValue(2); const canvas = document.createElement("canvas"); vi.spyOn(canvas, "getBoundingClientRect").mockReturnValue({ width: 320, height: 180 } as DOMRect); const renderer = new SongPlayerRenderer(canvas); renderer.restorePreviewSize(); expect(canvas.width).toBe(640); expect(canvas.height).toBe(360); });
  it("redraws loaded images and prepare waits before export", async () => { const context = contextMock(); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D); class FakeImage { complete = false; naturalWidth = 100; naturalHeight = 100; onload: (() => void) | null = null; onerror: (() => void) | null = null; set src(_value: string) { queueMicrotask(() => { this.complete = true; this.onload?.(); }); } } vi.stubGlobal("Image", FakeImage); const renderer = new SongPlayerRenderer(document.createElement("canvas")); const settings = { ...createProject().animation.songPlayer, coverImageUrl: "data:image/png;base64,AAAA" }; renderer.update({ settings, playbackRange: { startSeconds: 0, endSeconds: 1, durationSeconds: 1 }, localTimeSeconds: 0 }); await renderer.prepare(); expect(context.drawImage).toHaveBeenCalled(); });
  it("never draws a failed cover and rejects prepare", async () => { const context = contextMock(); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D); class FailedImage { complete = false; naturalWidth = 100; naturalHeight = 100; onload: (() => void) | null = null; onerror: (() => void) | null = null; set src(_value: string) { queueMicrotask(() => this.onerror?.()); } } vi.stubGlobal("Image", FailedImage); const renderer = new SongPlayerRenderer(document.createElement("canvas")); const settings = { ...createProject().animation.songPlayer, coverImageUrl: "data:image/png;base64,BROKEN" }; renderer.update({ settings, playbackRange: { startSeconds: 0, endSeconds: 1, durationSeconds: 1 }, localTimeSeconds: 0 }); await expect(renderer.prepare()).rejects.toThrow(/non caricabile/); renderer.renderNow(0); expect(context.drawImage).not.toHaveBeenCalled(); });
  it("rejects every pending prepare when disposed", async () => { const context = contextMock(); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(context as unknown as CanvasRenderingContext2D); class PendingImage { complete = false; naturalWidth = 0; naturalHeight = 0; onload: (() => void) | null = null; onerror: (() => void) | null = null; set src(_value: string) {} } vi.stubGlobal("Image", PendingImage); const renderer = new SongPlayerRenderer(document.createElement("canvas")); const settings = { ...createProject().animation.songPlayer, coverImageUrl: "data:image/png;base64,PENDING" }; renderer.update({ settings, playbackRange: { startSeconds: 0, endSeconds: 1, durationSeconds: 1 }, localTimeSeconds: 0 }); const pending = renderer.prepare(); renderer.dispose(); await expect(pending).rejects.toThrow(/dismesso/); await expect(renderer.prepare()).rejects.toThrow(/dismesso/); });
});
