import { beforeEach, describe, expect, it, vi } from "vitest";
const { invoke } = vi.hoisted(() => ({ invoke: vi.fn() }));
vi.mock("@tauri-apps/api/core", () => ({ invoke, isTauri: () => true }));
import { cancelSongPlayerJob, decodeSongPlayerTerminalResult, ensureSongPlayerRuntime, getSongPlayerRuntimeSetup, startSongPlayerJob, subscribeSongPlayerNativeActivity, waitForSongPlayerJob } from "./song-player-native";

describe("song player native facade", () => {
  beforeEach(() => invoke.mockReset().mockResolvedValue({ jobId: "job-1", status: "completed" }));
  it("sends the strict match DTO expected by Tauri", async () => { await startSongPlayerJob({ kind: "match", referencePath: "/music/full.wav", targetPath: "/music/fragment.wav" }); expect(invoke).toHaveBeenCalledWith("song_player_start_job", { request: { kind: "match", referencePath: "/music/full.wav", targetPath: "/music/fragment.wav" } }); });
  it("sends analysis without frontend-only hashes", async () => { await startSongPlayerJob({ kind: "analyze", inputPath: "/music/full.wav" }); expect(invoke).toHaveBeenCalledWith("song_player_start_job", { request: { kind: "analyze", inputPath: "/music/full.wav" } }); });
  it("sends the dedicated vocal-separation DTO", async () => { await startSongPlayerJob({ kind: "separateVocals", inputPath: "/music/full.wav" }); expect(invoke).toHaveBeenCalledWith("song_player_start_job", { request: { kind: "separateVocals", inputPath: "/music/full.wav" } }); });
  it("starts and polls automatic runtime setup through native commands", async () => { invoke.mockResolvedValueOnce({ status: "installing", progress: 42, message: "Installazione Demucs", error: null, updatedAtMs: 1 }).mockResolvedValueOnce({ status: "ready", progress: 100, message: "Pronto", error: null, updatedAtMs: 2 });await expect(ensureSongPlayerRuntime()).resolves.toMatchObject({status:"installing",progress:42});await expect(getSongPlayerRuntimeSetup()).resolves.toMatchObject({status:"ready",progress:100});expect(invoke.mock.calls.slice(0,2)).toEqual([["song_player_ensure_runtime",undefined],["song_player_get_runtime_setup",undefined]]); });
  it("rejects malformed terminal match payloads and normalizes valid ones", () => { expect(() => decodeSongPlayerTerminalResult("match", { status: "matched" })).toThrow(/incompleto/); expect(decodeSongPlayerTerminalResult("match", { status: "matched", offsetSeconds: 2.5, confidence: .8, candidates: [{ offsetSeconds: 2.5, similarity: .7 }] })).toEqual({ kind: "match", status: "matched", offsetMs: 2500, confidence: .8, candidates: [{ offsetMs: 2500, score: .7 }] }); });
  it("requires and returns the canonical YouTube URL produced by the worker", () => { expect(() => decodeSongPlayerTerminalResult("download", { path: "/music/full.wav" })).toThrow(/URL canonico/); expect(decodeSongPlayerTerminalResult("download", { path: "/music/full.wav", youtubeUrl: "https://www.youtube.com/watch?v=abc", videoId: "abc", title: "Track" })).toEqual({ kind: "download", path: "/music/full.wav", sourceUrl: "https://www.youtube.com/watch?v=abc", videoId: "abc", title: "Track" }); });
  it("enforces and publishes a shared frontend job lease until terminal or cancelled", async () => { const activity: boolean[] = []; const unsubscribe = subscribeSongPlayerNativeActivity((active) => activity.push(active)); invoke.mockResolvedValueOnce({ jobId: "job-running", status: "queued" }); await startSongPlayerJob({ kind: "analyze", inputPath: "/music/full.wav" }); await expect(startSongPlayerJob({ kind: "match", referencePath: "/music/full.wav", targetPath: "/music/part.wav" })).rejects.toThrow(/già in corso/); invoke.mockResolvedValueOnce({ jobId: "job-running", status: "cancelled" }); await cancelSongPlayerJob("job-running"); await expect(startSongPlayerJob({ kind: "analyze", inputPath: "/music/full.wav" })).resolves.toMatchObject({ status: "completed" }); unsubscribe(); expect(activity).toEqual([true, false, true, false]); });
  it("cancels best-effort and releases the shared lease when polling and cancellation both fail", async () => { invoke.mockResolvedValueOnce({ jobId: "job-stale", status: "queued" }).mockRejectedValueOnce(new Error("poll failed")).mockRejectedValueOnce(new Error("cancel failed")).mockResolvedValueOnce({ jobId: "job-next", status: "completed" }); await startSongPlayerJob({ kind: "analyze", inputPath: "/music/full.wav" }); await expect(waitForSongPlayerJob("job-stale", { pollMs: 25 })).rejects.toThrow("poll failed"); await expect(startSongPlayerJob({ kind: "analyze", inputPath: "/music/next.wav" })).resolves.toMatchObject({ jobId: "job-next" }); expect(invoke).toHaveBeenCalledWith("song_player_cancel_job", { jobId: "job-stale" }); });
  it("cancels and releases the lease when polling is aborted before the first request", async () => { invoke.mockResolvedValueOnce({ jobId: "job-aborted", status: "queued" }).mockResolvedValueOnce({ jobId: "job-aborted", status: "cancelled" }).mockResolvedValueOnce({ jobId: "job-after-abort", status: "completed" }); await startSongPlayerJob({ kind: "analyze", inputPath: "/music/full.wav" }); const controller = new AbortController(); controller.abort(); await expect(waitForSongPlayerJob("job-aborted", { signal: controller.signal })).rejects.toMatchObject({ name: "AbortError" }); await expect(startSongPlayerJob({ kind: "analyze", inputPath: "/music/next.wav" })).resolves.toMatchObject({ jobId: "job-after-abort" }); });
});
