import type { UiLanguage } from "./ui-preferences";

/**
 * Compatibility catalogue for UI written before the bilingual shell existed.
 * Keep technical/product names unchanged and translate longest phrases first.
 */
const PAIRS: ReadonlyArray<readonly [string, string]> = [
  ["MLSM usa H.264 quando supportato e, per sorgenti oltre 4K, passa automaticamente a H.265/HEVC senza ridurre la risoluzione.", "MLSM uses H.264 when supported and, for sources above 4K, automatically switches to H.265/HEVC without reducing resolution."],
  ["passa automaticamente a", "automatically switches to"],
  ["sorgenti oltre 4K", "sources above 4K"],
  ["quando supportato", "when supported"],
  ["ridurre la risoluzione", "reducing resolution"],
  ["Nessun encoder MP4 compatibile con la risoluzione originale", "No MP4 encoder is compatible with the original resolution"],
  ["Sono stati verificati H.264/AVC e H.265/HEVC.", "H.264/AVC and H.265/HEVC were checked."],
  ["non è disponibile per la risoluzione originale", "is not available for the original resolution"],
  ["L’encoder", "The encoder"],
  ["Carica un brano intero. L’intro dura", "Upload a full track. The intro lasts"],
  ["Timbri deterministici, nessun comment perso", "Deterministic stamps, no comments lost"],
  ["Completo · nessun taglio", "Full · no cropping"],
  ["Separatore prima/dopo", "Before/after separator"],
  ["Renderer TypeScript/Canvas nativo · nessun host C++ o repository incorporato", "Native TypeScript/Canvas renderer · no C++ host or embedded repository"],
  ["Nessun effetto attivo.", "No active effects."],
  ["● Download soltanto al primo utilizzo · cache locale persistente · nessun peso nel progetto", "● Download on first use only · persistent local cache · no project payload"],
  ["Elaborazione locale · nessun audio inviato online", "Local processing · no audio sent online"],
  ["Nessun effetto. Aggiungilo qui o trascinalo dalla libreria nella corsia Effetti.", "No effects. Add one here or drag it from the library to the Effects lane."],
  ["Riordina i livelli: quello più in alto viene composto sopra gli altri. Nessun livello video ha un ruolo principale o overlay.", "Reorder layers: the topmost one is composited above the others. No video layer has a fixed main or overlay role."],
  ["Carica i media nel pool a sinistra e usa “Aggiungi in timeline”: poi trascina i bordi per estenderli e il corpo per spostarli.", "Load media into the pool on the left and use “Add to timeline”; then drag the edges to extend clips and the body to move them."],
  ["Il catalogo Transitions è vuoto: nessun effetto generico viene mostrato al suo posto.", "The Transitions catalogue is empty: no generic effect is shown in its place."],
  ["Backend video artifact non disponibile in questa build: nessun risultato simulato.", "Video artifact backend unavailable in this build: no simulated result."],
  ["Carica i media nel pool e trascinali in timeline per iniziare il montaggio.", "Load media into the pool and drag them onto the timeline to start editing."],
  ["Carica lo spezzone usato dalla clip e, separatamente, la canzone completa.", "Load the clip fragment and, separately, the full song."],
  ["Anteprima ed export campionano la stessa analisi FFT al tempo esatto del fotogramma.", "Preview and export sample the same FFT analysis at the exact frame time."],
  ["Applica modello e regolazioni correnti a più immagini in sequenza.", "Apply the current model and adjustments to multiple images in sequence."],
  ["Aggiungi una o più foto per creare una coda batch.", "Add one or more photos to create a batch queue."],
  ["I video restano nel flusso singolo.", "Videos remain in the single-item workflow."],
  ["Carica un’immagine. Il rilevatore conserva tutte le categorie COCO supportate e ogni cerchio può essere rilevato o posizionato manualmente.", "Upload an image. The detector keeps every supported COCO category, and each circle can be detected or positioned manually."],
  ["Una sensibilità maggiore riduce la soglia di confidenza e può includere più categorie supportate.", "Higher sensitivity lowers the confidence threshold and may include more supported categories."],
  ["La modifica non riavvia automaticamente il rilevamento.", "Changing it does not rerun detection automatically."],
  ["Nessun oggetto salvato. Carica un’immagine per avviare il rilevamento.", "No objects saved. Upload an image to run detection."],
  ["Usa la palette dell’oggetto selezionato.", "Uses the selected object's palette."],
  ["Le bande orizzontali restano ferme mentre l’anello radiale ruota.", "Fixed horizontal bands stay level while the radial ring rotates."],
  ["Gli impulsi sinistro e destro indipendenti vengono specchiati automaticamente con sorgenti mono.", "Independent left/right pulses mirror automatically when the source is mono."],
  ["Usa la traccia cue del progetto e la tipografia Pro Subtitles nel cerchio dell’oggetto.", "Uses the project cue track and Pro Subtitles typography inside this object circle."],
  ["Adattamento nativo del concetto Winamp/MilkDrop", "Native adaptation of the Winamp/MilkDrop concept"],
  ["usa le 48 bande FFT reali di MLSM", "uses MLSM’s 48 real FFT bands"],
  ["resta sincronizzato durante seek ed export", "stays synchronized during seeking and export"],
  ["non richiede projectM o componenti Windows", "does not require projectM or Windows components"],
  ["Carica foto o video di sfondo", "Upload a background image or video"],
  ["Carica immagine o video di sfondo", "Upload a background image or video"],
  ["Carica un video per iniziare", "Upload a video to begin"],
  ["Carica una foto o un video", "Upload a photo or video"],
  ["Carica foto o video", "Upload photos or videos"],
  ["Carica sorgente Upscaler", "Upload Upscaler source"],
  ["Carica video Frame Booster", "Upload Frame Booster video"],
  ["Carica canzone completa", "Upload full song"],
  ["Carica brano intero", "Upload full track"],
  ["Carica spezzone clip", "Upload clip fragment"],
  ["Carica cartella commenti", "Upload comments folder"],
  ["Carica immagini commenti", "Upload comment images"],
  ["Carica video con watermark", "Upload watermarked video"],
  ["Carica fotografia senza watermark", "Upload photo without watermark"],
  ["Carica fotografia pulita", "Upload clean photo"],
  ["Carica video verticale", "Upload vertical video"],
  ["Carica immagine laterale", "Upload side image"],
  ["Carica copertina", "Upload cover"],
  ["Carica immagine principale", "Upload main image"],
  ["Carica immagine di sfondo", "Upload background image"],
  ["Carica immagine", "Upload image"],
  ["Carica video", "Upload video"],
  ["Carica brano", "Upload track"],
  ["Carica audio", "Upload audio"],
  ["Carica immagine Auto Detector", "Upload Auto Detector image"],
  ["Carica immagine", "Upload image"],
  ["Lettura immagine…", "Reading image…"],
  ["Avvio rilevamento…", "Starting detection…"],
  ["Sensibilità rilevamento", "Detection sensitivity"],
  ["Rilevamento non riuscito", "Detection failed"],
  ["Oggetti rilevati", "Detected objects"],
  ["Oggetto rilevato", "Detected object"],
  ["Rileva di nuovo", "Detect again"],
  ["Seleziona un oggetto", "Select an object"],
  ["Ripristina palette immagine", "Reset to image palette"],
  ["Automatica dall’oggetto", "Automatic from object"],
  ["Automatica dall’immagine", "Auto from image"],
  ["Manuale per istanza", "Manual per instance"],
  ["Sorgente palette", "Palette source"],
  ["Velocità rotazione", "Rotation speed"],
  ["Particelle collisione", "Collision particles"],
  ["Spettro radiale", "Radial spectrum"],
  ["Spettro centrale", "Center spectrum"],
  ["Lati stereo", "Stereo sides"],
  ["Cerchio manuale", "Manual circle"],
  ["Cerchi Circular Spectrum", "Circular Spectrum circles"],
  ["Composizione globale", "Global composition"],
  ["Composizione centrale pulita", "Clean central composition"],
  ["Composizione Video Editor", "Video Editor composition"],
  ["Composizione Comments Invasion", "Comments Invasion composition"],
  ["Controlli riproduzione a tutto schermo", "Fullscreen playback controls"],
  ["Controlli anteprima zona rimozione", "Removal preview controls"],
  ["Anteprima zona rimozione", "Removal area preview"],
  ["Anteprima non disponibile", "Preview unavailable"],
  ["Anteprima immagine usata per estrarre la palette", "Image preview used to extract the palette"],
  ["Anteprima leggera", "Lightweight preview"],
  ["export ricostruito alla risoluzione finale", "export rebuilt at final resolution"],
  ["Preview ed export condividono tempi e posizioni", "Preview and export share timing and positions"],
  ["Aggiungi endpoint", "Add endpoint"],
  ["Verifica endpoint e carica modelli", "Check endpoints and load models"],
  ["Attività endpoint remoti", "Remote endpoint activity"],
  ["Alcuni endpoint non rispondono", "Some endpoints are not responding"],
  ["Continua con", "Continue with"],
  ["Checkpoint segmenti", "Segment checkpoints"],
  ["Checkpoint video", "Video checkpoint"],
  ["Svuota tutta la cache video", "Clear all video cache"],
  ["Conferma pulizia cache video", "Confirm video cache cleanup"],
  ["Conferma eliminazione", "Confirm deletion"],
  ["Come vuoi gestire la cache?", "How do you want to handle the cache?"],
  ["Riprendi cache compatibile", "Resume compatible cache"],
  ["Riparti da zero", "Start from scratch"],
  ["Aggiungi altre foto al batch Upscaler", "Add more photos to the Upscaler batch"],
  ["Batch foto", "Photo batch"],
  ["Cambia destinazione", "Change destination"],
  ["Destinazione", "Destination"],
  ["Avvia batch", "Start batch"],
  ["Riprova selezionati", "Retry selected"],
  ["Seleziona tutti", "Select all"],
  ["Deseleziona tutti", "Deselect all"],
  ["Rimuovi selezionati", "Remove selected"],
  ["Aggiungi in timeline", "Add to timeline"],
  ["Chiudi i vuoti della traccia", "Close track gaps"],
  ["Chiudi i vuoti", "Close gaps"],
  ["Duplica clip", "Duplicate clip"],
  ["Taglia sul playhead", "Cut at playhead"],
  ["Sposta sul playhead", "Move to playhead"],
  ["Sincronizza audio e video", "Synchronize audio and video"],
  ["Allinea per frame", "Align by frame"],
  ["Aggiungi effetti alla clip", "Add effects to clip"],
  ["Effetti della clip", "Clip effects"],
  ["Clip selezionata", "Selected clip"],
  ["Azioni clip", "Clip actions"],
  ["Traccia audio", "Audio track"],
  ["Livello video", "Video layer"],
  ["Audio della clip", "Clip audio"],
  ["Audio disattivato", "Audio disabled"],
  ["Disattiva audio clip", "Mute clip audio"],
  ["Attiva ombra immagine", "Enable image shadow"],
  ["Colore ombra immagine", "Image shadow color"],
  ["Distanza ombra immagine", "Image shadow distance"],
  ["Diffusione ombra immagine", "Image shadow blur"],
  ["Direzione ombra immagine", "Image shadow direction"],
  ["Aggiungi keyframe", "Add keyframe"],
  ["Porta su", "Move up"],
  ["Porta giù", "Move down"],
  ["Annulla modifica Video Editor", "Undo Video Editor change"],
  ["Annulla elaborazione", "Cancel processing"],
  ["Apri Pro Subtitles", "Open Pro Subtitles"],
  ["Apri assistente applicazione", "Open application assistant"],
  ["Chiudi assistente", "Close assistant"],
  ["Azzera memoria assistente", "Clear assistant memory"],
  ["Domanda per l’assistente", "Question for the assistant"],
  ["Chiedi come usare l’applicazione…", "Ask how to use the application…"],
  ["Cosa puoi fare?", "What can you do?"],
  ["Come esporto?", "How do I export?"],
  ["Da dove inizio?", "Where do I start?"],
  ["Blocchi manuali e libreria", "Manual blocks and library"],
  ["Inserisci blocco al playhead", "Insert block at playhead"],
  ["Applica anche animazione e stile", "Also apply animation and style"],
  ["Rilevamento automatico", "Automatic detection"],
  ["Lingua Whisper", "Whisper language"],
  ["Caratteri massimi per riga", "Maximum characters per line"],
  ["Durata massima sottotitolo", "Maximum subtitle duration"],
  ["Velocità massima lettura", "Maximum reading speed"],
  ["Animazione predefinita", "Default animation"],
  ["Dimensione globale", "Global size"],
  ["Posizione globale", "Global position"],
  ["Opacità globale", "Global opacity"],
  ["Stile per parola", "Per-word style"],
  ["Dividi frase", "Split phrase"],
  ["File sottotitoli", "Subtitle file"],
  ["Output per il montaggio", "Editing output"],
  ["Colore di fondo", "Background color"],
  ["Brano caricato + effetti meccanici", "Loaded track + mechanical effects"],
  ["Solo effetti meccanici", "Mechanical effects only"],
  ["Audio export Cassette Desk", "Cassette Desk export audio"],
  ["BPM e tonalità", "BPM and key"],
  ["BPM manuale", "Manual BPM"],
  ["Analisi armonica automatica", "Automatic harmonic analysis"],
  ["Analisi voce reale", "Real vocal analysis"],
  ["Colori indipendenti", "Independent colors"],
  ["Ambiente fuori dalla finestra", "Environment outside the window"],
  ["Durata intro", "Intro duration"],
  ["Carica immagine Cassette Desk", "Upload Cassette Desk image"],
  ["Carica cover / poster", "Upload cover / poster"],
  ["Carica poster Teddy Sing", "Upload Teddy Sing poster"],
  ["Carica cover del brano", "Upload track cover"],
  ["Elementi della base", "Backing-track elements"],
  ["Direzione artistica", "Art direction"],
  ["Sfondo e ambiente", "Background and environment"],
  ["Binari e collegamenti", "Rails and connections"],
  ["Colori batteria per tipo", "Drum colors by type"],
  ["Selezione e sostituzione", "Selection and replacement"],
  ["Sorgente", "Source"], ["Ingresso", "Input"], ["Uscita", "Output"],
  ["Impostazioni", "Settings"], ["Elementi", "Elements"], ["Comportamento", "Behavior"],
  ["Animazione", "Animation"], ["Effetti", "Effects"], ["Effetto", "Effect"],
  ["Colore", "Color"], ["Colori", "Colors"], ["Sfondo", "Background"],
  ["Immagine", "Image"], ["Fotografia", "Photo"], ["Video", "Video"], ["Audio", "Audio"],
  ["Traccia", "Track"], ["Clip", "Clip"], ["Oggetto", "Object"], ["Oggetti", "Objects"],
  ["Palette", "Palette"], ["Titolo", "Title"], ["Artista", "Artist"],
  ["Durata", "Duration"], ["Dimensione", "Size"], ["Dimensioni", "Dimensions"],
  ["Larghezza", "Width"], ["Altezza", "Height"], ["Posizione", "Position"],
  ["Rotazione", "Rotation"], ["Scala", "Scale"], ["Opacità", "Opacity"],
  ["Contrasto", "Contrast"], ["Luminosità", "Brightness"], ["Saturazione", "Saturation"],
  ["Intensità", "Intensity"], ["Velocità", "Speed"], ["Sensibilità", "Sensitivity"],
  ["Automatico", "Automatic"], ["Automatica", "Automatic"], ["Manuale", "Manual"],
  ["Attivo", "Enabled"], ["Attiva", "Enable"], ["Disattiva", "Disable"],
  ["Abilitato", "Enabled"], ["Abilitata", "Enabled"], ["Nessuno", "None"], ["Nessuna", "None"], ["Nessun", "No"],
  ["Carica", "Upload"], ["Seleziona", "Select"], ["Aggiungi", "Add"], ["Rimuovi", "Remove"], ["Elimina", "Delete"],
  ["Applica", "Apply"], ["Cambia", "Change"], ["Riprova", "Retry"], ["Ripristina", "Reset"],
  ["Avvia", "Start"], ["Avvio", "Starting"], ["Annulla", "Cancel"], ["Chiudi", "Close"],
  ["Apri", "Open"], ["Salva", "Save"], ["Esporta", "Export"], ["Anteprima", "Preview"],
  ["Riproduci", "Play"], ["Pausa", "Pause"], ["Ferma", "Stop"], ["Elaborazione", "Processing"],
  ["Caricamento", "Loading"], ["Preparazione", "Preparing"], ["Completato", "Completed"],
  ["Errore", "Error"], ["Non disponibile", "Unavailable"], ["Da verificare", "To be checked"],
  ["Locale", "Local"], ["Remoto", "Remote"], ["Cartella", "Folder"], ["Modello", "Model"],
  ["Fotogrammi", "Frames"], ["Fotogramma", "Frame"], ["Risoluzione", "Resolution"],
  ["Rapporto", "Aspect ratio"], ["Metodo", "Method"], ["Target", "Target"],
  ["Posizionamento", "Placement"], ["Persona", "Person"], ["Soglia", "Threshold"],
  ["Bilanciata", "Balanced"], ["Precisa", "Precise"], ["Alta", "High"],
  ["Ferma", "Stopped"], ["Sottotitoli", "Subtitles"], ["Anima", "Animate"],
  ["Strumenti AI", "AI Tools"], ["Regola", "Adjust"], ["Rilevamento", "Detection"],
  ["Rilevatore", "Detector"], ["Cerchio", "Circle"], ["Centro", "Center"],
  ["Oggetti rilevati", "Detected objects"], ["Oggetto rilevato", "Detected object"],
  ["il", "the"], ["la", "the"], ["lo", "the"], ["i", "the"], ["gli", "the"], ["le", "the"],
  ["un", "a"], ["uno", "a"], ["una", "an"], ["di", "of"], ["del", "of the"],
  ["della", "of the"], ["dello", "of the"], ["dei", "of the"], ["delle", "of the"],
  ["da", "from"], ["dal", "from the"], ["dalla", "from the"], ["dall", "from the"],
  ["al", "to the"], ["alla", "to the"], ["nel", "in the"], ["nella", "in the"],
  ["nello", "in the"], ["sul", "on the"], ["sulla", "on the"], ["con", "with"],
  ["senza", "without"], ["per", "for"], ["e", "and"], ["ed", "and"], ["o", "or"],
  ["oppure", "or"], ["anche", "also"], ["non", "not"], ["solo", "only"],
  ["soltanto", "only"], ["ogni", "each"], ["tutti", "all"], ["tutto", "everything"],
  ["questa", "this"], ["questo", "this"], ["stessa", "same"], ["stesso", "same"],
  ["prima", "before"], ["dopo", "after"], ["poi", "then"], ["quando", "when"],
  ["se", "if"], ["come", "as"], ["qui", "here"], ["sopra", "above"],
  ["sotto", "below"], ["sinistra", "left"], ["destra", "right"], ["alto", "top"],
  ["basso", "bottom"], ["primo", "first"], ["secondo", "second"], ["fino", "up to"],
  ["più", "more"], ["puoi", "you can"], ["può", "can"], ["viene", "is"],
  ["vengono", "are"], ["verrà", "will be"], ["resta", "remains"], ["restano", "remain"],
  ["usa", "uses"], ["usano", "use"], ["usato", "used"], ["richiede", "requires"],
  ["conserva", "preserves"], ["condividono", "share"], ["mostra", "shows"],
  ["scegli", "choose"], ["trascina", "drag"], ["riempi", "fill"], ["ruota", "rotates"],
  ["selezione", "selection"], ["selezionata", "selected"], ["principale", "main"],
  ["originale", "original"], ["originali", "original"], ["finale", "final"],
  ["completo", "complete"], ["completa", "complete"], ["intero", "full"],
  ["verticale", "vertical"], ["orizzontale", "horizontal"], ["centrale", "central"],
  ["laterale", "side"], ["globale", "global"], ["locale", "local"], ["reale", "real"],
  ["reali", "real"], ["pulita", "clean"], ["trasparente", "transparent"],
  ["disponibile", "available"], ["attivi", "active"], ["consigliato", "recommended"],
  ["massima", "maximum"], ["preciso", "precise"], ["fisica", "physical"],
  ["progetto", "project"], ["scena", "scene"], ["formato", "format"], ["modalità", "mode"],
  ["nome", "name"], ["tipo", "type"], ["testo", "text"], ["frase", "phrase"],
  ["frasi", "phrases"], ["parola", "word"], ["parole", "words"], ["stile", "style"],
  ["font", "font"], ["commenti", "comments"], ["commento", "comment"], ["immagini", "images"],
  ["bande", "bands"], ["barre", "bars"], ["segmenti", "segments"], ["segmento", "segment"],
  ["spettro", "spectrum"], ["spettrogramma", "spectrogram"], ["canzone", "song"],
  ["brano", "track"], ["spezzone", "fragment"], ["voce", "vocals"], ["vocale", "vocal"],
  ["musica", "music"], ["tonalità", "key"], ["analisi", "analysis"],
  ["regolazioni", "adjustments"], ["fusione", "blending"], ["allineamento", "alignment"],
  ["qualità", "quality"], ["controlli", "controls"], ["pannello", "panel"],
  ["libreria", "library"], ["blocco", "block"], ["blocchi", "blocks"], ["punto", "point"],
  ["bordo", "edge"], ["bordi", "edges"], ["cornice", "frame"], ["ombra", "shadow"],
  ["ombre", "shadows"], ["luce", "light"], ["particelle", "particles"],
  ["canale", "channel"], ["ingresso", "input"], ["uscita", "output"],
  ["risultato", "result"], ["confronto", "comparison"], ["dettaglio", "detail"],
  ["percorso", "path"], ["movimento", "motion"], ["battuta", "beat"], ["battute", "beats"],
  ["preparazione", "preparing"], ["lettura", "reading"], ["verifica", "check"],
  ["adattamento", "fit"], ["copertina", "cover"], ["sfera", "sphere"], ["cubo", "cube"],
  ["vetro", "glass"], ["stanza", "room"], ["finestra", "window"], ["area", "area"]
  , ["che", "that"], ["cui", "which"], ["mentre", "while"], ["perché", "because"],
  ["quindi", "therefore"], ["deve", "must"], ["devono", "must"], ["premi", "press"],
  ["clicca", "click"], ["crea", "creates"], ["creati", "created"], ["cambia", "changes"],
  ["mantiene", "keeps"], ["evita", "avoids"], ["permette", "allows"], ["supporta", "supports"],
  ["possono", "can"], ["sono", "are"], ["saranno", "will be"], ["essere", "be"], ["è", "is"],
  ["disponibili", "available"], ["mancante", "missing"], ["mancanti", "missing"],
  ["pronto", "ready"], ["pronta", "ready"], ["attesa", "waiting"], ["corretta", "correct"],
  ["corretto", "correct"], ["circa", "about"], ["separata", "separated"], ["estratta", "extracted"],
  ["impostata", "set"], ["salvato", "saved"], ["salvati", "saved"], ["salvate", "saved"],
  ["raggiungibile", "reachable"], ["raggiungibili", "reachable"], ["avanzamento", "progress"],
  ["tentativi", "attempts"], ["tastiera", "keyboard"], ["timbri", "stamps"], ["perso", "lost"],
  ["taglio", "crop"], ["tagli", "cuts"], ["composizione", "composition"], ["tipografica", "typographic"],
  ["scheda", "tab"], ["sostituirne", "replace its"], ["sostituzione", "replacement"],
  ["definisci", "define"], ["raggio", "beam"], ["due", "two"], ["punti", "points"],
  ["superficie", "surface"], ["coordinate", "coordinates"], ["rifinite", "refined"],
  ["collegamento", "connection"], ["collegamenti", "connections"], ["aggiornando", "updating"],
  ["geometria", "geometry"], ["materiale", "material"], ["scelta", "choice"], ["riguarda", "concerns"],
  ["parte", "starts"], ["combinata", "combined"], ["altri", "other"], ["altre", "other"],
  ["tipi", "types"], ["famiglie", "families"], ["generatore", "generator"],
  ["modificabili", "editable"], ["singolarmente", "individually"], ["grande", "large"],
  ["incorporata", "embedded"], ["definirà", "will define"], ["automaticamente", "automatically"],
  ["volantini", "flyers"], ["balla", "dances"], ["cammina", "walks"], ["originari", "original"],
  ["mano", "manually"], ["migliore", "best"], ["quasi", "almost"], ["integralmente", "fully"],
  ["valorizza", "enhances"], ["lati", "sides"], ["direttamente", "directly"], ["copia", "copy"],
  ["consiglio", "suggestion"], ["ripulisce", "cleans"], ["riallinea", "realigns"],
  ["spostare", "move"], ["arbitrariamente", "arbitrarily"], ["utilizzo", "use"],
  ["persistente", "persistent"], ["peso", "weight"], ["lunghezza", "length"],
  ["indicativa", "approximate"], ["incolla", "paste"], ["attivare", "enable"],
  ["punteggiatura", "punctuation"], ["righe", "lines"], ["enfasi", "emphasis"],
  ["ripetizioni", "repetitions"], ["meccaniche", "mechanical"], ["risalto", "focus"],
  ["chiave", "key"], ["tutte", "all"], ["foto", "photos"], ["inviate", "sent"],
  ["distribuisce", "distributes"], ["parallelo", "parallel"], ["tra", "among"],
  ["rimesso", "restored"], ["lavoro", "job"], ["link", "links"], ["insieme", "together"],
  ["separati", "separated"], ["spazi", "spaces"], ["virgole", "commas"], ["duplicati", "duplicates"],
  ["ignorati", "ignored"], ["invio", "enter"], ["userà", "will use"], ["espongono", "provide"],
  ["farà", "will ask"], ["approvare", "approve"], ["esclusione", "exclusion"],
  ["aggiuntivi", "additional"], ["ricevuto", "received"], ["localmente", "locally"],
  ["cade", "fails"], ["riprendere", "resume"], ["rifare", "redo"], ["parti", "parts"],
  ["già", "already"], ["eliminare", "delete"], ["sorgenti", "sources"], ["risultati", "results"],
  ["inviato", "sent"], ["riprodotto", "played"], ["inserito", "inserted"], ["esportato", "exported"],
  ["contenuti", "content"], ["possiedi", "own"], ["diritti", "rights"],
  ["autorizzazione", "permission"], ["disponibilità", "availability"], ["condizioni", "terms"],
  ["piattaforma", "platform"], ["variare", "vary"], ["decodificato", "decoded"],
  ["ricodificato", "re-encoded"], ["consegnato", "delivered"], ["rileva", "detects"],
  ["proprietà", "ownership"], ["quali", "which"], ["sei", "are"], ["autorizzato", "authorized"],
  ["intervenire", "modify"], ["rappresentare", "represent"], ["inquadratura", "shot"],
  ["vedere", "see"], ["tracce", "tracks"], ["nuovi", "new"], ["obiettivo", "target"],
  ["morbido", "soft"], ["pause", "pauses"], ["vocali", "vocal"], ["decidono", "determine"],
  ["rimangono", "remain"], ["vincoli", "constraints"], ["mostrerà", "will show"],
  ["stima", "estimate"], ["attendibile", "reliable"], ["confronterà", "will compare"],
  ["appartengono", "belong"], ["esattamente", "exactly"], ["nuovo", "new"],
  ["ordine", "order"], ["ricostruisce", "rebuilds"], ["rimette", "restores"],
  ["aggiungilo", "add it"], ["trascinalo", "drag it"], ["corsia", "lane"],
  ["riordina", "reorder"], ["livelli", "layers"], ["quello", "the one"], ["composto", "composited"],
  ["catalogo", "catalog"], ["vuoto", "empty"], ["generico", "generic"], ["mostrato", "shown"],
  ["posto", "place"], ["simulato", "simulated"], ["intro", "intro"],
  ["deterministici", "deterministic"], ["nativo", "native"], ["incorporato", "embedded"],
  ["imposta", "sets"], ["seconda", "second"], ["ha", "has"], ["ruolo", "role"],
  ["suo", "its"], ["estenderli", "extend them"], ["corpo", "body"], ["spostarli", "move them"]
];

const sortedPairs = [...PAIRS].sort((a, b) => Math.max(b[0].length, b[1].length) - Math.max(a[0].length, a[1].length));
const PROTECTED_UI_TERMS = /https?:\/\/\S+|(?<![\p{L}\p{N}_])(?:\/[\w.-]+)+|\b(?:MLSM Studio|My Lonely Soul Music|Circular Spectrum|Overlay Spectral|Comments Invasion|Cassette Desk|Song Player|Frame Booster|Video Editor|Pro ?Subtitles|MilkDrop|Winamp|FFmpeg|Whisper|Demucs|Gradio|Colab|Canvas2D|WebM|H\.264|COCO|CUDA|MPS|Metal)\b/giu;

function escapeRegExp(value: string) { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }

function replacementCase(source: string, translated: string) {
  if (source.length > 1 && source === source.toUpperCase()) return translated.toUpperCase();
  if (source[0] === source[0]?.toUpperCase()) return translated[0]?.toUpperCase() + translated.slice(1);
  return translated[0]?.toLowerCase() + translated.slice(1);
}

export function localizeUiText(value: string, language: UiLanguage): string {
  if (!value.trim()) return value;
  const protectedValues: string[] = [];
  let output = value.replace(PROTECTED_UI_TERMS, (match) => `\uE000${protectedValues.push(match) - 1}\uE001`);
  for (const [italian, english] of sortedPairs) {
    const source = language === "en" ? italian : english;
    const target = language === "en" ? english : italian;
    if (source === target || !output.toLocaleLowerCase().includes(source.toLocaleLowerCase())) continue;
    const pattern = new RegExp(`(?<![\\p{L}\\p{N}_])${escapeRegExp(source)}(?![\\p{L}\\p{N}_])`, "giu");
    output = output.replace(pattern, (match) => replacementCase(match, target));
  }
  return output.replace(/\uE000(\d+)\uE001/g, (_match, index: string) => protectedValues[Number(index)] ?? "");
}
