import type { UiLanguage } from "./ui-preferences";

/**
 * Compatibility catalogue for UI written before the bilingual shell existed.
 * Keep technical/product names unchanged and translate longest phrases first.
 */
const PAIRS: ReadonlyArray<readonly [string, string]> = [
  ["Questo dispositivo non può eseguire Whisper in modo efficiente con float16. MLSM userà automaticamente una precisione compatibile: riprova la trascrizione.", "This device cannot run Whisper efficiently with float16. MLSM will use a compatible precision automatically; retry the transcription."],
  ["Il dispositivo o backend selezionato non supporta calcoli float16 efficienti.", "Requested float16 compute type, but the target device or backend do not support efficient float16 computation."],
  ["Disattivato: quando i segmenti Gradio hanno già la risoluzione richiesta vengono uniti senza ricodificare il video e viene ripristinato direttamente l’audio originale.", "Disabled: when Gradio segments already match the requested resolution, they are joined without re-encoding the video and the original audio is restored directly."],
  ["Le regolazioni richiedono una ricodifica completa del video finale. L’avanzamento e il tempo residuo saranno mostrati durante la codifica.", "Adjustments require a full re-encode of the final video. Progress and remaining time will be shown during encoding."],
  ["Applica colore, nitidezza e riduzione rumore al video", "Apply colour, sharpness and noise reduction to the video"],
  ["Applica regolazioni video Upscaler", "Apply Upscaler video adjustments"],
  ["Regolazioni video finali", "Final video adjustments"],
  ["Operazione lenta", "Slow operation"],
  // Reports workspace. These reviewed phrases prevent the generic word-level
  // fallback from producing mixed or unnatural copy in the English UI.
  ["Report in sola visualizzazione", "Report in read-only view"],
  ["MLSM STUDIO · SOLA VISUALIZZAZIONE", "MLSM STUDIO · READ-ONLY VIEW"],
  ["Torna a Studio", "Back to Studio"],
  ["Caricamento dashboard…", "Loading dashboard…"],
  ["Carica dati CSV, testo o Excel", "Upload CSV, text or Excel data"],
  ["Importa dashboard JSON", "Import dashboard JSON"],
  ["Torna alle aree", "Back to areas"],
  ["Le mie dashboard", "My dashboards"],
  ["Esporta JSON", "Export JSON"],
  ["Esporta HTML", "Export HTML"],
  ["Link visualizzazione", "View link"],
  ["Salva dashboard", "Save dashboard"],
  ["NOME DASHBOARD", "DASHBOARD NAME"],
  ["Nome dashboard", "Dashboard name"],
  ["Modifica nome dashboard", "Edit dashboard name"],
  ["Modifiche non salvate", "Unsaved changes"],
  ["Nuova dashboard", "New dashboard"],
  ["Torna all’editor", "Back to editor"],
  ["Chiudi messaggio", "Close message"],
  ["Origini e campi", "Sources and fields"],
  ["Aggiungi dati", "Add data"],
  ["Cerca un campo…", "Search for a field…"],
  ["Cerca campi", "Search fields"],
  ["Misura numerica", "Numeric measure"],
  ["Clicca per assegnare al widget selezionato", "Click to assign to the selected widget"],
  ["Seleziona un widget, poi assegna il campo", "Select a widget, then assign the field"],
  ["Nessun campo trovato.", "No fields found."],
  ["Carica un file per esplorare dimensioni e misure.", "Upload a file to explore dimensions and measures."],
  ["Trascina i campi sulle aree Dimensione e Misura, oppure seleziona un widget e clicca un campo.", "Drag fields onto the Dimension and Measure areas, or select a widget and click a field."],
  ["Elaborazione e archivio locale · mai su Git", "Local processing and storage · never on Git"],
  ["Composizione dashboard", "Dashboard canvas"],
  ["Anteprima dati", "Data preview"],
  ["Aggiungi riga", "Add row"],
  ["Aggiungi widget", "Add widget"],
  ["Controlli della dashboard", "Dashboard controls"],
  ["Scegli il campo, il valore e i grafici che devono rispondere al filtro.", "Choose the field, value and charts that should respond to the filter."],
  ["Configura filtri dashboard", "Configure dashboard filters"],
  ["Chiudi menu filtri", "Close filters menu"],
  ["Seleziona origine", "Select source"],
  ["Seleziona campo", "Select field"],
  ["Crea filtro", "Create filter"],
  ["Non ci sono filtri. Creane uno scegliendo un campo dell’origine attiva.", "There are no filters. Create one by choosing a field from the active source."],
  ["ORIGINE DATI", "DATA SOURCE"],
  ["I tuoi dati. Una nuova prospettiva.", "Your data. A new perspective."],
  ["DAI NUMERI ALLE IDEE", "FROM NUMBERS TO IDEAS"],
  ["I dati ci sono. Dai forma al report.", "Your data is ready. Shape the report."],
  ["Una storia da raccontare,\nun dato alla volta.", "A story to tell,\none data point at a time."],
  ["Aggiungi un widget dal pannello a destra. Collega i campi e guarda la tua dashboard prendere forma.", "Add a widget from the panel on the right. Connect the fields and watch your dashboard take shape."],
  ["Carica un file, scegli i campi e componi una dashboard. Tutto il necessario, nello spazio giusto.", "Upload a file, choose the fields and build a dashboard. Everything you need, in the right place."],
  ["Scegli il primo widget", "Choose the first widget"],
  ["Carica il tuo primo file", "Upload your first file"],
  ["Esplora un esempio", "Explore an example"],
  ["Trascina qui il file", "Drop the file here"],
  ["Collega i dati", "Connect data"],
  ["Componi il report", "Build the report"],
  ["Salva e condividi", "Save and share"],
  ["Aggiungi un altro widget", "Add another widget"],
  ["Operazione in corso…", "Operation in progress…"],
  ["PRESENTAZIONE", "PRESENTATION"],
  ["AGGIUNGI WIDGET", "ADD WIDGET"],
  ["Widget e proprietà", "Widgets and properties"],
  ["PROPRIETÀ WIDGET", "WIDGET PROPERTIES"],
  ["Deseleziona widget", "Deselect widget"],
  ["Tipo widget", "Widget type"],
  ["Il cambio mantiene titolo, posizione, dimensioni, colore e campi compatibili.", "Changing type preserves the title, position, size, color and compatible fields."],
  ["Cambia visualizzazione", "Change visualization"],
  ["Seleziona un widget nella dashboard per configurare dati, aspetto e dimensioni.", "Select a dashboard widget to configure its data, appearance and size."],
  ["Dimensione / asse X", "Dimension / X axis"],
  ["Asse X (numerico)", "X axis (numeric)"],
  ["Asse Y (numerico)", "Y axis (numeric)"],
  ["Trascina un campo qui", "Drag a field here"],
  ["Raggruppa il tempo", "Group time by"],
  ["Disponibile per linee, area, barre, ciambella e righe della pivot.", "Available for lines, area, bars, doughnut and pivot rows."],
  ["Campo da contare", "Field to count"],
  ["Può essere numerico, testuale, data o booleano.", "It can be numeric, text, date or boolean."],
  ["Trascina una misura qui", "Drag a measure here"],
  ["Decimali massimi", "Maximum decimals"],
  ["Ordinamento grafico", "Chart sorting"],
  ["Asse X crescente", "X axis ascending"],
  ["Asse X decrescente", "X axis descending"],
  ["Ordine del file", "File order"],
  ["Valore crescente", "Value ascending"],
  ["Valore decrescente", "Value descending"],
  ["Sequenza temporale protetta: i punti vengono collegati in ordine cronologico.", "Protected time sequence: points are connected in chronological order."],
  ["Date e periodi sono cronologici; i numeri vengono ordinati numericamente.", "Dates and periods are chronological; numbers are sorted numerically."],
  ["Vuoto = tutte", "Empty = all"],
  ["Larghezza predefinita", "Preset width"],
  ["Larghezza manuale (1–12)", "Manual width (1–12)"],
  ["¼ pagina", "¼ page"],
  ["⅓ pagina", "⅓ page"],
  ["½ pagina", "½ page"],
  ["⅔ pagina", "⅔ page"],
  ["Pagina intera", "Full page"],
  ["Sfondo mappa", "Map background"],
  ["Colore sfondo mappa", "Map background color"],
  ["Ripristina sfondo grigio", "Reset gray background"],
  ["Ripristina sfondo mappa", "Reset map background"],
  ["Colore pallini", "Marker color"],
  ["Colore pallini mappa", "Map marker color"],
  ["Usa colore accento dashboard", "Use dashboard accent color"],
  ["Usa colore dashboard per i pallini", "Use dashboard color for markers"],
  ["Colore widget", "Widget color"],
  ["Usa palette dashboard", "Use dashboard palette"],
  ["Usa colore della dashboard", "Use dashboard color"],
  ["AGGIUNGI ANIMAZIONE", "ADD ANIMATION"],
  ["ANIMAZIONE · TIME SERIES", "ANIMATION · TIME SERIES"],
  ["Le animazioni trasformano un widget in una storia interattiva. Altri modelli saranno aggiunti qui.", "Animations turn a widget into an interactive story. More models will be added here."],
  ["Mostra come la misura cambia nel tempo.", "Show how the measure changes over time."],
  ["Questa origine non contiene campi data.", "This source contains no date fields."],
  ["Animazione widget", "Widget animation"],
  ["Menu predisposto per i prossimi modelli di animazione.", "Menu ready for future animation models."],
  ["Grafico animato", "Animated chart"],
  ["Asse X da animare", "X axis to animate"],
  ["Asse X animazione", "Animation X axis"],
  ["I periodi vengono sempre ordinati cronologicamente.", "Periods are always sorted chronologically."],
  ["Raggruppa asse X", "Group X axis by"],
  ["Raggruppa asse X animazione", "Group animation X axis by"],
  ["Valore mostrato", "Displayed value"],
  ["Valore animazione Time Series", "Time Series animation value"],
  ["Singolo periodo", "Single period"],
  ["Cumulativo", "Cumulative"],
  ["Il cumulativo somma progressivamente i valori dei periodi in ordine cronologico.", "Cumulative mode progressively adds period values in chronological order."],
  ["Linea di tendenza", "Trend line"],
  ["Regressione lineare tratteggiata sulla serie.", "Dashed linear regression over the series."],
  ["Evidenzia massimo", "Highlight maximum"],
  ["Marca il picco e ne mostra periodo e valore.", "Mark the peak and show its period and value."],
  ["LAYOUT RIGA", "ROW LAYOUT"],
  ["Elementi per riga", "Items per row"],
  ["Lascia vuoto per usare le larghezze individuali; inserisci 6, 7 o un altro valore per creare colonne uguali.", "Leave empty to use individual widths; enter 6, 7 or another value to create equal columns."],
  ["Aggiungi una nuova riga", "Add a new row"],
  ["Nome tab", "Tab name"],
  ["Nome tab attivo", "Active tab name"],
  ["Elimina tab attivo", "Delete active tab"],
  ["Il contesto dietro i numeri…", "The context behind the numbers…"],
  ["Colore accento", "Accent color"],
  ["Colore testo", "Text color"],
  ["Colore sfondo", "Background color"],
  ["SOLA VISUALIZZAZIONE", "READ-ONLY VIEW"],
  ["URL della dashboard", "Dashboard URL"],
  ["Questo link apre una vista professionale senza editor e pannelli laterali. La dashboard resta salvata sul dispositivo.", "This link opens a professional view without the editor or side panels. The dashboard remains saved on this device."],
  ["URL visualizzazione dashboard", "Dashboard view URL"],
  ["Copia URL", "Copy URL"],
  ["Apri sola visualizzazione", "Open read-only view"],
  ["HTML DA INCORPORARE", "EMBED HTML"],
  ["Dashboard pronta da incorporare", "Dashboard ready to embed"],
  ["Il file HTML contiene grafici, mappe, tab e stile MLSM. Le mappe reali usano Leaflet e OpenStreetMap e richiedono una connessione Internet.", "The HTML file contains charts, maps, tabs and MLSM styling. Real maps use Leaflet and OpenStreetMap and require an Internet connection."],
  ["Codice HTML incorporamento", "HTML embed code"],
  ["Copia codice", "Copy code"],
  ["CONVERTI SENZA RICOMINCIARE", "CONVERT WITHOUT STARTING OVER"],
  ["COMPONI LA DASHBOARD", "BUILD THE DASHBOARD"],
  ["Cambia tipo di widget", "Change widget type"],
  ["Scegli un widget", "Choose a widget"],
  ["Titolo, posizione, dimensioni, colore e campi compatibili restano invariati.", "Title, position, size, color and compatible fields remain unchanged."],
  ["Puoi inserirne quanti vuoi e configurarli dopo nella barra laterale.", "Add as many as you need and configure them later in the sidebar."],
  ["Chiudi selezione widget", "Close widget selection"],
  ["Un numero chiave in grande evidenza.", "A key number in clear focus."],
  ["Confronta categorie e periodi.", "Compare categories and periods."],
  ["Mostra l’andamento nel tempo.", "Show change over time."],
  ["Evidenzia volumi e tendenze.", "Highlight volumes and trends."],
  ["Visualizza la composizione percentuale.", "Show percentage composition."],
  ["Scopri relazioni tra due misure.", "Discover relationships between two measures."],
  ["Riconosce offline città, nazioni e codici ISO.", "Recognizes cities, countries and ISO codes offline."],
  ["Consulta le righe originali.", "Browse the original rows."],
  ["Incrocia righe, colonne, totali e aggregazioni.", "Cross rows, columns, totals and aggregations."],
  ["Aggiungi note, contesto e conclusioni.", "Add notes, context and conclusions."],
  ["Carica prima un file per usare i widget collegati ai dati. Il widget Testo è già disponibile.", "Upload a file first to use data-driven widgets. The Text widget is already available."],
  ["IL TUO SPAZIO DATI", "YOUR DATA SPACE"],
  ["Report salvati su questo dispositivo.", "Reports saved on this device."],
  ["Chiudi libreria", "Close library"],
  ["Apri dashboard", "Open dashboard"],
  ["Apri una copia", "Open a copy"],
  ["Il primo report merita un posto qui.", "Your first report deserves a place here."],
  ["Usa “Salva dashboard” per ritrovarlo alla prossima apertura.", "Use “Save dashboard” to find it here next time."],
  ["Indicatore KPI", "KPI indicator"],
  ["Linee", "Lines"],
  ["Ciambella", "Doughnut"],
  ["Dispersione", "Scatter"],
  ["Mappa geografica", "Geographic map"],
  ["Tabella pivot", "Pivot table"],
  ["Testo e note", "Text and notes"],
  ["Conteggio righe", "Row count"],
  ["Conteggio distinti", "Distinct count"],
  ["Intervallo (max − min)", "Range (max − min)"],
  ["Deviazione standard", "Standard deviation"],
  ["Data esatta", "Exact date"],
  ["Settimana", "Week"],
  ["Mese", "Month"],
  ["Trimestre", "Quarter"],
  ["Anno", "Year"],
  ["Mostra dati del grafico", "Show chart data"],
  ["Prime 200 coppie mostrate. Aggiungi una tabella per consultare tutte le righe.", "First 200 pairs shown. Add a table to browse every row."],
  ["Pagina precedente", "Previous page"],
  ["Pagina successiva", "Next page"],
  ["Media complessiva", "Overall average"],
  ["Totale righe", "Total rows"],
  ["Distinti complessivi", "Overall distinct count"],
  ["Aggiungi una nota nelle impostazioni del widget.", "Add a note in the widget settings."],
  ["Preparazione mappa geografica…", "Preparing geographic map…"],
  ["Nessuna località riconosciuta. Usa codici ISO (IT, USA), nomi di nazioni, città comuni oppure coordinate “latitudine, longitudine”.", "No locations recognized. Use ISO codes (IT, USA), country names, common cities or “latitude, longitude” coordinates."],
  ["Dimensione bolla proporzionale al valore · cartografia OpenStreetMap", "Bubble size proportional to value · OpenStreetMap mapping"],
  ["Cartografia momentaneamente non disponibile. Controlla la connessione Internet; i punti geografici restano elaborati localmente.", "Map tiles are temporarily unavailable. Check your Internet connection; geographic points remain processed locally."],
  ["Mostra località", "Show locations"],
  ["Località", "Location"],
  ["Nazione", "Country"],
  ["Città", "City"],
  ["Latitudine", "Latitude"],
  ["Longitudine", "Longitude"],
  ["Chiudi animazione", "Close animation"],
  ["Animazione temporale", "Time animation"],
  ["NUOVO MASSIMO", "NEW MAXIMUM"],
  ["Preparazione serie…", "Preparing series…"],
  ["Avanzamento", "Progress"],
  ["Serie in riproduzione", "Series playing"],
  ["Calcolo tendenza", "Calculating trend"],
  ["Riproduzione completa", "Playback complete"],
  ["MASSIMO RAGGIUNTO", "MAXIMUM REACHED"],
  ["Riproduci di nuovo", "Play again"],
  ["Riga dashboard", "Dashboard row"],
  ["Elementi nella riga", "Items in row"],
  ["Griglia fissa", "Fixed grid"],
  ["Larghezze dei singoli widget", "Individual widget widths"],
  ["Elimina riga", "Delete row"],
  ["Trascina per riordinare", "Drag to reorder"],
  ["Sposta prima", "Move earlier"],
  ["Sposta dopo", "Move later"],
  ["Duplica widget", "Duplicate widget"],
  ["Cambia tipo widget", "Change widget type"],
  ["Elimina widget", "Delete widget"],
  ["Riproduci animazione", "Play animation"],
  ["Riproduci Time Series", "Play Time Series"],
  ["Seleziona questa riga, poi aggiungi i widget", "Select this row, then add widgets"],
  ["Nessun dato disponibile con i filtri attuali.", "No data available with the current filters."],
  ["Nessun valore numerico disponibile per questa misura.", "No numeric values are available for this measure."],
  ["Tutti i valori sono zero: non ci sono proporzioni da rappresentare.", "All values are zero: there are no proportions to display."],
  ["Dashboard senza titolo", "Untitled dashboard"],
  ["Pagina 1", "Page 1"],
  ["Dati importati", "Imported data"],
  ["CAMPI", "FIELDS"],
  ["DATI", "DATA"],
  ["FILTRI INTERATTIVI", "INTERACTIVE FILTERS"],
  ["Categorie", "Categories"],
  ["Origine", "Source"],
  ["Origini", "Sources"],
  ["Campo", "Field"],
  ["Campi", "Fields"],
  ["Misura", "Measure"],
  ["Righe", "Rows"],
  ["Colonne", "Columns"],
  ["Totale", "Total"],
  ["Valuta", "Currency"],
  ["Numero", "Number"],
  ["Percentuale", "Percentage"],
  ["Somma", "Sum"],
  ["Media", "Average"],
  ["Mediana", "Median"],
  ["Minimo", "Minimum"],
  ["Massimo", "Maximum"],
  ["Varianza", "Variance"],
  ["Periodo", "Period"],
  ["Periodi", "Periods"],
  ["Proprietà", "Properties"],
  ["Accento", "Accent"],
  ["Tutte", "All"],
  ["Tutti", "All"],
  ["vuoto", "empty"],
  ["righe", "rows"],
  ["campi", "fields"],
  ["origini", "sources"],
  ["periodi", "periods"],
  // Legacy panels still contain a few English-only controls. Keep these
  // complete phrases here so the bridge never leaves an Italian/English mix.
  ["Carica un’immagine. Il rilevatore mantiene tutte le categorie COCO supportate e ogni cerchio può essere rilevato o posizionato manualmente.", "Upload an image. The detector keeps every supported COCO category, and each circle can be detected or positioned manually."],
  ["Una sensibilità maggiore riduce la soglia di confidenza e può includere più categorie supportate. La modifica non riavvia automaticamente il rilevamento.", "Higher sensitivity lowers the confidence threshold and may include more supported categories. Changing it does not rerun detection automatically."],
  ["Canvas2D deterministico · contain + rilevamento oggetti", "Deterministic Canvas2D · contain + object detection"],
  ["Anteprima Circular Spectrum Auto Detector", "Circular Spectrum Auto Detector preview"],
  ["Mostra/nascondi aree rilevate", "Toggle detected areas"],
  ["Nascondi aree rilevate", "Hide detected areas"],
  ["Mostra aree rilevate", "Show detected areas"],
  ["Esci da tutto schermo", "Exit full screen"],
  ["Anteprima a tutto schermo", "Preview full screen"],
  ["↙ Torna all’editor", "↙ Back to editor"],
  ["⛶ Tutto schermo", "⛶ Full screen"],
  ["● Canvas2D · export offline condiviso", "● Canvas2D · shared offline export"],
  ["Persone", "People"],
  ["Cerchi Circular Spectrum", "Circular Spectrum circles"],
  ["Ridimensiona Circular Spectrum", "Resize Circular Spectrum"],
  ["Disattiva animazione", "Disable animation"],
  ["Animata", "Animated"],
  ["Personalizzata", "Custom"],
  ["Stereo laterale (L/R)", "Stereo sides (L/R)"],
  ["Testo completo della canzone", "Full song text"],
  ["Incolla il testo", "Paste the text"],
  ["Mixer audio", "Audio mixer"],
  ["Transizioni", "Transitions"],
  ["Apri procedura", "Open workflow"],
  ["Genera un layer Pro Subtitles per la clip selezionata.", "Generate a Pro Subtitles layer for the selected clip."],
  ["Seleziona un frammento nella timeline.", "Select a fragment in the timeline."],
  ["Seleziona una clip con audio per regolarne il volume.", "Select a clip with audio to adjust its volume."],
  ["Traccia bloccata · sbloccala per modificare le regolazioni.", "Track locked · unlock it to edit adjustments."],
  ["Seleziona una clip video o immagine per regolarla.", "Select a video or image clip to adjust it."],
  ["Il frammento selezionato verrà elaborato e il risultato inserito come nuova clip sopra l’originale.", "The selected fragment will be processed and the result inserted as a new clip above the original."],
  ["Esegui sul frammento", "Run on fragment"],
  ["transizioni disponibili. Si applicano soltanto alla clip visiva selezionata.", "transitions available. They apply only to the selected visual clip."],
  ["Seleziona una clip visiva su una traccia sbloccata.", "Select a visual clip on an unlocked track."],
  ["Nessuna transizione disponibile in questa build.", "No transitions available in this build."],
  ["Frame precedente", "Previous frame"],
  ["Frame successivo", "Next frame"],
  ["Riproduci/Pausa (Spazio)", "Play/Pause (Space)"],
  ["Spazio", "Space"],
  ["Sottotitolo", "Subtitle"],
  ["Risoluzione · formato", "Resolution · format"],
  ["Qualità codifica", "Encoding quality"],
  ["Massima · bitrate elevato", "Maximum · high bitrate"],
  ["Alta · file più leggero", "High · smaller file"],
  ["Scegli destinazione e esporta", "Choose destination and export"],
  ["Durata", "Duration"],
  ["Video stimato", "Estimated video"],
  ["Nessuna conversione FPS", "No frame-rate conversion"],
  ["Formato", "Format"],
  ["Visualizzatori", "Visualizers"],
  ["Forma d’onda audio", "Waveform audio"],
  ["Già elaborato", "Already processed"],
  ["Interpola fotogrammi", "Boost frames"],
  ["Salva video", "Save video"],
  ["Video salvato", "Video saved"],
  ["Salvataggio…", "Saving…"],
  ["Interpolazione completata", "Interpolation complete"],
  ["Elaborazione in corso…", "Processing…"],
  ["Dimensioni in rilevamento", "Detecting dimensions"],
  ["rilevamento FPS in corso…", "detecting frame rate…"],
  ["FPS diretto", "Exact frame rate"],
  ["FPS target", "Target frame rate"],
  ["Moltiplicatore", "Multiplier"],
  ["Seleziona file", "Choose file"],
  ["Nessun file selezionato", "No file selected"],
  ["Sostituisci file", "Replace file"],
  ["Trascina un file qui", "Drop a file here"],
  ["Rimuovi file", "Remove file"],
  ["Video temporanei di Upscaler / Frame Booster", "Upscaler / Frame Booster temporary video"],
  ["Modelli Upscaler", "Upscaler models"],
  ["Modelli locali", "Local models"],
  ["Cache del browser", "Browser cache"],
  ["Centro di controllo MLSM Studio", "MLSM Studio Control Center"],
  ["Pronto per l’esportazione", "Ready to export"],
  ["Esportazione completata", "Export complete"],
  ["Nessuna selezione", "Nothing selected"],
  ["Ripristina impostazioni", "Reset settings"],
  ["Mostra anteprima", "Show preview"],
  ["Nascondi anteprima", "Hide preview"],
  ["Adatta alla finestra", "Fit to window"],
  ["Mantieni proporzioni", "Keep aspect ratio"],
  ["Qualità di esportazione", "Export quality"],
  ["Qualità anteprima", "Preview quality"],
  ["Impostazioni avanzate", "Advanced settings"],
  ["MLSM usa H.264 quando supportato e, per sorgenti oltre 4K, passa automaticamente a H.265/HEVC senza ridurre la risoluzione.", "MLSM uses H.264 when supported and, for sources above 4K, automatically switches to H.265/HEVC without reducing resolution."],
  ["passa automaticamente a", "automatically switches to"],
  ["sorgenti oltre 4K", "sources above 4K"],
  ["quando supportato", "when supported"],
  ["ridurre la risoluzione", "reducing resolution"],
  ["Nessun encoder MP4 compatibile con la risoluzione originale", "No MP4 encoder is compatible with the original resolution"],
  ["Sono stati verificati H.264/AVC e H.265/HEVC.", "H.264/AVC and H.265/HEVC were checked."],
  ["non è disponibile per la risoluzione originale", "is not available for the original resolution"],
  ["L’encoder", "The encoder"],
  ["Carica un brano intero. L’intro dura", "Upload a full track. The intro lasts"],
  ["Timbri deterministici, nessun comment perso", "Deterministic stamps, no comments lost"],
  ["Completo · nessun taglio", "Full · no cropping"],
  ["Separatore prima/dopo", "Before/after separator"],
  ["Renderer TypeScript/Canvas nativo · nessun host C++ o repository incorporato", "Native TypeScript/Canvas renderer · no C++ host or embedded repository"],
  ["Nessun effetto attivo.", "No active effects."],
  ["● Download soltanto al primo utilizzo · cache locale persistente · nessun peso nel progetto", "● Download on first use only · persistent local cache · no project payload"],
  ["Elaborazione locale · nessun audio inviato online", "Local processing · no audio sent online"],
  ["Nessun effetto. Aggiungilo qui o trascinalo dalla libreria nella corsia Effetti.", "No effects. Add one here or drag it from the library to the Effects lane."],
  ["Riordina i livelli: quello più in alto viene composto sopra gli altri. Nessun livello video ha un ruolo principale o overlay.", "Reorder layers: the topmost one is composited above the others. No video layer has a fixed main or overlay role."],
  ["Carica i media nel pool a sinistra e usa “Aggiungi in timeline”: poi trascina i bordi per estenderli e il corpo per spostarli.", "Load media into the pool on the left and use “Add to timeline”; then drag the edges to extend clips and the body to move them."],
  ["Il catalogo Transitions è vuoto: nessun effetto generico viene mostrato al suo posto.", "The Transitions catalogue is empty: no generic effect is shown in its place."],
  ["Backend video artifact non disponibile in questa build: nessun risultato simulato.", "Video artifact backend unavailable in this build: no simulated result."],
  ["Carica i media nel pool e trascinali in timeline per iniziare il montaggio.", "Load media into the pool and drag them onto the timeline to start editing."],
  ["Carica lo spezzone usato dalla clip e, separatamente, la canzone completa.", "Load the clip fragment and, separately, the full song."],
  ["Anteprima ed export campionano la stessa analisi FFT al tempo esatto del fotogramma.", "Preview and export sample the same FFT analysis at the exact frame time."],
  ["Applica modello e regolazioni correnti a più immagini in sequenza.", "Apply the current model and adjustments to multiple images in sequence."],
  ["Aggiungi una o più foto per creare una coda batch.", "Add one or more photos to create a batch queue."],
  ["I video restano nel flusso singolo.", "Videos remain in the single-item workflow."],
  ["Carica un’immagine. Il rilevatore conserva tutte le categorie COCO supportate e ogni cerchio può essere rilevato o posizionato manualmente.", "Upload an image. The detector keeps every supported COCO category, and each circle can be detected or positioned manually."],
  ["Una sensibilità maggiore riduce la soglia di confidenza e può includere più categorie supportate.", "Higher sensitivity lowers the confidence threshold and may include more supported categories."],
  ["La modifica non riavvia automaticamente il rilevamento.", "Changing it does not rerun detection automatically."],
  ["Nessun oggetto salvato. Carica un’immagine per avviare il rilevamento.", "No objects saved. Upload an image to run detection."],
  ["Usa la palette dell’oggetto selezionato.", "Uses the selected object's palette."],
  ["Le bande orizzontali restano ferme mentre l’anello radiale ruota.", "Fixed horizontal bands stay level while the radial ring rotates."],
  ["Gli impulsi sinistro e destro indipendenti vengono specchiati automaticamente con sorgenti mono.", "Independent left/right pulses mirror automatically when the source is mono."],
  ["Usa la traccia cue del progetto e la tipografia Pro Subtitles nel cerchio dell’oggetto.", "Uses the project cue track and Pro Subtitles typography inside this object circle."],
  ["Adattamento nativo del concetto Winamp/MilkDrop", "Native adaptation of the Winamp/MilkDrop concept"],
  ["usa le 48 bande FFT reali di MLSM", "uses MLSM’s 48 real FFT bands"],
  ["resta sincronizzato durante seek ed export", "stays synchronized during seeking and export"],
  ["non richiede projectM o componenti Windows", "does not require projectM or Windows components"],
  ["Carica foto o video di sfondo", "Upload a background image or video"],
  ["Carica immagine o video di sfondo", "Upload a background image or video"],
  ["Carica un video per iniziare", "Upload a video to begin"],
  ["Carica una foto o un video", "Upload a photo or video"],
  ["Carica foto o video", "Upload photos or videos"],
  ["Carica sorgente Upscaler", "Upload Upscaler source"],
  ["Carica video Frame Booster", "Upload Frame Booster video"],
  ["Carica canzone completa", "Upload full song"],
  ["Carica brano intero", "Upload full track"],
  ["Carica spezzone clip", "Upload clip fragment"],
  ["Carica cartella commenti", "Upload comments folder"],
  ["Carica immagini commenti", "Upload comment images"],
  ["Carica video con watermark", "Upload watermarked video"],
  ["Carica video senza watermark", "Upload video without watermark"],
  ["Carica video pulito", "Upload clean video"],
  ["Carica fotografia senza watermark", "Upload photo without watermark"],
  ["Carica fotografia pulita", "Upload clean photo"],
  ["Riferimento originale pulito", "Clean original reference"],
  ["Fotografia", "Photo"],
  ["Video pulito", "Clean video"],
  ["Ricalcola sincronizzazione", "Recalculate synchronization"],
  ["Sincronizzazione temporale automatica", "Automatic time synchronization"],
  ["Riallinea ogni frame", "Realign every frame"],
  ["Spostamento massimo", "Maximum displacement"],
  ["Stabilizzazione", "Stabilization"],
  ["Intervallo ricerca", "Search range"],
  ["partenza bloccata", "start locked"],
  ["Il video pulito parte dall’inizio a velocità originale. Dopo la sua fine, la parte restante resta originale.", "The clean video starts from the beginning at its original speed. After it ends, the remaining part stays unchanged."],
  ["Offset positivo: usa un frame successivo del video pulito. Fuori dall’intervallo disponibile, il video resta originale.", "Positive offset: use a later frame from the clean video. Outside the available range, the video stays unchanged."],
  ["Controllo anti-anomalia", "Artifact prevention check"],
  ["I frame rate non coincidono", "Frame rates do not match"],
  ["Mantieni FPS video con watermark", "Keep watermarked video FPS"],
  ["Mantieni FPS video pulito", "Keep clean video FPS"],
  ["Continua e mostrami il risultato", "Continue and show me the result"],
  ["Interrompi elaborazione", "Stop processing"],
  ["Allineamento spaziale instabile", "Unstable spatial alignment"],
  ["CONTROLLO QUALITÀ", "QUALITY CHECK"],
  ["SINCRONIZZAZIONE VIDEO", "VIDEO SYNCHRONIZATION"],
  ["Ripristino audio originale e chiusura MP4", "Restoring original audio and finalizing MP4"],
  ["Verifica del video e dell’audio esportati", "Verifying exported video and audio"],
  ["Carica video verticale", "Upload vertical video"],
  ["Carica immagine laterale", "Upload side image"],
  ["Carica copertina", "Upload cover"],
  ["Carica immagine principale", "Upload main image"],
  ["Carica immagine di sfondo", "Upload background image"],
  ["Carica immagine", "Upload image"],
  ["Carica video", "Upload video"],
  ["Carica brano", "Upload track"],
  ["Carica audio", "Upload audio"],
  ["Carica immagine Auto Detector", "Upload Auto Detector image"],
  ["Carica immagine", "Upload image"],
  ["Lettura immagine…", "Reading image…"],
  ["Avvio rilevamento…", "Starting detection…"],
  ["Sensibilità rilevamento", "Detection sensitivity"],
  ["Rilevamento non riuscito", "Detection failed"],
  ["Oggetti rilevati", "Detected objects"],
  ["Oggetto rilevato", "Detected object"],
  ["Rileva di nuovo", "Detect again"],
  ["Seleziona un oggetto", "Select an object"],
  ["Ripristina palette immagine", "Reset to image palette"],
  ["Automatica dall’oggetto", "Automatic from object"],
  ["Automatica dall’immagine", "Auto from image"],
  ["Manuale per istanza", "Manual per instance"],
  ["Sorgente palette", "Palette source"],
  ["Velocità rotazione", "Rotation speed"],
  ["Particelle collisione", "Collision particles"],
  ["Spettro radiale", "Radial spectrum"],
  ["Spettro centrale", "Center spectrum"],
  ["Lati stereo", "Stereo sides"],
  ["Cerchio manuale", "Manual circle"],
  ["Cerchi Circular Spectrum", "Circular Spectrum circles"],
  ["Composizione globale", "Global composition"],
  ["Composizione centrale pulita", "Clean central composition"],
  ["Composizione Video Editor", "Video Editor composition"],
  ["Composizione Comments Invasion", "Comments Invasion composition"],
  ["Controlli riproduzione a tutto schermo", "Fullscreen playback controls"],
  ["Controlli anteprima zona rimozione", "Removal preview controls"],
  ["Anteprima zona rimozione", "Removal area preview"],
  ["Anteprima non disponibile", "Preview unavailable"],
  ["Anteprima immagine usata per estrarre la palette", "Image preview used to extract the palette"],
  ["Anteprima leggera", "Lightweight preview"],
  ["export ricostruito alla risoluzione finale", "export rebuilt at final resolution"],
  ["Preview ed export condividono tempi e posizioni", "Preview and export share timing and positions"],
  ["Aggiungi endpoint", "Add endpoint"],
  ["Verifica endpoint e carica modelli", "Check endpoints and load models"],
  ["Attività endpoint remoti", "Remote endpoint activity"],
  ["Alcuni endpoint non rispondono", "Some endpoints are not responding"],
  ["Continua con", "Continue with"],
  ["Checkpoint segmenti", "Segment checkpoints"],
  ["Checkpoint video", "Video checkpoint"],
  ["Svuota tutta la cache video", "Clear all video cache"],
  ["Conferma pulizia cache video", "Confirm video cache cleanup"],
  ["Conferma eliminazione", "Confirm deletion"],
  ["Come vuoi gestire la cache?", "How do you want to handle the cache?"],
  ["Riprendi cache compatibile", "Resume compatible cache"],
  ["Riparti da zero", "Start from scratch"],
  ["Aggiungi altre foto al batch Upscaler", "Add more photos to the Upscaler batch"],
  ["Batch foto", "Photo batch"],
  ["Cambia destinazione", "Change destination"],
  ["Destinazione", "Destination"],
  ["Avvia batch", "Start batch"],
  ["Riprova selezionati", "Retry selected"],
  ["Seleziona tutti", "Select all"],
  ["Deseleziona tutti", "Deselect all"],
  ["Rimuovi selezionati", "Remove selected"],
  ["Aggiungi in timeline", "Add to timeline"],
  ["Chiudi i vuoti della traccia", "Close track gaps"],
  ["Chiudi i vuoti", "Close gaps"],
  ["Duplica clip", "Duplicate clip"],
  ["Taglia sul playhead", "Cut at playhead"],
  ["Sposta sul playhead", "Move to playhead"],
  ["Sincronizza audio e video", "Synchronize audio and video"],
  ["Allinea per frame", "Align by frame"],
  ["Aggiungi effetti alla clip", "Add effects to clip"],
  ["Effetti della clip", "Clip effects"],
  ["Clip selezionata", "Selected clip"],
  ["Azioni clip", "Clip actions"],
  ["Traccia audio", "Audio track"],
  ["Livello video", "Video layer"],
  ["Audio della clip", "Clip audio"],
  ["Audio disattivato", "Audio disabled"],
  ["Disattiva audio clip", "Mute clip audio"],
  ["Attiva ombra immagine", "Enable image shadow"],
  ["Colore ombra immagine", "Image shadow color"],
  ["Distanza ombra immagine", "Image shadow distance"],
  ["Diffusione ombra immagine", "Image shadow blur"],
  ["Direzione ombra immagine", "Image shadow direction"],
  ["Aggiungi keyframe", "Add keyframe"],
  ["Porta su", "Move up"],
  ["Porta giù", "Move down"],
  ["Annulla modifica Video Editor", "Undo Video Editor change"],
  ["Annulla elaborazione", "Cancel processing"],
  ["Apri Pro Subtitles", "Open Pro Subtitles"],
  ["Apri assistente applicazione", "Open application assistant"],
  ["Chiudi assistente", "Close assistant"],
  ["Azzera memoria assistente", "Clear assistant memory"],
  ["Domanda per l’assistente", "Question for the assistant"],
  ["Chiedi come usare l’applicazione…", "Ask how to use the application…"],
  ["Cosa puoi fare?", "What can you do?"],
  ["Come esporto?", "How do I export?"],
  ["Da dove inizio?", "Where do I start?"],
  ["Blocchi manuali e libreria", "Manual blocks and library"],
  ["Inserisci blocco al playhead", "Insert block at playhead"],
  ["Applica anche animazione e stile", "Also apply animation and style"],
  ["Rilevamento automatico", "Automatic detection"],
  ["Lingua Whisper", "Whisper language"],
  ["Caratteri massimi per riga", "Maximum characters per line"],
  ["Durata massima sottotitolo", "Maximum subtitle duration"],
  ["Velocità massima lettura", "Maximum reading speed"],
  ["Animazione predefinita", "Default animation"],
  ["Dimensione globale", "Global size"],
  ["Posizione globale", "Global position"],
  ["Opacità globale", "Global opacity"],
  ["Stile per parola", "Per-word style"],
  ["Dividi frase", "Split phrase"],
  ["File sottotitoli", "Subtitle file"],
  ["Output per il montaggio", "Editing output"],
  ["Colore di fondo", "Background color"],
  ["Brano caricato + effetti meccanici", "Loaded track + mechanical effects"],
  ["Solo effetti meccanici", "Mechanical effects only"],
  ["Audio export Cassette Desk", "Cassette Desk export audio"],
  ["BPM e tonalità", "BPM and key"],
  ["BPM manuale", "Manual BPM"],
  ["Analisi armonica automatica", "Automatic harmonic analysis"],
  ["Analisi voce reale", "Real vocal analysis"],
  ["Colori indipendenti", "Independent colors"],
  ["Ambiente fuori dalla finestra", "Environment outside the window"],
  ["Durata intro", "Intro duration"],
  ["Carica immagine Cassette Desk", "Upload Cassette Desk image"],
  ["Carica cover / poster", "Upload cover / poster"],
  ["Carica poster Teddy Sing", "Upload Teddy Sing poster"],
  ["Carica cover del brano", "Upload track cover"],
  ["Elementi della base", "Backing-track elements"],
  ["Direzione artistica", "Art direction"],
  ["Sfondo e ambiente", "Background and environment"],
  ["Binari e collegamenti", "Rails and connections"],
  ["Colori batteria per tipo", "Drum colors by type"],
  ["Selezione e sostituzione", "Selection and replacement"],
  ["Sorgente", "Source"], ["Ingresso", "Input"], ["Uscita", "Output"],
  ["Impostazioni", "Settings"], ["Elementi", "Elements"], ["Comportamento", "Behavior"],
  ["Animazione", "Animation"], ["Effetti", "Effects"], ["Effetto", "Effect"],
  ["Colore", "Color"], ["Colori", "Colors"], ["Sfondo", "Background"],
  ["Immagine", "Image"], ["Fotografia", "Photo"], ["Video", "Video"], ["Audio", "Audio"],
  ["Traccia", "Track"], ["Clip", "Clip"], ["Oggetto", "Object"], ["Oggetti", "Objects"],
  ["Palette", "Palette"], ["Titolo", "Title"], ["Artista", "Artist"],
  ["Durata", "Duration"], ["Dimensione", "Size"], ["Dimensioni", "Dimensions"],
  ["Larghezza", "Width"], ["Altezza", "Height"], ["Posizione", "Position"],
  ["Rotazione", "Rotation"], ["Scala", "Scale"], ["Opacità", "Opacity"],
  ["Contrasto", "Contrast"], ["Luminosità", "Brightness"], ["Saturazione", "Saturation"],
  ["Intensità", "Intensity"], ["Velocità", "Speed"], ["Sensibilità", "Sensitivity"],
  ["Automatico", "Automatic"], ["Automatica", "Automatic"], ["Manuale", "Manual"],
  ["Attivo", "Enabled"], ["Attiva", "Enable"], ["Disattiva", "Disable"],
  ["Abilitato", "Enabled"], ["Abilitata", "Enabled"], ["Nessuno", "None"], ["Nessuna", "None"], ["Nessun", "No"],
  ["Carica", "Upload"], ["Seleziona", "Select"], ["Aggiungi", "Add"], ["Rimuovi", "Remove"], ["Elimina", "Delete"],
  ["Applica", "Apply"], ["Cambia", "Change"], ["Riprova", "Retry"], ["Ripristina", "Reset"],
  ["Avvia", "Start"], ["Avvio", "Starting"], ["Annulla", "Cancel"], ["Chiudi", "Close"],
  ["Apri", "Open"], ["Salva", "Save"], ["Esporta", "Export"], ["Anteprima", "Preview"],
  ["Riproduci", "Play"], ["Pausa", "Pause"], ["Ferma", "Stop"], ["Elaborazione", "Processing"],
  ["Caricamento", "Loading"], ["Preparazione", "Preparing"], ["Completato", "Completed"],
  ["Errore", "Error"], ["Non disponibile", "Unavailable"], ["Da verificare", "To be checked"],
  ["Locale", "Local"], ["Remoto", "Remote"], ["Cartella", "Folder"], ["Modello", "Model"],
  ["Fotogrammi", "Frames"], ["Fotogramma", "Frame"], ["Risoluzione", "Resolution"],
  ["Rapporto", "Aspect ratio"], ["Metodo", "Method"], ["Target", "Target"],
  ["Posizionamento", "Placement"], ["Persona", "Person"], ["Soglia", "Threshold"],
  ["Bilanciata", "Balanced"], ["Precisa", "Precise"], ["Alta", "High"],
  ["Ferma", "Stopped"], ["Sottotitoli", "Subtitles"], ["Anima", "Animate"],
  ["Strumenti AI", "AI Tools"], ["Regola", "Adjust"], ["Rilevamento", "Detection"],
  ["Rilevatore", "Detector"], ["Cerchio", "Circle"], ["Centro", "Center"],
  ["Oggetti rilevati", "Detected objects"], ["Oggetto rilevato", "Detected object"],
  ["il", "the"], ["la", "the"], ["lo", "the"], ["i", "the"], ["gli", "the"], ["le", "the"],
  ["un", "a"], ["uno", "a"], ["una", "an"], ["di", "of"], ["del", "of the"],
  ["della", "of the"], ["dello", "of the"], ["dei", "of the"], ["delle", "of the"],
  ["da", "from"], ["dal", "from the"], ["dalla", "from the"], ["dall", "from the"],
  ["al", "to the"], ["alla", "to the"], ["nel", "in the"], ["nella", "in the"],
  ["nello", "in the"], ["sul", "on the"], ["sulla", "on the"], ["con", "with"],
  ["senza", "without"], ["per", "for"], ["e", "and"], ["ed", "and"], ["o", "or"],
  ["oppure", "or"], ["anche", "also"], ["non", "not"], ["solo", "only"],
  ["soltanto", "only"], ["ogni", "each"], ["tutti", "all"], ["tutto", "everything"],
  ["questa", "this"], ["questo", "this"], ["stessa", "same"], ["stesso", "same"],
  ["prima", "before"], ["dopo", "after"], ["poi", "then"], ["quando", "when"],
  ["se", "if"], ["come", "as"], ["qui", "here"], ["sopra", "above"],
  ["sotto", "below"], ["sinistra", "left"], ["destra", "right"], ["alto", "top"],
  ["basso", "bottom"], ["primo", "first"], ["secondo", "second"], ["fino", "up to"],
  ["più", "more"], ["puoi", "you can"], ["può", "can"], ["viene", "is"],
  ["vengono", "are"], ["verrà", "will be"], ["resta", "remains"], ["restano", "remain"],
  ["usa", "uses"], ["usano", "use"], ["usato", "used"], ["richiede", "requires"],
  ["conserva", "preserves"], ["condividono", "share"], ["mostra", "shows"],
  ["scegli", "choose"], ["trascina", "drag"], ["riempi", "fill"], ["ruota", "rotates"],
  ["selezione", "selection"], ["selezionata", "selected"], ["principale", "main"],
  ["originale", "original"], ["originali", "original"], ["finale", "final"],
  ["completo", "complete"], ["completa", "complete"], ["intero", "full"],
  ["verticale", "vertical"], ["orizzontale", "horizontal"], ["centrale", "central"],
  ["laterale", "side"], ["globale", "global"], ["locale", "local"], ["reale", "real"],
  ["reali", "real"], ["pulita", "clean"], ["trasparente", "transparent"],
  ["disponibile", "available"], ["attivi", "active"], ["consigliato", "recommended"],
  ["massima", "maximum"], ["preciso", "precise"], ["fisica", "physical"],
  ["progetto", "project"], ["scena", "scene"], ["formato", "format"], ["modalità", "mode"],
  ["nome", "name"], ["tipo", "type"], ["testo", "text"], ["frase", "phrase"],
  ["frasi", "phrases"], ["parola", "word"], ["parole", "words"], ["stile", "style"],
  ["font", "font"], ["commenti", "comments"], ["commento", "comment"], ["immagini", "images"],
  ["bande", "bands"], ["barre", "bars"], ["segmenti", "segments"], ["segmento", "segment"],
  ["spettro", "spectrum"], ["spettrogramma", "spectrogram"], ["canzone", "song"],
  ["brano", "track"], ["spezzone", "fragment"], ["voce", "vocals"], ["vocale", "vocal"],
  ["musica", "music"], ["tonalità", "key"], ["analisi", "analysis"],
  ["regolazioni", "adjustments"], ["fusione", "blending"], ["allineamento", "alignment"],
  ["qualità", "quality"], ["controlli", "controls"], ["pannello", "panel"],
  ["libreria", "library"], ["blocco", "block"], ["blocchi", "blocks"], ["punto", "point"],
  ["bordo", "edge"], ["bordi", "edges"], ["cornice", "frame"], ["ombra", "shadow"],
  ["ombre", "shadows"], ["luce", "light"], ["particelle", "particles"],
  ["canale", "channel"], ["ingresso", "input"], ["uscita", "output"],
  ["risultato", "result"], ["confronto", "comparison"], ["dettaglio", "detail"],
  ["percorso", "path"], ["movimento", "motion"], ["battuta", "beat"], ["battute", "beats"],
  ["preparazione", "preparing"], ["lettura", "reading"], ["verifica", "check"],
  ["adattamento", "fit"], ["copertina", "cover"], ["sfera", "sphere"], ["cubo", "cube"],
  ["vetro", "glass"], ["stanza", "room"], ["finestra", "window"], ["area", "area"]
  , ["che", "that"], ["cui", "which"], ["mentre", "while"], ["perché", "because"],
  ["quindi", "therefore"], ["deve", "must"], ["devono", "must"], ["premi", "press"],
  ["clicca", "click"], ["crea", "creates"], ["creati", "created"], ["cambia", "changes"],
  ["mantiene", "keeps"], ["evita", "avoids"], ["permette", "allows"], ["supporta", "supports"],
  ["possono", "can"], ["sono", "are"], ["saranno", "will be"], ["essere", "be"], ["è", "is"],
  ["disponibili", "available"], ["mancante", "missing"], ["mancanti", "missing"],
  ["pronto", "ready"], ["pronta", "ready"], ["attesa", "waiting"], ["corretta", "correct"],
  ["corretto", "correct"], ["circa", "about"], ["separata", "separated"], ["estratta", "extracted"],
  ["impostata", "set"], ["salvato", "saved"], ["salvati", "saved"], ["salvate", "saved"],
  ["raggiungibile", "reachable"], ["raggiungibili", "reachable"], ["avanzamento", "progress"],
  ["tentativi", "attempts"], ["tastiera", "keyboard"], ["timbri", "stamps"], ["perso", "lost"],
  ["taglio", "crop"], ["tagli", "cuts"], ["composizione", "composition"], ["tipografica", "typographic"],
  ["scheda", "tab"], ["sostituirne", "replace its"], ["sostituzione", "replacement"],
  ["definisci", "define"], ["raggio", "beam"], ["due", "two"], ["punti", "points"],
  ["superficie", "surface"], ["coordinate", "coordinates"], ["rifinite", "refined"],
  ["collegamento", "connection"], ["collegamenti", "connections"], ["aggiornando", "updating"],
  ["geometria", "geometry"], ["materiale", "material"], ["scelta", "choice"], ["riguarda", "concerns"],
  ["parte", "starts"], ["combinata", "combined"], ["altri", "other"], ["altre", "other"],
  ["tipi", "types"], ["famiglie", "families"], ["generatore", "generator"],
  ["modificabili", "editable"], ["singolarmente", "individually"], ["grande", "large"],
  ["incorporata", "embedded"], ["definirà", "will define"], ["automaticamente", "automatically"],
  ["volantini", "flyers"], ["balla", "dances"], ["cammina", "walks"], ["originari", "original"],
  ["mano", "manually"], ["migliore", "best"], ["quasi", "almost"], ["integralmente", "fully"],
  ["valorizza", "enhances"], ["lati", "sides"], ["direttamente", "directly"], ["copia", "copy"],
  ["consiglio", "suggestion"], ["ripulisce", "cleans"], ["riallinea", "realigns"],
  ["spostare", "move"], ["arbitrariamente", "arbitrarily"], ["utilizzo", "use"],
  ["persistente", "persistent"], ["peso", "weight"], ["lunghezza", "length"],
  ["indicativa", "approximate"], ["incolla", "paste"], ["attivare", "enable"],
  ["punteggiatura", "punctuation"], ["righe", "lines"], ["enfasi", "emphasis"],
  ["ripetizioni", "repetitions"], ["meccaniche", "mechanical"], ["risalto", "focus"],
  ["chiave", "key"], ["tutte", "all"], ["foto", "photos"], ["inviate", "sent"],
  ["distribuisce", "distributes"], ["parallelo", "parallel"], ["tra", "among"],
  ["rimesso", "restored"], ["lavoro", "job"], ["link", "links"], ["insieme", "together"],
  ["separati", "separated"], ["spazi", "spaces"], ["virgole", "commas"], ["duplicati", "duplicates"],
  ["ignorati", "ignored"], ["invio", "enter"], ["userà", "will use"], ["espongono", "provide"],
  ["farà", "will ask"], ["approvare", "approve"], ["esclusione", "exclusion"],
  ["aggiuntivi", "additional"], ["ricevuto", "received"], ["localmente", "locally"],
  ["cade", "fails"], ["riprendere", "resume"], ["rifare", "redo"], ["parti", "parts"],
  ["già", "already"], ["eliminare", "delete"], ["sorgenti", "sources"], ["risultati", "results"],
  ["inviato", "sent"], ["riprodotto", "played"], ["inserito", "inserted"], ["esportato", "exported"],
  ["contenuti", "content"], ["possiedi", "own"], ["diritti", "rights"],
  ["autorizzazione", "permission"], ["disponibilità", "availability"], ["condizioni", "terms"],
  ["piattaforma", "platform"], ["variare", "vary"], ["decodificato", "decoded"],
  ["ricodificato", "re-encoded"], ["consegnato", "delivered"], ["rileva", "detects"],
  ["proprietà", "ownership"], ["quali", "which"], ["sei", "are"], ["autorizzato", "authorized"],
  ["intervenire", "modify"], ["rappresentare", "represent"], ["inquadratura", "shot"],
  ["vedere", "see"], ["tracce", "tracks"], ["nuovi", "new"], ["obiettivo", "target"],
  ["morbido", "soft"], ["vocali", "vocal"], ["decidono", "determine"],
  ["rimangono", "remain"], ["vincoli", "constraints"], ["mostrerà", "will show"],
  ["stima", "estimate"], ["attendibile", "reliable"], ["confronterà", "will compare"],
  ["appartengono", "belong"], ["esattamente", "exactly"], ["nuovo", "new"],
  ["ordine", "order"], ["ricostruisce", "rebuilds"], ["rimette", "restores"],
  ["aggiungilo", "add it"], ["trascinalo", "drag it"], ["corsia", "lane"],
  ["riordina", "reorder"], ["livelli", "layers"], ["quello", "the one"], ["composto", "composited"],
  ["catalogo", "catalog"], ["vuoto", "empty"], ["generico", "generic"], ["mostrato", "shown"],
  ["posto", "place"], ["simulato", "simulated"], ["intro", "intro"],
  ["deterministici", "deterministic"], ["nativo", "native"], ["incorporato", "embedded"],
  ["imposta", "sets"], ["seconda", "second"], ["ha", "has"], ["ruolo", "role"],
  ["suo", "its"], ["estenderli", "extend them"], ["corpo", "body"], ["spostarli", "move them"]
];

const PROTECTED_UI_TERMS = /https?:\/\/\S+|(?<![\p{L}\p{N}_])(?:\/[\w.-]+)+|[\p{L}\p{N}_-][\p{L}\p{N}_ .()-]*\.(?:mp4|mov|webm|mkv|mp3|wav|flac|ogg|m4a|png|jpg|jpeg|webp|glb|fbx|srt|vtt)\b|\b(?:MLSM Studio|My Lonely Soul Music|Lonely Bot|Sound Animation|Photo & Video Studio|Circular Spectrum(?: Auto Detector)?|Overlay Spectral|Comments Invasion|Cassette Desk|Song Player|Frame Booster|Video Editor|Pro ?Subtitles|From 9:16 to 16:9|Static Watermark Remover|Auto Detector|AI Quantizer|AI Forensics|DAW Align|Music Restoration|Mastering|Teddy (?:Walk|Sing)|MilkDrop|Winamp|FFmpeg|Whisper|Demucs|Gradio|Colab|Canvas2D|WebM|H\.264|H\.265|OpenAI|NVIDIA|Gemini|COCO|CUDA|MPS|Metal)\b/giu;

function escapeRegExp(value: string) { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }

function replacementCase(source: string, translated: string) {
  if (source.length > 1 && source === source.toUpperCase()) return translated.toUpperCase();
  if (source[0] === source[0]?.toUpperCase()) return translated[0]?.toUpperCase() + translated.slice(1);
  return translated[0]?.toLowerCase() + translated.slice(1);
}

function compileCatalogue(language: UiLanguage) {
  const translations = new Map<string, string>();
  for (const [italian, english] of PAIRS) {
    const source = language === "en" ? italian : english;
    const target = language === "en" ? english : italian;
    // English articles such as "a" are valid Italian words too: never reverse them in isolation.
    if (language === "it" && source.length < 3) continue;
    if (!translations.has(source.toLowerCase())) translations.set(source.toLowerCase(), target);
  }
  const phrases = [...translations.keys()].sort((a, b) => b.length - a.length).map(escapeRegExp);
  return { translations, pattern: new RegExp(`(?<![\\p{L}\\p{N}_])(?:${phrases.join("|")})(?![\\p{L}\\p{N}_])`, "giu") };
}

// Compile once, not hundreds of regular expressions for each DOM mutation.
const catalogues = { it: compileCatalogue("it"), en: compileCatalogue("en") };

export function localizeUiText(value: string, language: UiLanguage, exactOnly = false): string {
  const trimmed = value.trim();
  if (!trimmed || /^(?:[A-Za-z]:[\\/]|\/|https?:\/\/)/.test(trimmed)) return value;
  const { translations, pattern } = catalogues[language];
  // Complete reviewed phrases take priority, including phrases containing product names.
  const exact = translations.get(trimmed.toLowerCase());
  if (exact) return value.replace(trimmed, replacementCase(trimmed, exact));
  if (exactOnly) return value;
  const protectedValues: string[] = [];
  const protectedText = value.replace(PROTECTED_UI_TERMS, (match) => `\uE000${protectedValues.push(match) - 1}\uE001`);
  // Single pass: replacement text must never be translated again in this call.
  const output = protectedText.replace(pattern, (match) => replacementCase(match, translations.get(match.toLowerCase()) ?? match));
  return output.replace(/\uE000(\d+)\uE001/g, (_match, index: string) => protectedValues[Number(index)] ?? "");
}
